// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClientCompletions = `-- name: CountClientCompletions :one
SELECT COUNT(*)::int AS total
FROM mentorix.client_workout_completions
WHERE trainer_id = $1
  AND client_user_id = $2
  AND ($3::timestamptz IS NULL OR completed_at >= $3)
  AND ($4::timestamptz IS NULL OR completed_at < $4)
`

type CountClientCompletionsParams struct {
	TrainerID    pgtype.UUID        `json:"trainer_id"`
	ClientUserID pgtype.UUID        `json:"client_user_id"`
	FromAt       pgtype.Timestamptz `json:"from_at"`
	ToAt         pgtype.Timestamptz `json:"to_at"`
}

func (q *Queries) CountClientCompletions(ctx context.Context, arg CountClientCompletionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countClientCompletions,
		arg.TrainerID,
		arg.ClientUserID,
		arg.FromAt,
		arg.ToAt,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getClientActivityStats = `-- name: GetClientActivityStats :one
SELECT
  COUNT(*)::int AS total_completions,
  COUNT(*) FILTER (WHERE completed_at >= $3)::int AS completions_last_7_days,
  COUNT(*) FILTER (WHERE completed_at >= $4)::int AS completions_last_30_days,
  MIN(completed_at) AS first_completed_at,
  MAX(completed_at) AS last_completed_at
FROM mentorix.client_workout_completions
WHERE trainer_id = $1
  AND client_user_id = $2
`

type GetClientActivityStatsParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
	Since7d      time.Time   `json:"since_7d"`
	Since30d     time.Time   `json:"since_30d"`
}

type GetClientActivityStatsRow struct {
	TotalCompletions      int32       `json:"total_completions"`
	CompletionsLast7Days  int32       `json:"completions_last_7_days"`
	CompletionsLast30Days int32       `json:"completions_last_30_days"`
	FirstCompletedAt      interface{} `json:"first_completed_at"`
	LastCompletedAt       interface{} `json:"last_completed_at"`
}

func (q *Queries) GetClientActivityStats(ctx context.Context, arg GetClientActivityStatsParams) (GetClientActivityStatsRow, error) {
	row := q.db.QueryRow(ctx, getClientActivityStats,
		arg.TrainerID,
		arg.ClientUserID,
		arg.Since7d,
		arg.Since30d,
	)
	var i GetClientActivityStatsRow
	err := row.Scan(
		&i.TotalCompletions,
		&i.CompletionsLast7Days,
		&i.CompletionsLast30Days,
		&i.FirstCompletedAt,
		&i.LastCompletedAt,
	)
	return i, err
}

const getClientAnalyticsHeader = `-- name: GetClientAnalyticsHeader :one

SELECT
  tc.client_user_id,
  u.display_name,
  u.avatar_file_path,
  tc.status,
  tc.created_at AS linked_at,
  (
    SELECT MAX(cwc.completed_at)
    FROM mentorix.client_workout_completions cwc
    WHERE cwc.client_user_id = tc.client_user_id
  ) AS last_active_at
FROM mentorix.trainer_clients tc
INNER JOIN mentorix.users u ON u.id = tc.client_user_id
WHERE tc.trainer_id = $1
  AND tc.client_user_id = $2
`

type GetClientAnalyticsHeaderParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

type GetClientAnalyticsHeaderRow struct {
	ClientUserID   pgtype.UUID `json:"client_user_id"`
	DisplayName    string      `json:"display_name"`
	AvatarFilePath string      `json:"avatar_file_path"`
	Status         string      `json:"status"`
	LinkedAt       time.Time   `json:"linked_at"`
	LastActiveAt   interface{} `json:"last_active_at"`
}

// Trainer analytics: read-only aggregates over client_workout_completions,
// program_assignments and program version trees.
func (q *Queries) GetClientAnalyticsHeader(ctx context.Context, arg GetClientAnalyticsHeaderParams) (GetClientAnalyticsHeaderRow, error) {
	row := q.db.QueryRow(ctx, getClientAnalyticsHeader, arg.TrainerID, arg.ClientUserID)
	var i GetClientAnalyticsHeaderRow
	err := row.Scan(
		&i.ClientUserID,
		&i.DisplayName,
		&i.AvatarFilePath,
		&i.Status,
		&i.LinkedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getClientCurrentAssignmentAnalytics = `-- name: GetClientCurrentAssignmentAnalytics :one
SELECT
  pa.program_id,
  pa.program_version_id,
  pa.completion_cycle_id,
  pa.assigned_at,
  pv.name AS program_name,
  pv.name_ru AS program_name_ru,
  (
    pa.program_version_id IS DISTINCT FROM (
      SELECT lpv.id
      FROM mentorix.program_versions lpv
      WHERE lpv.program_id = pa.program_id
      ORDER BY lpv.version_number DESC
      LIMIT 1
    )
  )::boolean AS is_behind_latest
FROM mentorix.program_assignments pa
INNER JOIN mentorix.program_versions pv ON pv.id = pa.program_version_id
WHERE pa.trainer_id = $1
  AND pa.client_user_id = $2
  AND pa.status = 'active'
`

type GetClientCurrentAssignmentAnalyticsParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

type GetClientCurrentAssignmentAnalyticsRow struct {
	ProgramID         pgtype.UUID `json:"program_id"`
	ProgramVersionID  pgtype.UUID `json:"program_version_id"`
	CompletionCycleID pgtype.UUID `json:"completion_cycle_id"`
	AssignedAt        time.Time   `json:"assigned_at"`
	ProgramName       string      `json:"program_name"`
	ProgramNameRu     string      `json:"program_name_ru"`
	IsBehindLatest    bool        `json:"is_behind_latest"`
}

func (q *Queries) GetClientCurrentAssignmentAnalytics(ctx context.Context, arg GetClientCurrentAssignmentAnalyticsParams) (GetClientCurrentAssignmentAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getClientCurrentAssignmentAnalytics, arg.TrainerID, arg.ClientUserID)
	var i GetClientCurrentAssignmentAnalyticsRow
	err := row.Scan(
		&i.ProgramID,
		&i.ProgramVersionID,
		&i.CompletionCycleID,
		&i.AssignedAt,
		&i.ProgramName,
		&i.ProgramNameRu,
		&i.IsBehindLatest,
	)
	return i, err
}

const getProgramAnalyticsHeader = `-- name: GetProgramAnalyticsHeader :one
SELECT
  p.id AS program_id,
  p.created_by,
  p.name,
  p.name_ru,
  p.status,
  (
    SELECT COALESCE(MAX(pv.version_number), 0)
    FROM mentorix.program_versions pv
    WHERE pv.program_id = p.id
  )::int AS latest_version_number,
  (
    SELECT COUNT(DISTINCT d.id)
    FROM mentorix.program_week_days d
    JOIN mentorix.program_weeks w ON w.id = d.week_id
    WHERE w.program_id = p.id
      AND EXISTS (
        SELECT 1
        FROM mentorix.program_week_day_blocks b
        WHERE b.program_week_day_id = d.id
      )
  )::int AS training_days_count
FROM mentorix.programs p
WHERE p.id = $1
  AND p.deleted_at IS NULL
`

type GetProgramAnalyticsHeaderRow struct {
	ProgramID           pgtype.UUID `json:"program_id"`
	CreatedBy           pgtype.UUID `json:"created_by"`
	Name                string      `json:"name"`
	NameRu              string      `json:"name_ru"`
	Status              string      `json:"status"`
	LatestVersionNumber int32       `json:"latest_version_number"`
	TrainingDaysCount   int32       `json:"training_days_count"`
}

func (q *Queries) GetProgramAnalyticsHeader(ctx context.Context, id pgtype.UUID) (GetProgramAnalyticsHeaderRow, error) {
	row := q.db.QueryRow(ctx, getProgramAnalyticsHeader, id)
	var i GetProgramAnalyticsHeaderRow
	err := row.Scan(
		&i.ProgramID,
		&i.CreatedBy,
		&i.Name,
		&i.NameRu,
		&i.Status,
		&i.LatestVersionNumber,
		&i.TrainingDaysCount,
	)
	return i, err
}

const getProgramCompletionTotals = `-- name: GetProgramCompletionTotals :one
SELECT
  COUNT(*)::int AS total_completions,
  COUNT(*) FILTER (WHERE completed_at >= $3)::int AS completions_last_30_days,
  MAX(completed_at) AS last_activity_at
FROM mentorix.client_workout_completions
WHERE trainer_id = $1
  AND program_id = $2
`

type GetProgramCompletionTotalsParams struct {
	TrainerID pgtype.UUID `json:"trainer_id"`
	ProgramID pgtype.UUID `json:"program_id"`
	Since30d  time.Time   `json:"since_30d"`
}

type GetProgramCompletionTotalsRow struct {
	TotalCompletions      int32       `json:"total_completions"`
	CompletionsLast30Days int32       `json:"completions_last_30_days"`
	LastActivityAt        interface{} `json:"last_activity_at"`
}

func (q *Queries) GetProgramCompletionTotals(ctx context.Context, arg GetProgramCompletionTotalsParams) (GetProgramCompletionTotalsRow, error) {
	row := q.db.QueryRow(ctx, getProgramCompletionTotals, arg.TrainerID, arg.ProgramID, arg.Since30d)
	var i GetProgramCompletionTotalsRow
	err := row.Scan(&i.TotalCompletions, &i.CompletionsLast30Days, &i.LastActivityAt)
	return i, err
}

const listClientCompletionWeeks = `-- name: ListClientCompletionWeeks :many
SELECT DISTINCT date_trunc('week', completed_at AT TIME ZONE 'UTC')::timestamp AS week_start
FROM mentorix.client_workout_completions
WHERE trainer_id = $1
  AND client_user_id = $2
ORDER BY week_start DESC
LIMIT 520
`

type ListClientCompletionWeeksParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

// Distinct ISO weeks (UTC) with at least one completion, newest first (streak input).
// AT TIME ZONE 'UTC' makes truncation independent of the DB session timezone.
func (q *Queries) ListClientCompletionWeeks(ctx context.Context, arg ListClientCompletionWeeksParams) ([]pgtype.Timestamp, error) {
	rows, err := q.db.Query(ctx, listClientCompletionWeeks, arg.TrainerID, arg.ClientUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Timestamp{}
	for rows.Next() {
		var week_start pgtype.Timestamp
		if err := rows.Scan(&week_start); err != nil {
			return nil, err
		}
		items = append(items, week_start)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientCompletions = `-- name: ListClientCompletions :many
SELECT
  cwc.id,
  cwc.completed_at,
  cwc.program_id,
  cwc.program_name,
  cwc.program_name_ru,
  cwc.week_number,
  cwc.day_number,
  cwc.result_text,
  COALESCE(cwc.completion_cycle_id = pa.completion_cycle_id, false)::boolean AS is_current_cycle
FROM mentorix.client_workout_completions cwc
LEFT JOIN mentorix.program_assignments pa
  ON pa.trainer_id = cwc.trainer_id
  AND pa.client_user_id = cwc.client_user_id
  AND pa.status = 'active'
WHERE cwc.trainer_id = $1
  AND cwc.client_user_id = $2
  AND ($3::timestamptz IS NULL OR cwc.completed_at >= $3)
  AND ($4::timestamptz IS NULL OR cwc.completed_at < $4)
ORDER BY cwc.completed_at DESC, cwc.id DESC
LIMIT $6 OFFSET $5
`

type ListClientCompletionsParams struct {
	TrainerID    pgtype.UUID        `json:"trainer_id"`
	ClientUserID pgtype.UUID        `json:"client_user_id"`
	FromAt       pgtype.Timestamptz `json:"from_at"`
	ToAt         pgtype.Timestamptz `json:"to_at"`
	Offset       int32              `json:"offset"`
	Limit        int32              `json:"limit"`
}

type ListClientCompletionsRow struct {
	ID             pgtype.UUID `json:"id"`
	CompletedAt    time.Time   `json:"completed_at"`
	ProgramID      pgtype.UUID `json:"program_id"`
	ProgramName    string      `json:"program_name"`
	ProgramNameRu  string      `json:"program_name_ru"`
	WeekNumber     int32       `json:"week_number"`
	DayNumber      int32       `json:"day_number"`
	ResultText     string      `json:"result_text"`
	IsCurrentCycle bool        `json:"is_current_cycle"`
}

func (q *Queries) ListClientCompletions(ctx context.Context, arg ListClientCompletionsParams) ([]ListClientCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listClientCompletions,
		arg.TrainerID,
		arg.ClientUserID,
		arg.FromAt,
		arg.ToAt,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientCompletionsRow{}
	for rows.Next() {
		var i ListClientCompletionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompletedAt,
			&i.ProgramID,
			&i.ProgramName,
			&i.ProgramNameRu,
			&i.WeekNumber,
			&i.DayNumber,
			&i.ResultText,
			&i.IsCurrentCycle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientProgramActivity = `-- name: ListClientProgramActivity :many
SELECT
  program_id,
  (array_agg(program_name ORDER BY completed_at DESC))[1]::text AS program_name,
  (array_agg(program_name_ru ORDER BY completed_at DESC))[1]::text AS program_name_ru,
  COUNT(*)::int AS total_completions,
  MIN(completed_at) AS first_completed_at,
  MAX(completed_at) AS last_completed_at
FROM mentorix.client_workout_completions
WHERE trainer_id = $1
  AND client_user_id = $2
GROUP BY program_id
ORDER BY MAX(completed_at) DESC
`

type ListClientProgramActivityParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

type ListClientProgramActivityRow struct {
	ProgramID        pgtype.UUID `json:"program_id"`
	ProgramName      string      `json:"program_name"`
	ProgramNameRu    string      `json:"program_name_ru"`
	TotalCompletions int32       `json:"total_completions"`
	FirstCompletedAt interface{} `json:"first_completed_at"`
	LastCompletedAt  interface{} `json:"last_completed_at"`
}

// Lifetime totals per program across all cycles and versions.
// Names come from the journal snapshot so deleted programs still show up.
func (q *Queries) ListClientProgramActivity(ctx context.Context, arg ListClientProgramActivityParams) ([]ListClientProgramActivityRow, error) {
	rows, err := q.db.Query(ctx, listClientProgramActivity, arg.TrainerID, arg.ClientUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientProgramActivityRow{}
	for rows.Next() {
		var i ListClientProgramActivityRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.ProgramName,
			&i.ProgramNameRu,
			&i.TotalCompletions,
			&i.FirstCompletedAt,
			&i.LastCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCycleWeekProgress = `-- name: ListCycleWeekProgress :many
SELECT
  w.week_number,
  COUNT(d.id) FILTER (
    WHERE EXISTS (
      SELECT 1
      FROM mentorix.program_version_week_day_blocks b
      WHERE b.program_version_week_day_id = d.id
    )
  )::int AS total_days,
  COUNT(d.id) FILTER (
    WHERE EXISTS (
      SELECT 1
      FROM mentorix.client_workout_completions c
      WHERE c.completion_cycle_id = $2
        AND c.day_key = d.day_key
    )
  )::int AS completed_days
FROM mentorix.program_version_weeks w
LEFT JOIN mentorix.program_version_week_days d ON d.program_version_week_id = w.id
WHERE w.program_version_id = $1
GROUP BY w.week_number
ORDER BY w.week_number ASC
`

type ListCycleWeekProgressParams struct {
	ProgramVersionID  pgtype.UUID `json:"program_version_id"`
	CompletionCycleID pgtype.UUID `json:"completion_cycle_id"`
}

type ListCycleWeekProgressRow struct {
	WeekNumber    int32 `json:"week_number"`
	TotalDays     int32 `json:"total_days"`
	CompletedDays int32 `json:"completed_days"`
}

// Per week of the assigned version: training days (days with blocks)
// and how many of them are completed in the given cycle.
func (q *Queries) ListCycleWeekProgress(ctx context.Context, arg ListCycleWeekProgressParams) ([]ListCycleWeekProgressRow, error) {
	rows, err := q.db.Query(ctx, listCycleWeekProgress, arg.ProgramVersionID, arg.CompletionCycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCycleWeekProgressRow{}
	for rows.Next() {
		var i ListCycleWeekProgressRow
		if err := rows.Scan(&i.WeekNumber, &i.TotalDays, &i.CompletedDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestVersionWeekTrainingDays = `-- name: ListLatestVersionWeekTrainingDays :many
SELECT
  d.day_number,
  d.day_key
FROM mentorix.program_version_week_days d
INNER JOIN mentorix.program_version_weeks w ON w.id = d.program_version_week_id
INNER JOIN mentorix.program_versions pv ON pv.id = d.program_version_id
WHERE pv.program_id = $1
  AND w.week_number = $2
  AND pv.version_number = (
    SELECT COALESCE(MAX(lpv.version_number), 0)
    FROM mentorix.program_versions lpv
    WHERE lpv.program_id = $1
  )
  AND EXISTS (
    SELECT 1
    FROM mentorix.program_version_week_day_blocks b
    WHERE b.program_version_week_day_id = d.id
  )
ORDER BY d.day_number ASC
`

type ListLatestVersionWeekTrainingDaysParams struct {
	ProgramID  pgtype.UUID `json:"program_id"`
	WeekNumber int32       `json:"week_number"`
}

type ListLatestVersionWeekTrainingDaysRow struct {
	DayNumber int32       `json:"day_number"`
	DayKey    pgtype.UUID `json:"day_key"`
}

// Training days (days with blocks) of week_number in the latest published version.
func (q *Queries) ListLatestVersionWeekTrainingDays(ctx context.Context, arg ListLatestVersionWeekTrainingDaysParams) ([]ListLatestVersionWeekTrainingDaysRow, error) {
	rows, err := q.db.Query(ctx, listLatestVersionWeekTrainingDays, arg.ProgramID, arg.WeekNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestVersionWeekTrainingDaysRow{}
	for rows.Next() {
		var i ListLatestVersionWeekTrainingDaysRow
		if err := rows.Scan(&i.DayNumber, &i.DayKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramAnalyticsClients = `-- name: ListProgramAnalyticsClients :many
SELECT
  pa.client_user_id,
  u.display_name,
  u.avatar_file_path,
  pa.assigned_at,
  (
    pa.program_version_id IS DISTINCT FROM (
      SELECT lpv.id
      FROM mentorix.program_versions lpv
      WHERE lpv.program_id = pa.program_id
      ORDER BY lpv.version_number DESC
      LIMIT 1
    )
  )::boolean AS is_behind_latest,
  (
    SELECT COUNT(*)
    FROM mentorix.program_version_week_days d
    WHERE d.program_version_id = pa.program_version_id
      AND EXISTS (
        SELECT 1
        FROM mentorix.program_version_week_day_blocks b
        WHERE b.program_version_week_day_id = d.id
      )
  )::int AS total_training_days,
  (
    SELECT COUNT(*)
    FROM mentorix.client_workout_completions c
    WHERE c.completion_cycle_id = pa.completion_cycle_id
      AND c.day_key IN (
        SELECT d2.day_key
        FROM mentorix.program_version_week_days d2
        WHERE d2.program_version_id = pa.program_version_id
      )
  )::int AS completed_days,
  (
    SELECT MAX(c.completed_at)
    FROM mentorix.client_workout_completions c
    WHERE c.trainer_id = pa.trainer_id
      AND c.client_user_id = pa.client_user_id
      AND c.program_id = pa.program_id
  ) AS last_completed_at
FROM mentorix.program_assignments pa
INNER JOIN mentorix.users u ON u.id = pa.client_user_id
WHERE pa.program_id = $1
  AND pa.status = 'active'
ORDER BY u.display_name ASC, pa.client_user_id ASC
`

type ListProgramAnalyticsClientsRow struct {
	ClientUserID      pgtype.UUID `json:"client_user_id"`
	DisplayName       string      `json:"display_name"`
	AvatarFilePath    string      `json:"avatar_file_path"`
	AssignedAt        time.Time   `json:"assigned_at"`
	IsBehindLatest    bool        `json:"is_behind_latest"`
	TotalTrainingDays int32       `json:"total_training_days"`
	CompletedDays     int32       `json:"completed_days"`
	LastCompletedAt   interface{} `json:"last_completed_at"`
}

// Active assignees of the program with per-cycle progress.
func (q *Queries) ListProgramAnalyticsClients(ctx context.Context, programID pgtype.UUID) ([]ListProgramAnalyticsClientsRow, error) {
	rows, err := q.db.Query(ctx, listProgramAnalyticsClients, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramAnalyticsClientsRow{}
	for rows.Next() {
		var i ListProgramAnalyticsClientsRow
		if err := rows.Scan(
			&i.ClientUserID,
			&i.DisplayName,
			&i.AvatarFilePath,
			&i.AssignedAt,
			&i.IsBehindLatest,
			&i.TotalTrainingDays,
			&i.CompletedDays,
			&i.LastCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramAnalyticsWeeks = `-- name: ListProgramAnalyticsWeeks :many
SELECT
  c.week_number,
  COUNT(*)::int AS completions_count,
  COUNT(DISTINCT c.client_user_id)::int AS distinct_clients_count
FROM mentorix.client_workout_completions c
INNER JOIN mentorix.program_assignments pa
  ON pa.completion_cycle_id = c.completion_cycle_id
  AND pa.status = 'active'
WHERE pa.program_id = $1
GROUP BY c.week_number
ORDER BY c.week_number ASC
`

type ListProgramAnalyticsWeeksRow struct {
	WeekNumber           int32 `json:"week_number"`
	CompletionsCount     int32 `json:"completions_count"`
	DistinctClientsCount int32 `json:"distinct_clients_count"`
}

// Drop-off by program week: current-cycle completions of active assignees.
func (q *Queries) ListProgramAnalyticsWeeks(ctx context.Context, programID pgtype.UUID) ([]ListProgramAnalyticsWeeksRow, error) {
	rows, err := q.db.Query(ctx, listProgramAnalyticsWeeks, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramAnalyticsWeeksRow{}
	for rows.Next() {
		var i ListProgramAnalyticsWeeksRow
		if err := rows.Scan(&i.WeekNumber, &i.CompletionsCount, &i.DistinctClientsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramWeekCompletions = `-- name: ListProgramWeekCompletions :many
SELECT
  c.id,
  c.client_user_id,
  c.day_key,
  c.day_number,
  c.result_text,
  c.completed_at
FROM mentorix.client_workout_completions c
INNER JOIN mentorix.program_assignments pa
  ON pa.completion_cycle_id = c.completion_cycle_id
  AND pa.status = 'active'
WHERE pa.program_id = $1
  AND c.week_number = $2
`

type ListProgramWeekCompletionsParams struct {
	ProgramID  pgtype.UUID `json:"program_id"`
	WeekNumber int32       `json:"week_number"`
}

type ListProgramWeekCompletionsRow struct {
	ID           pgtype.UUID `json:"id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
	DayKey       pgtype.UUID `json:"day_key"`
	DayNumber    int32       `json:"day_number"`
	ResultText   string      `json:"result_text"`
	CompletedAt  time.Time   `json:"completed_at"`
}

// Current-cycle completions of active assignees for one program week.
func (q *Queries) ListProgramWeekCompletions(ctx context.Context, arg ListProgramWeekCompletionsParams) ([]ListProgramWeekCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listProgramWeekCompletions, arg.ProgramID, arg.WeekNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramWeekCompletionsRow{}
	for rows.Next() {
		var i ListProgramWeekCompletionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientUserID,
			&i.DayKey,
			&i.DayNumber,
			&i.ResultText,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramWeekMatrixClients = `-- name: ListProgramWeekMatrixClients :many
SELECT
  pa.client_user_id,
  u.display_name,
  u.avatar_file_path,
  pa.completion_cycle_id,
  (
    pa.program_version_id IS DISTINCT FROM (
      SELECT lpv.id
      FROM mentorix.program_versions lpv
      WHERE lpv.program_id = pa.program_id
      ORDER BY lpv.version_number DESC
      LIMIT 1
    )
  )::boolean AS is_behind_latest
FROM mentorix.program_assignments pa
INNER JOIN mentorix.users u ON u.id = pa.client_user_id
WHERE pa.program_id = $1
  AND pa.status = 'active'
ORDER BY u.display_name ASC, pa.client_user_id ASC
`

type ListProgramWeekMatrixClientsRow struct {
	ClientUserID      pgtype.UUID `json:"client_user_id"`
	DisplayName       string      `json:"display_name"`
	AvatarFilePath    string      `json:"avatar_file_path"`
	CompletionCycleID pgtype.UUID `json:"completion_cycle_id"`
	IsBehindLatest    bool        `json:"is_behind_latest"`
}

// Active assignees for the week-results matrix (cycle id for completion join).
func (q *Queries) ListProgramWeekMatrixClients(ctx context.Context, programID pgtype.UUID) ([]ListProgramWeekMatrixClientsRow, error) {
	rows, err := q.db.Query(ctx, listProgramWeekMatrixClients, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramWeekMatrixClientsRow{}
	for rows.Next() {
		var i ListProgramWeekMatrixClientsRow
		if err := rows.Scan(
			&i.ClientUserID,
			&i.DisplayName,
			&i.AvatarFilePath,
			&i.CompletionCycleID,
			&i.IsBehindLatest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainerProgramsAnalytics = `-- name: ListTrainerProgramsAnalytics :many
WITH assignment_progress AS (
  SELECT
    pa.program_id,
    (
      SELECT COUNT(*)
      FROM mentorix.program_version_week_days d
      WHERE d.program_version_id = pa.program_version_id
        AND EXISTS (
          SELECT 1
          FROM mentorix.program_version_week_day_blocks b
          WHERE b.program_version_week_day_id = d.id
        )
    )::int AS total_days,
    (
      SELECT COUNT(*)
      FROM mentorix.client_workout_completions c
      WHERE c.completion_cycle_id = pa.completion_cycle_id
        AND c.day_key IN (
          SELECT d2.day_key
          FROM mentorix.program_version_week_days d2
          WHERE d2.program_version_id = pa.program_version_id
        )
    )::int AS completed_days
  FROM mentorix.program_assignments pa
  WHERE pa.trainer_id = $6
    AND pa.status = 'active'
),
completion_totals AS (
  SELECT
    cwc.program_id,
    COUNT(*)::int AS total_completions,
    COUNT(*) FILTER (WHERE cwc.completed_at >= $7)::int AS completions_last_30_days,
    MAX(cwc.completed_at) AS last_activity_at
  FROM mentorix.client_workout_completions cwc
  WHERE cwc.trainer_id = $6
    AND cwc.program_id IS NOT NULL
  GROUP BY cwc.program_id
)
SELECT
  p.id AS program_id,
  p.name,
  p.name_ru,
  p.status,
  (
    SELECT COUNT(DISTINCT d.id)
    FROM mentorix.program_week_days d
    JOIN mentorix.program_weeks w ON w.id = d.week_id
    WHERE w.program_id = p.id
      AND EXISTS (
        SELECT 1
        FROM mentorix.program_week_day_blocks b
        WHERE b.program_week_day_id = d.id
      )
  )::int AS training_days_count,
  COALESCE(ap.active_clients_count, 0)::int AS active_clients_count,
  COALESCE(ct.total_completions, 0)::int AS total_completions,
  COALESCE(ct.completions_last_30_days, 0)::int AS completions_last_30_days,
  COALESCE(ap.avg_completion_percent, 0)::float AS avg_completion_percent,
  ct.last_activity_at
FROM mentorix.programs p
LEFT JOIN (
  SELECT
    program_id,
    COUNT(*)::int AS active_clients_count,
    AVG(
      LEAST(completed_days::float / NULLIF(total_days, 0), 1.0) * 100.0
    )::float AS avg_completion_percent
  FROM assignment_progress
  GROUP BY program_id
) ap ON ap.program_id = p.id
LEFT JOIN completion_totals ct ON ct.program_id = p.id
WHERE p.created_by = $1
  AND p.deleted_at IS NULL
ORDER BY
  CASE WHEN $2 = 'name' AND $3 = 'asc' THEN p.name END ASC NULLS LAST,
  CASE WHEN $2 = 'name' AND $3 = 'desc' THEN p.name END DESC NULLS LAST,
  CASE WHEN $2 = 'last_activity' AND $3 = 'asc' THEN ct.last_activity_at END ASC NULLS LAST,
  CASE WHEN $2 = 'last_activity' AND $3 = 'desc' THEN ct.last_activity_at END DESC NULLS LAST,
  p.id ASC
LIMIT $5 OFFSET $4
`

type ListTrainerProgramsAnalyticsParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	SortBy    interface{} `json:"sort_by"`
	SortOrder interface{} `json:"sort_order"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
	TrainerID pgtype.UUID `json:"trainer_id"`
	Since30d  time.Time   `json:"since_30d"`
}

type ListTrainerProgramsAnalyticsRow struct {
	ProgramID             pgtype.UUID `json:"program_id"`
	Name                  string      `json:"name"`
	NameRu                string      `json:"name_ru"`
	Status                string      `json:"status"`
	TrainingDaysCount     int32       `json:"training_days_count"`
	ActiveClientsCount    int32       `json:"active_clients_count"`
	TotalCompletions      int32       `json:"total_completions"`
	CompletionsLast30Days int32       `json:"completions_last_30_days"`
	AvgCompletionPercent  float64     `json:"avg_completion_percent"`
	LastActivityAt        interface{} `json:"last_activity_at"`
}

// One row per non-deleted program owned by the trainer, with completion aggregates.
func (q *Queries) ListTrainerProgramsAnalytics(ctx context.Context, arg ListTrainerProgramsAnalyticsParams) ([]ListTrainerProgramsAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, listTrainerProgramsAnalytics,
		arg.CreatedBy,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
		arg.TrainerID,
		arg.Since30d,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrainerProgramsAnalyticsRow{}
	for rows.Next() {
		var i ListTrainerProgramsAnalyticsRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.Name,
			&i.NameRu,
			&i.Status,
			&i.TrainingDaysCount,
			&i.ActiveClientsCount,
			&i.TotalCompletions,
			&i.CompletionsLast30Days,
			&i.AvgCompletionPercent,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
