// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserIdentitiesOutsideProviders = `-- name: CountUserIdentitiesOutsideProviders :one
SELECT count(*)
FROM mentorix.auth_identities
WHERE user_id = $1
  AND NOT (provider = ANY ($2::text[]))
`

type CountUserIdentitiesOutsideProvidersParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Providers []string    `json:"providers"`
}

func (q *Queries) CountUserIdentitiesOutsideProviders(ctx context.Context, arg CountUserIdentitiesOutsideProvidersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserIdentitiesOutsideProviders, arg.UserID, arg.Providers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserByID = `-- name: DeleteUserByID :execrows
DELETE FROM mentorix.users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserWithoutIdentity = `-- name: DeleteUserWithoutIdentity :exec
DELETE FROM mentorix.users u
WHERE u.id = $1
  AND NOT EXISTS (SELECT 1 FROM mentorix.auth_identities i WHERE i.user_id = u.id)
`

func (q *Queries) DeleteUserWithoutIdentity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserWithoutIdentity, id)
	return err
}

const fillUserPrimaryEmailIfEmpty = `-- name: FillUserPrimaryEmailIfEmpty :exec
UPDATE mentorix.users u
SET primary_email = src.primary_email
FROM mentorix.users src
WHERE u.id = $1
  AND src.id = $2
  AND (u.primary_email IS NULL OR u.primary_email = '')
  AND src.primary_email IS NOT NULL
  AND src.primary_email <> ''
`

type FillUserPrimaryEmailIfEmptyParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	FromUserID pgtype.UUID `json:"from_user_id"`
}

func (q *Queries) FillUserPrimaryEmailIfEmpty(ctx context.Context, arg FillUserPrimaryEmailIfEmptyParams) error {
	_, err := q.db.Exec(ctx, fillUserPrimaryEmailIfEmpty, arg.UserID, arg.FromUserID)
	return err
}

const getEmailPasswordIdentity = `-- name: GetEmailPasswordIdentity :one
SELECT user_id, COALESCE(password_hash, '') AS password_hash
FROM mentorix.auth_identities
WHERE provider = $1 AND subject = $2
`

type GetEmailPasswordIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

type GetEmailPasswordIdentityRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) GetEmailPasswordIdentity(ctx context.Context, arg GetEmailPasswordIdentityParams) (GetEmailPasswordIdentityRow, error) {
	row := q.db.QueryRow(ctx, getEmailPasswordIdentity, arg.Provider, arg.Subject)
	var i GetEmailPasswordIdentityRow
	err := row.Scan(&i.UserID, &i.PasswordHash)
	return i, err
}

const getRefreshSessionUserForUpdate = `-- name: GetRefreshSessionUserForUpdate :one
SELECT user_id
FROM mentorix.auth_refresh_sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
FOR UPDATE
`

func (q *Queries) GetRefreshSessionUserForUpdate(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionUserForUpdate, tokenHash)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserAvatarFilePath = `-- name: GetUserAvatarFilePath :one
SELECT avatar_file_path
FROM mentorix.users
WHERE id = $1
`

func (q *Queries) GetUserAvatarFilePath(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserAvatarFilePath, id)
	var avatar_file_path string
	err := row.Scan(&avatar_file_path)
	return avatar_file_path, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  COALESCE(primary_email, '') AS primary_email,
  display_name,
  created_at
FROM mentorix.users
WHERE id = $1
`

type GetUserByIDRow struct {
	PrimaryEmail string    `json:"primary_email"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.PrimaryEmail, &i.DisplayName, &i.CreatedAt)
	return i, err
}

const grantUserRole = `-- name: GrantUserRole :exec
INSERT INTO mentorix.user_roles (user_id, role)
VALUES ($1, $2)
ON CONFLICT (user_id, role) DO NOTHING
`

type GrantUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) GrantUserRole(ctx context.Context, arg GrantUserRoleParams) error {
	_, err := q.db.Exec(ctx, grantUserRole, arg.UserID, arg.Role)
	return err
}

const insertAuthIdentity = `-- name: InsertAuthIdentity :exec
INSERT INTO mentorix.auth_identities (user_id, provider, subject, password_hash)
VALUES ($1, $2, $3, $4)
`

type InsertAuthIdentityParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Provider     string      `json:"provider"`
	Subject      string      `json:"subject"`
	PasswordHash *string     `json:"password_hash"`
}

func (q *Queries) InsertAuthIdentity(ctx context.Context, arg InsertAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, insertAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.PasswordHash,
	)
	return err
}

const insertAuthIdentityIfAbsent = `-- name: InsertAuthIdentityIfAbsent :execrows
INSERT INTO mentorix.auth_identities (user_id, provider, subject, password_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT auth_identities_provider_subject_uniq DO NOTHING
`

type InsertAuthIdentityIfAbsentParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Provider     string      `json:"provider"`
	Subject      string      `json:"subject"`
	PasswordHash *string     `json:"password_hash"`
}

func (q *Queries) InsertAuthIdentityIfAbsent(ctx context.Context, arg InsertAuthIdentityIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuthIdentityIfAbsent,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.PasswordHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRefreshSession = `-- name: InsertRefreshSession :exec
INSERT INTO mentorix.auth_refresh_sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertRefreshSessionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash []byte      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) InsertRefreshSession(ctx context.Context, arg InsertRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, insertRefreshSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const insertTrainer = `-- name: InsertTrainer :exec
INSERT INTO mentorix.trainers (user_id)
VALUES ($1)
`

func (q *Queries) InsertTrainer(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertTrainer, userID)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO mentorix.users (primary_email, display_name)
VALUES ($1, $2)
RETURNING id
`

type InsertUserParams struct {
	PrimaryEmail *string `json:"primary_email"`
	DisplayName  string  `json:"display_name"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.PrimaryEmail, arg.DisplayName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO mentorix.user_roles (user_id, role)
VALUES ($1, $2)
`

type InsertUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.UserID, arg.Role)
	return err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role
FROM mentorix.user_roles
WHERE user_id = $1
ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveSignInIdentitiesToUser = `-- name: MoveSignInIdentitiesToUser :execrows
UPDATE mentorix.auth_identities
SET user_id = $1
WHERE user_id = $2
  AND provider = ANY ($3::text[])
`

type MoveSignInIdentitiesToUserParams struct {
	ToUserID   pgtype.UUID `json:"to_user_id"`
	FromUserID pgtype.UUID `json:"from_user_id"`
	Providers  []string    `json:"providers"`
}

func (q *Queries) MoveSignInIdentitiesToUser(ctx context.Context, arg MoveSignInIdentitiesToUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveSignInIdentitiesToUser, arg.ToUserID, arg.FromUserID, arg.Providers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeStaleRefreshSessions = `-- name: PurgeStaleRefreshSessions :execrows
DELETE FROM mentorix.auth_refresh_sessions
WHERE (revoked_at IS NOT NULL AND revoked_at < now() - interval '30 days')
   OR (expires_at < now() - interval '30 days')
`

func (q *Queries) PurgeStaleRefreshSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleRefreshSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllUserRefreshSessions = `-- name: RevokeAllUserRefreshSessions :exec
UPDATE mentorix.auth_refresh_sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshSessions, userID)
	return err
}

const revokeRefreshSessionByHash = `-- name: RevokeRefreshSessionByHash :exec
UPDATE mentorix.auth_refresh_sessions
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshSessionByHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshSessionByHash, tokenHash)
	return err
}

const updateUserAvatarFilePath = `-- name: UpdateUserAvatarFilePath :exec
UPDATE mentorix.users
SET avatar_file_path = $2
WHERE id = $1
`

type UpdateUserAvatarFilePathParams struct {
	ID             pgtype.UUID `json:"id"`
	AvatarFilePath string      `json:"avatar_file_path"`
}

func (q *Queries) UpdateUserAvatarFilePath(ctx context.Context, arg UpdateUserAvatarFilePathParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatarFilePath, arg.ID, arg.AvatarFilePath)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :execrows
UPDATE mentorix.users
SET display_name = $2
WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userHasTrainerLink = `-- name: UserHasTrainerLink :one
SELECT EXISTS (
  SELECT 1 FROM mentorix.trainer_clients WHERE client_user_id = $1
)
`

func (q *Queries) UserHasTrainerLink(ctx context.Context, clientUserID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userHasTrainerLink, clientUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
