// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: client_workout_completion.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clientWorkoutCompletionExists = `-- name: ClientWorkoutCompletionExists :one
SELECT EXISTS(
  SELECT 1
  FROM mentorix.client_workout_completions
  WHERE completion_cycle_id = $1
    AND day_key = $2
) AS ok
`

type ClientWorkoutCompletionExistsParams struct {
	CompletionCycleID pgtype.UUID `json:"completion_cycle_id"`
	DayKey            pgtype.UUID `json:"day_key"`
}

func (q *Queries) ClientWorkoutCompletionExists(ctx context.Context, arg ClientWorkoutCompletionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, clientWorkoutCompletionExists, arg.CompletionCycleID, arg.DayKey)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const insertClientWorkoutCompletion = `-- name: InsertClientWorkoutCompletion :one
INSERT INTO mentorix.client_workout_completions (
  client_user_id,
  trainer_id,
  completed_at,
  program_id,
  program_version_id,
  program_assignment_id,
  completion_cycle_id,
  day_key,
  week_number,
  day_number,
  program_name,
  program_name_ru,
  day_snapshot,
  result_text,
  source
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, client_user_id, trainer_id, completed_at, program_id, program_version_id, program_assignment_id, completion_cycle_id, day_key, week_number, day_number, program_name, program_name_ru, day_snapshot, result_text, source, created_at
`

type InsertClientWorkoutCompletionParams struct {
	ClientUserID        pgtype.UUID `json:"client_user_id"`
	TrainerID           pgtype.UUID `json:"trainer_id"`
	CompletedAt         time.Time   `json:"completed_at"`
	ProgramID           pgtype.UUID `json:"program_id"`
	ProgramVersionID    pgtype.UUID `json:"program_version_id"`
	ProgramAssignmentID pgtype.UUID `json:"program_assignment_id"`
	CompletionCycleID   pgtype.UUID `json:"completion_cycle_id"`
	DayKey              pgtype.UUID `json:"day_key"`
	WeekNumber          int32       `json:"week_number"`
	DayNumber           int32       `json:"day_number"`
	ProgramName         string      `json:"program_name"`
	ProgramNameRu       string      `json:"program_name_ru"`
	DaySnapshot         []byte      `json:"day_snapshot"`
	ResultText          string      `json:"result_text"`
	Source              string      `json:"source"`
}

func (q *Queries) InsertClientWorkoutCompletion(ctx context.Context, arg InsertClientWorkoutCompletionParams) (MentorixClientWorkoutCompletion, error) {
	row := q.db.QueryRow(ctx, insertClientWorkoutCompletion,
		arg.ClientUserID,
		arg.TrainerID,
		arg.CompletedAt,
		arg.ProgramID,
		arg.ProgramVersionID,
		arg.ProgramAssignmentID,
		arg.CompletionCycleID,
		arg.DayKey,
		arg.WeekNumber,
		arg.DayNumber,
		arg.ProgramName,
		arg.ProgramNameRu,
		arg.DaySnapshot,
		arg.ResultText,
		arg.Source,
	)
	var i MentorixClientWorkoutCompletion
	err := row.Scan(
		&i.ID,
		&i.ClientUserID,
		&i.TrainerID,
		&i.CompletedAt,
		&i.ProgramID,
		&i.ProgramVersionID,
		&i.ProgramAssignmentID,
		&i.CompletionCycleID,
		&i.DayKey,
		&i.WeekNumber,
		&i.DayNumber,
		&i.ProgramName,
		&i.ProgramNameRu,
		&i.DaySnapshot,
		&i.ResultText,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listCompletedDayKeysByCycle = `-- name: ListCompletedDayKeysByCycle :many
SELECT day_key
FROM mentorix.client_workout_completions
WHERE completion_cycle_id = $1
`

func (q *Queries) ListCompletedDayKeysByCycle(ctx context.Context, completionCycleID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCompletedDayKeysByCycle, completionCycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var day_key pgtype.UUID
		if err := rows.Scan(&day_key); err != nil {
			return nil, err
		}
		items = append(items, day_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
