// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: health.sql

package sqlc

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

// Placeholder until domain queries land in chunk 1+. Used to verify sqlc wiring.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
