// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MentorixAuthIdentity struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Provider     string      `json:"provider"`
	Subject      string      `json:"subject"`
	PasswordHash *string     `json:"password_hash"`
	CreatedAt    time.Time   `json:"created_at"`
}

type MentorixExercise struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	NameRu          string      `json:"name_ru"`
	AddedBy         pgtype.UUID `json:"added_by"`
	ModifiedBy      pgtype.UUID `json:"modified_by"`
	ModifiedAt      time.Time   `json:"modified_at"`
	Equipment       *string     `json:"equipment"`
	Type            string      `json:"type"`
	MuscleGroup     string      `json:"muscle_group"`
	Description     string      `json:"description"`
	DescriptionRu   string      `json:"description_ru"`
	Difficulty      string      `json:"difficulty"`
	VideoUrl        string      `json:"video_url"`
	PreviewImageUrl string      `json:"preview_image_url"`
	CreatedAt       time.Time   `json:"created_at"`
}

type MentorixInvite struct {
	ID               pgtype.UUID        `json:"id"`
	TrainerUserID    pgtype.UUID        `json:"trainer_user_id"`
	Token            string             `json:"token"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	ConsumedByUserID pgtype.UUID        `json:"consumed_by_user_id"`
	CreatedAt        time.Time          `json:"created_at"`
}

type MentorixLinkCode struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Code       string             `json:"code"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type MentorixProgram struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	Status          string             `json:"status"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	Category        *string            `json:"category"`
	Difficulty      *string            `json:"difficulty"`
	PreviewImageUrl string             `json:"preview_image_url"`
	CreatedAt       time.Time          `json:"created_at"`
	ModifiedAt      time.Time          `json:"modified_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type MentorixProgramDay struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
	CreatedAt time.Time   `json:"created_at"`
}

type MentorixProgramDayExercise struct {
	ID           pgtype.UUID    `json:"id"`
	ProgramDayID pgtype.UUID    `json:"program_day_id"`
	ExerciseID   pgtype.UUID    `json:"exercise_id"`
	SortOrder    int32          `json:"sort_order"`
	Sets         *int32         `json:"sets"`
	Reps         *int32         `json:"reps"`
	WeightKg     pgtype.Numeric `json:"weight_kg"`
	Instruction  string         `json:"instruction"`
	CreatedAt    time.Time      `json:"created_at"`
}

type MentorixRefreshSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type MentorixTrainer struct {
	UserID    pgtype.UUID `json:"user_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type MentorixTrainerClient struct {
	TrainerUserID pgtype.UUID        `json:"trainer_user_id"`
	ClientUserID  pgtype.UUID        `json:"client_user_id"`
	Status        string             `json:"status"`
	BlockedAt     pgtype.Timestamptz `json:"blocked_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type MentorixUser struct {
	ID           pgtype.UUID `json:"id"`
	PrimaryEmail *string     `json:"primary_email"`
	CreatedAt    time.Time   `json:"created_at"`
}

type MentorixUserRole struct {
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
}
