// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MentorixAuthIdentity struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Provider     string      `json:"provider"`
	Subject      string      `json:"subject"`
	PasswordHash *string     `json:"password_hash"`
	CreatedAt    time.Time   `json:"created_at"`
}

type MentorixAuthRefreshSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type MentorixExercise struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	NameRu          string             `json:"name_ru"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	ModifiedAt      time.Time          `json:"modified_at"`
	Equipment       *string            `json:"equipment"`
	ExerciseType    string             `json:"exercise_type"`
	MuscleGroup     string             `json:"muscle_group"`
	Description     string             `json:"description"`
	DescriptionRu   string             `json:"description_ru"`
	Difficulty      string             `json:"difficulty"`
	VideoUrl        string             `json:"video_url"`
	PreviewImageUrl string             `json:"preview_image_url"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type MentorixProgram struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	Status          string             `json:"status"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	Category        *string            `json:"category"`
	Difficulty      *string            `json:"difficulty"`
	PreviewImageUrl string             `json:"preview_image_url"`
	CreatedAt       time.Time          `json:"created_at"`
	ModifiedAt      time.Time          `json:"modified_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	NameRu          string             `json:"name_ru"`
	DescriptionRu   string             `json:"description_ru"`
}

type MentorixProgramAssignment struct {
	ID               pgtype.UUID `json:"id"`
	ProgramID        pgtype.UUID `json:"program_id"`
	ProgramVersionID pgtype.UUID `json:"program_version_id"`
	TrainerID        pgtype.UUID `json:"trainer_id"`
	ClientUserID     pgtype.UUID `json:"client_user_id"`
	Status           string      `json:"status"`
	AssignedAt       time.Time   `json:"assigned_at"`
	CreatedAt        time.Time   `json:"created_at"`
	ModifiedAt       time.Time   `json:"modified_at"`
	CreatedBy        pgtype.UUID `json:"created_by"`
	ModifiedBy       pgtype.UUID `json:"modified_by"`
}

type MentorixProgramVersion struct {
	ID                 pgtype.UUID `json:"id"`
	ProgramID          pgtype.UUID `json:"program_id"`
	VersionNumber      int32       `json:"version_number"`
	PublishedAt        time.Time   `json:"published_at"`
	PublishedBy        pgtype.UUID `json:"published_by"`
	Name               string      `json:"name"`
	NameRu             string      `json:"name_ru"`
	Description        string      `json:"description"`
	DescriptionRu      string      `json:"description_ru"`
	Category           *string     `json:"category"`
	Difficulty         *string     `json:"difficulty"`
	PreviewImageUrl    string      `json:"preview_image_url"`
	CreatedAt          time.Time   `json:"created_at"`
	ContentFingerprint string      `json:"content_fingerprint"`
}

type MentorixProgramVersionWeek struct {
	ID               pgtype.UUID `json:"id"`
	ProgramVersionID pgtype.UUID `json:"program_version_id"`
	WeekNumber       int32       `json:"week_number"`
	SortOrder        int32       `json:"sort_order"`
	CreatedAt        time.Time   `json:"created_at"`
}

type MentorixProgramVersionWeekDay struct {
	ID                   pgtype.UUID `json:"id"`
	ProgramVersionID     pgtype.UUID `json:"program_version_id"`
	ProgramVersionWeekID pgtype.UUID `json:"program_version_week_id"`
	DayNumber            int32       `json:"day_number"`
	SortOrder            int32       `json:"sort_order"`
	CreatedAt            time.Time   `json:"created_at"`
}

type MentorixProgramVersionWeekDayBlock struct {
	ID                      pgtype.UUID `json:"id"`
	ProgramVersionWeekDayID pgtype.UUID `json:"program_version_week_day_id"`
	BlockType               string      `json:"block_type"`
	Instruction             string      `json:"instruction"`
	SortOrder               int32       `json:"sort_order"`
	CreatedAt               time.Time   `json:"created_at"`
}

type MentorixProgramVersionWeekDayBlockExercise struct {
	ID                           pgtype.UUID `json:"id"`
	ExerciseID                   pgtype.UUID `json:"exercise_id"`
	SortOrder                    int32       `json:"sort_order"`
	Sets                         *int32      `json:"sets"`
	Reps                         *int32      `json:"reps"`
	Instruction                  string      `json:"instruction"`
	CreatedAt                    time.Time   `json:"created_at"`
	ProgramVersionWeekDayBlockID pgtype.UUID `json:"program_version_week_day_block_id"`
}

type MentorixProgramWeek struct {
	ID         pgtype.UUID `json:"id"`
	ProgramID  pgtype.UUID `json:"program_id"`
	WeekNumber int32       `json:"week_number"`
	SortOrder  int32       `json:"sort_order"`
	CreatedAt  time.Time   `json:"created_at"`
	ModifiedAt time.Time   `json:"modified_at"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
}

type MentorixProgramWeekDay struct {
	ID         pgtype.UUID `json:"id"`
	ProgramID  pgtype.UUID `json:"program_id"`
	DayNumber  int32       `json:"day_number"`
	SortOrder  int32       `json:"sort_order"`
	CreatedAt  time.Time   `json:"created_at"`
	ModifiedAt time.Time   `json:"modified_at"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
	WeekID     pgtype.UUID `json:"week_id"`
}

type MentorixProgramWeekDayBlock struct {
	ID               pgtype.UUID `json:"id"`
	ProgramWeekDayID pgtype.UUID `json:"program_week_day_id"`
	BlockType        string      `json:"block_type"`
	Instruction      string      `json:"instruction"`
	SortOrder        int32       `json:"sort_order"`
	CreatedAt        time.Time   `json:"created_at"`
	ModifiedAt       time.Time   `json:"modified_at"`
	ModifiedBy       pgtype.UUID `json:"modified_by"`
}

type MentorixProgramWeekDayBlockExercise struct {
	ID                    pgtype.UUID `json:"id"`
	ExerciseID            pgtype.UUID `json:"exercise_id"`
	SortOrder             int32       `json:"sort_order"`
	Sets                  *int32      `json:"sets"`
	Reps                  *int32      `json:"reps"`
	Instruction           string      `json:"instruction"`
	CreatedAt             time.Time   `json:"created_at"`
	ModifiedAt            time.Time   `json:"modified_at"`
	ModifiedBy            pgtype.UUID `json:"modified_by"`
	ProgramWeekDayBlockID pgtype.UUID `json:"program_week_day_block_id"`
}

type MentorixTrainer struct {
	UserID    pgtype.UUID `json:"user_id"`
	CreatedAt time.Time   `json:"created_at"`
	ID        pgtype.UUID `json:"id"`
}

type MentorixTrainerClient struct {
	ClientUserID pgtype.UUID        `json:"client_user_id"`
	Status       string             `json:"status"`
	BlockedAt    pgtype.Timestamptz `json:"blocked_at"`
	CreatedAt    time.Time          `json:"created_at"`
	TrainerID    pgtype.UUID        `json:"trainer_id"`
}

type MentorixTrainerInvite struct {
	ID         pgtype.UUID        `json:"id"`
	Token      string             `json:"token"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy pgtype.UUID        `json:"consumed_by"`
	CreatedAt  time.Time          `json:"created_at"`
	TrainerID  pgtype.UUID        `json:"trainer_id"`
}

type MentorixUser struct {
	ID             pgtype.UUID `json:"id"`
	PrimaryEmail   *string     `json:"primary_email"`
	CreatedAt      time.Time   `json:"created_at"`
	DisplayName    string      `json:"display_name"`
	AvatarFilePath string      `json:"avatar_file_path"`
}

type MentorixUserLinkCode struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Code       string             `json:"code"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type MentorixUserRole struct {
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
}
