// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: program.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPrograms = `-- name: CountPrograms :one
SELECT COUNT(*)::int AS total
FROM mentorix.programs
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR created_by = $1)
  AND ($2::text IS NULL OR name ILIKE $2 ESCAPE '\')
  AND ($3::text[] IS NULL OR status = ANY($3))
  AND ($4::text IS NULL OR category = $4)
  AND ($5::text IS NULL OR difficulty = $5)
`

type CountProgramsParams struct {
	FilterCreatedBy  pgtype.UUID `json:"filter_created_by"`
	QPattern         *string     `json:"q_pattern"`
	FilterStatuses   []string    `json:"filter_statuses"`
	FilterCategory   *string     `json:"filter_category"`
	FilterDifficulty *string     `json:"filter_difficulty"`
}

func (q *Queries) CountPrograms(ctx context.Context, arg CountProgramsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPrograms,
		arg.FilterCreatedBy,
		arg.QPattern,
		arg.FilterStatuses,
		arg.FilterCategory,
		arg.FilterDifficulty,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const dayBelongsToProgram = `-- name: DayBelongsToProgram :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.program_days
  WHERE id = $1 AND program_id = $2
) AS ok
`

type DayBelongsToProgramParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) DayBelongsToProgram(ctx context.Context, arg DayBelongsToProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, dayBelongsToProgram, arg.ID, arg.ProgramID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const deleteDayExercise = `-- name: DeleteDayExercise :execrows
DELETE FROM mentorix.program_day_exercises
WHERE id = $1 AND program_day_id = $2
`

type DeleteDayExerciseParams struct {
	ID           pgtype.UUID `json:"id"`
	ProgramDayID pgtype.UUID `json:"program_day_id"`
}

func (q *Queries) DeleteDayExercise(ctx context.Context, arg DeleteDayExerciseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDayExercise, arg.ID, arg.ProgramDayID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgramDay = `-- name: DeleteProgramDay :execrows
DELETE FROM mentorix.program_days
WHERE id = $1 AND program_id = $2
`

type DeleteProgramDayParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) DeleteProgramDay(ctx context.Context, arg DeleteProgramDayParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramDay, arg.ID, arg.ProgramID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exerciseExists = `-- name: ExerciseExists :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.exercises WHERE id = $1
) AS ok
`

func (q *Queries) ExerciseExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, exerciseExists, id)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT
  id, created_by, modified_by, status, name, description, category, difficulty,
  preview_image_url, created_at, modified_at, deleted_at
FROM mentorix.programs
WHERE id = $1
`

func (q *Queries) GetProgramByID(ctx context.Context, id pgtype.UUID) (MentorixProgram, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i MentorixProgram
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.PreviewImageUrl,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertDayExercise = `-- name: InsertDayExercise :exec
INSERT INTO mentorix.program_day_exercises (
  program_day_id, exercise_id, sort_order, sets, reps, weight_kg, instruction
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertDayExerciseParams struct {
	ProgramDayID pgtype.UUID    `json:"program_day_id"`
	ExerciseID   pgtype.UUID    `json:"exercise_id"`
	SortOrder    int32          `json:"sort_order"`
	Sets         *int32         `json:"sets"`
	Reps         *int32         `json:"reps"`
	WeightKg     pgtype.Numeric `json:"weight_kg"`
	Instruction  string         `json:"instruction"`
}

func (q *Queries) InsertDayExercise(ctx context.Context, arg InsertDayExerciseParams) error {
	_, err := q.db.Exec(ctx, insertDayExercise,
		arg.ProgramDayID,
		arg.ExerciseID,
		arg.SortOrder,
		arg.Sets,
		arg.Reps,
		arg.WeightKg,
		arg.Instruction,
	)
	return err
}

const insertProgramDay = `-- name: InsertProgramDay :one
INSERT INTO mentorix.program_days (program_id, day_number, sort_order)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertProgramDayParams struct {
	ProgramID pgtype.UUID `json:"program_id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProgramDay(ctx context.Context, arg InsertProgramDayParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProgramDay, arg.ProgramID, arg.DayNumber, arg.SortOrder)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProgramDayAuto = `-- name: InsertProgramDayAuto :exec
INSERT INTO mentorix.program_days (program_id, day_number, sort_order)
VALUES ($1, $2, $3)
`

type InsertProgramDayAutoParams struct {
	ProgramID pgtype.UUID `json:"program_id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProgramDayAuto(ctx context.Context, arg InsertProgramDayAutoParams) error {
	_, err := q.db.Exec(ctx, insertProgramDayAuto, arg.ProgramID, arg.DayNumber, arg.SortOrder)
	return err
}

const insertProgramDraft = `-- name: InsertProgramDraft :one
INSERT INTO mentorix.programs (created_by, modified_by, status, modified_at)
VALUES ($1, $1, $2, $3)
RETURNING id
`

type InsertProgramDraftParams struct {
	CreatedBy  pgtype.UUID `json:"created_by"`
	Status     string      `json:"status"`
	ModifiedAt time.Time   `json:"modified_at"`
}

func (q *Queries) InsertProgramDraft(ctx context.Context, arg InsertProgramDraftParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProgramDraft, arg.CreatedBy, arg.Status, arg.ModifiedAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listDayExercises = `-- name: ListDayExercises :many
SELECT
  pde.id,
  pde.exercise_id,
  e.name,
  e.name_ru,
  pde.sort_order,
  pde.sets,
  pde.reps,
  pde.weight_kg,
  pde.instruction,
  pde.created_at
FROM mentorix.program_day_exercises pde
JOIN mentorix.exercises e ON e.id = pde.exercise_id
WHERE pde.program_day_id = $1
ORDER BY pde.sort_order ASC, pde.created_at ASC
`

type ListDayExercisesRow struct {
	ID          pgtype.UUID    `json:"id"`
	ExerciseID  pgtype.UUID    `json:"exercise_id"`
	Name        string         `json:"name"`
	NameRu      string         `json:"name_ru"`
	SortOrder   int32          `json:"sort_order"`
	Sets        *int32         `json:"sets"`
	Reps        *int32         `json:"reps"`
	WeightKg    pgtype.Numeric `json:"weight_kg"`
	Instruction string         `json:"instruction"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) ListDayExercises(ctx context.Context, programDayID pgtype.UUID) ([]ListDayExercisesRow, error) {
	rows, err := q.db.Query(ctx, listDayExercises, programDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDayExercisesRow{}
	for rows.Next() {
		var i ListDayExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.Name,
			&i.NameRu,
			&i.SortOrder,
			&i.Sets,
			&i.Reps,
			&i.WeightKg,
			&i.Instruction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramDays = `-- name: ListProgramDays :many
SELECT id, day_number, sort_order, created_at
FROM mentorix.program_days
WHERE program_id = $1
ORDER BY sort_order ASC, day_number ASC
`

type ListProgramDaysRow struct {
	ID        pgtype.UUID `json:"id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) ListProgramDays(ctx context.Context, programID pgtype.UUID) ([]ListProgramDaysRow, error) {
	rows, err := q.db.Query(ctx, listProgramDays, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramDaysRow{}
	for rows.Next() {
		var i ListProgramDaysRow
		if err := rows.Scan(
			&i.ID,
			&i.DayNumber,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT
  id, created_by, modified_by, status, name, description, category, difficulty,
  preview_image_url, created_at, modified_at, deleted_at
FROM mentorix.programs
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR created_by = $1)
  AND ($2::text IS NULL OR name ILIKE $2 ESCAPE '\')
  AND ($3::text[] IS NULL OR status = ANY($3))
  AND ($4::text IS NULL OR category = $4)
  AND ($5::text IS NULL OR difficulty = $5)
ORDER BY
  CASE WHEN $6 = 'name' AND $7 = 'asc' THEN name END ASC NULLS LAST,
  CASE WHEN $6 = 'name' AND $7 = 'desc' THEN name END DESC NULLS LAST,
  CASE WHEN $6 = 'created_at' AND $7 = 'asc' THEN created_at END ASC NULLS LAST,
  CASE WHEN $6 = 'created_at' AND $7 = 'desc' THEN created_at END DESC NULLS LAST,
  CASE WHEN $6 = 'modified_at' AND $7 = 'asc' THEN modified_at END ASC NULLS LAST,
  CASE WHEN $6 = 'modified_at' AND $7 = 'desc' THEN modified_at END DESC NULLS LAST,
  CASE WHEN $6 = 'status' AND $7 = 'asc' THEN status END ASC NULLS LAST,
  CASE WHEN $6 = 'status' AND $7 = 'desc' THEN status END DESC NULLS LAST,
  CASE WHEN $6 = 'category' AND $7 = 'asc' THEN category END ASC NULLS LAST,
  CASE WHEN $6 = 'category' AND $7 = 'desc' THEN category END DESC NULLS LAST,
  CASE WHEN $6 = 'difficulty' AND $7 = 'asc' THEN difficulty END ASC NULLS LAST,
  CASE WHEN $6 = 'difficulty' AND $7 = 'desc' THEN difficulty END DESC NULLS LAST,
  id ASC
LIMIT $9 OFFSET $8
`

type ListProgramsParams struct {
	FilterCreatedBy  pgtype.UUID `json:"filter_created_by"`
	QPattern         *string     `json:"q_pattern"`
	FilterStatuses   []string    `json:"filter_statuses"`
	FilterCategory   *string     `json:"filter_category"`
	FilterDifficulty *string     `json:"filter_difficulty"`
	SortBy           interface{} `json:"sort_by"`
	SortOrder        interface{} `json:"sort_order"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]MentorixProgram, error) {
	rows, err := q.db.Query(ctx, listPrograms,
		arg.FilterCreatedBy,
		arg.QPattern,
		arg.FilterStatuses,
		arg.FilterCategory,
		arg.FilterDifficulty,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorixProgram{}
	for rows.Next() {
		var i MentorixProgram
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.Status,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Difficulty,
			&i.PreviewImageUrl,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDayExerciseSort = `-- name: NextDayExerciseSort :one
SELECT COALESCE(MAX(sort_order), 0) + 1::int AS next_sort
FROM mentorix.program_day_exercises
WHERE program_day_id = $1
`

func (q *Queries) NextDayExerciseSort(ctx context.Context, programDayID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextDayExerciseSort, programDayID)
	var next_sort int32
	err := row.Scan(&next_sort)
	return next_sort, err
}

const nextProgramDayNumbers = `-- name: NextProgramDayNumbers :one
SELECT
  COALESCE(MAX(day_number), 0) + 1::int AS next_day_number,
  COALESCE(MAX(sort_order), 0) + 1::int AS next_sort_order
FROM mentorix.program_days
WHERE program_id = $1
`

type NextProgramDayNumbersRow struct {
	NextDayNumber int32 `json:"next_day_number"`
	NextSortOrder int32 `json:"next_sort_order"`
}

func (q *Queries) NextProgramDayNumbers(ctx context.Context, programID pgtype.UUID) (NextProgramDayNumbersRow, error) {
	row := q.db.QueryRow(ctx, nextProgramDayNumbers, programID)
	var i NextProgramDayNumbersRow
	err := row.Scan(&i.NextDayNumber, &i.NextSortOrder)
	return i, err
}

const setProgramStatus = `-- name: SetProgramStatus :execrows
UPDATE mentorix.programs SET
  status = $2,
  modified_by = $3,
  modified_at = $4
WHERE id = $1 AND deleted_at IS NULL
`

type SetProgramStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
	ModifiedAt time.Time   `json:"modified_at"`
}

func (q *Queries) SetProgramStatus(ctx context.Context, arg SetProgramStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProgramStatus,
		arg.ID,
		arg.Status,
		arg.ModifiedBy,
		arg.ModifiedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProgram = `-- name: SoftDeleteProgram :execrows
UPDATE mentorix.programs SET
  deleted_at = $2,
  modified_by = $3,
  modified_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteProgramParams struct {
	ID         pgtype.UUID        `json:"id"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ModifiedBy pgtype.UUID        `json:"modified_by"`
}

func (q *Queries) SoftDeleteProgram(ctx context.Context, arg SoftDeleteProgramParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProgram, arg.ID, arg.DeletedAt, arg.ModifiedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDayExercise = `-- name: UpdateDayExercise :execrows
UPDATE mentorix.program_day_exercises SET
  exercise_id = $3,
  sets = $4,
  reps = $5,
  weight_kg = $6,
  instruction = $7
WHERE id = $1 AND program_day_id = $2
`

type UpdateDayExerciseParams struct {
	ID           pgtype.UUID    `json:"id"`
	ProgramDayID pgtype.UUID    `json:"program_day_id"`
	ExerciseID   pgtype.UUID    `json:"exercise_id"`
	Sets         *int32         `json:"sets"`
	Reps         *int32         `json:"reps"`
	WeightKg     pgtype.Numeric `json:"weight_kg"`
	Instruction  string         `json:"instruction"`
}

func (q *Queries) UpdateDayExercise(ctx context.Context, arg UpdateDayExerciseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDayExercise,
		arg.ID,
		arg.ProgramDayID,
		arg.ExerciseID,
		arg.Sets,
		arg.Reps,
		arg.WeightKg,
		arg.Instruction,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProgram = `-- name: UpdateProgram :execrows
UPDATE mentorix.programs SET
  modified_by = $1,
  modified_at = $2,
  name = COALESCE($3, name),
  description = COALESCE($4, description),
  category = COALESCE($5, category),
  difficulty = COALESCE($6, difficulty),
  preview_image_url = COALESCE($7, preview_image_url)
WHERE id = $8 AND deleted_at IS NULL
`

type UpdateProgramParams struct {
	ModifiedBy      pgtype.UUID `json:"modified_by"`
	ModifiedAt      time.Time   `json:"modified_at"`
	Name            *string     `json:"name"`
	Description     *string     `json:"description"`
	Category        *string     `json:"category"`
	Difficulty      *string     `json:"difficulty"`
	PreviewImageUrl *string     `json:"preview_image_url"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProgram,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Difficulty,
		arg.PreviewImageUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
