// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: program.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProgramDaysForWeek = `-- name: CountProgramDaysForWeek :one
SELECT COUNT(*)::int AS count
FROM mentorix.program_days
WHERE week_id = $1
`

func (q *Queries) CountProgramDaysForWeek(ctx context.Context, weekID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProgramDaysForWeek, weekID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countProgramWeeks = `-- name: CountProgramWeeks :one
SELECT COUNT(*)::int AS count
FROM mentorix.program_weeks
WHERE program_id = $1
`

func (q *Queries) CountProgramWeeks(ctx context.Context, programID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProgramWeeks, programID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countPrograms = `-- name: CountPrograms :one
SELECT COUNT(*)::int AS total
FROM mentorix.programs
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR created_by = $1)
  AND (
    $2::text IS NULL
    OR name ILIKE $2 ESCAPE '\'
    OR name_ru ILIKE $2 ESCAPE '\'
  )
  AND ($3::text[] IS NULL OR status = ANY($3))
  AND ($4::text IS NULL OR category = $4)
  AND ($5::text IS NULL OR difficulty = $5)
`

type CountProgramsParams struct {
	FilterCreatedBy  pgtype.UUID `json:"filter_created_by"`
	QPattern         *string     `json:"q_pattern"`
	FilterStatuses   []string    `json:"filter_statuses"`
	FilterCategory   *string     `json:"filter_category"`
	FilterDifficulty *string     `json:"filter_difficulty"`
}

func (q *Queries) CountPrograms(ctx context.Context, arg CountProgramsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPrograms,
		arg.FilterCreatedBy,
		arg.QPattern,
		arg.FilterStatuses,
		arg.FilterCategory,
		arg.FilterDifficulty,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const dayBelongsToProgram = `-- name: DayBelongsToProgram :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.program_days
  WHERE id = $1 AND program_id = $2
) AS ok
`

type DayBelongsToProgramParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) DayBelongsToProgram(ctx context.Context, arg DayBelongsToProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, dayBelongsToProgram, arg.ID, arg.ProgramID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const dayBelongsToWeek = `-- name: DayBelongsToWeek :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.program_days
  WHERE id = $1 AND week_id = $2 AND program_id = $3
) AS ok
`

type DayBelongsToWeekParams struct {
	ID        pgtype.UUID `json:"id"`
	WeekID    pgtype.UUID `json:"week_id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) DayBelongsToWeek(ctx context.Context, arg DayBelongsToWeekParams) (bool, error) {
	row := q.db.QueryRow(ctx, dayBelongsToWeek, arg.ID, arg.WeekID, arg.ProgramID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const deleteDayExercise = `-- name: DeleteDayExercise :execrows
DELETE FROM mentorix.program_day_exercises
WHERE id = $1 AND program_day_id = $2
`

type DeleteDayExerciseParams struct {
	ID           pgtype.UUID `json:"id"`
	ProgramDayID pgtype.UUID `json:"program_day_id"`
}

func (q *Queries) DeleteDayExercise(ctx context.Context, arg DeleteDayExerciseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDayExercise, arg.ID, arg.ProgramDayID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgramDay = `-- name: DeleteProgramDay :execrows
DELETE FROM mentorix.program_days
WHERE id = $1 AND program_id = $2 AND week_id = $3
`

type DeleteProgramDayParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
	WeekID    pgtype.UUID `json:"week_id"`
}

func (q *Queries) DeleteProgramDay(ctx context.Context, arg DeleteProgramDayParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramDay, arg.ID, arg.ProgramID, arg.WeekID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgramWeek = `-- name: DeleteProgramWeek :execrows
DELETE FROM mentorix.program_weeks
WHERE id = $1 AND program_id = $2
`

type DeleteProgramWeekParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) DeleteProgramWeek(ctx context.Context, arg DeleteProgramWeekParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramWeek, arg.ID, arg.ProgramID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exerciseExists = `-- name: ExerciseExists :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.exercises WHERE id = $1 AND deleted_at IS NULL
) AS ok
`

func (q *Queries) ExerciseExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, exerciseExists, id)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT
  p.id, p.created_by, p.modified_by, p.status, p.name, p.name_ru, p.description, p.description_ru,
  p.category, p.difficulty, p.preview_image_url, p.created_at, p.modified_at, p.deleted_at,
  COALESCE(u.display_name, '') AS created_by_name
FROM mentorix.programs p
JOIN mentorix.users u ON u.id = p.created_by
WHERE p.id = $1
`

type GetProgramByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	Status          string             `json:"status"`
	Name            string             `json:"name"`
	NameRu          string             `json:"name_ru"`
	Description     string             `json:"description"`
	DescriptionRu   string             `json:"description_ru"`
	Category        *string            `json:"category"`
	Difficulty      *string            `json:"difficulty"`
	PreviewImageUrl string             `json:"preview_image_url"`
	CreatedAt       time.Time          `json:"created_at"`
	ModifiedAt      time.Time          `json:"modified_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedByName   string             `json:"created_by_name"`
}

func (q *Queries) GetProgramByID(ctx context.Context, id pgtype.UUID) (GetProgramByIDRow, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i GetProgramByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.Status,
		&i.Name,
		&i.NameRu,
		&i.Description,
		&i.DescriptionRu,
		&i.Category,
		&i.Difficulty,
		&i.PreviewImageUrl,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.CreatedByName,
	)
	return i, err
}

const insertDayExercise = `-- name: InsertDayExercise :exec
INSERT INTO mentorix.program_day_exercises (
  program_day_id, exercise_id, sort_order, sets, reps, weight_kg, instruction,
  modified_at, modified_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertDayExerciseParams struct {
	ProgramDayID pgtype.UUID    `json:"program_day_id"`
	ExerciseID   pgtype.UUID    `json:"exercise_id"`
	SortOrder    int32          `json:"sort_order"`
	Sets         *int32         `json:"sets"`
	Reps         *int32         `json:"reps"`
	WeightKg     pgtype.Numeric `json:"weight_kg"`
	Instruction  string         `json:"instruction"`
	ModifiedAt   time.Time      `json:"modified_at"`
	ModifiedBy   pgtype.UUID    `json:"modified_by"`
}

func (q *Queries) InsertDayExercise(ctx context.Context, arg InsertDayExerciseParams) error {
	_, err := q.db.Exec(ctx, insertDayExercise,
		arg.ProgramDayID,
		arg.ExerciseID,
		arg.SortOrder,
		arg.Sets,
		arg.Reps,
		arg.WeightKg,
		arg.Instruction,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	return err
}

const insertProgramDay = `-- name: InsertProgramDay :one
INSERT INTO mentorix.program_days (program_id, week_id, day_number, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertProgramDayParams struct {
	ProgramID pgtype.UUID `json:"program_id"`
	WeekID    pgtype.UUID `json:"week_id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProgramDay(ctx context.Context, arg InsertProgramDayParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProgramDay,
		arg.ProgramID,
		arg.WeekID,
		arg.DayNumber,
		arg.SortOrder,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProgramDayAuto = `-- name: InsertProgramDayAuto :exec
INSERT INTO mentorix.program_days (program_id, week_id, day_number, sort_order)
VALUES ($1, $2, $3, $4)
`

type InsertProgramDayAutoParams struct {
	ProgramID pgtype.UUID `json:"program_id"`
	WeekID    pgtype.UUID `json:"week_id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProgramDayAuto(ctx context.Context, arg InsertProgramDayAutoParams) error {
	_, err := q.db.Exec(ctx, insertProgramDayAuto,
		arg.ProgramID,
		arg.WeekID,
		arg.DayNumber,
		arg.SortOrder,
	)
	return err
}

const insertProgramDraft = `-- name: InsertProgramDraft :one
INSERT INTO mentorix.programs (created_by, modified_by, status, modified_at)
VALUES ($1, $1, $2, $3)
RETURNING id
`

type InsertProgramDraftParams struct {
	CreatedBy  pgtype.UUID `json:"created_by"`
	Status     string      `json:"status"`
	ModifiedAt time.Time   `json:"modified_at"`
}

func (q *Queries) InsertProgramDraft(ctx context.Context, arg InsertProgramDraftParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProgramDraft, arg.CreatedBy, arg.Status, arg.ModifiedAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProgramWeek = `-- name: InsertProgramWeek :one
INSERT INTO mentorix.program_weeks (program_id, week_number, sort_order, modified_at, modified_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertProgramWeekParams struct {
	ProgramID  pgtype.UUID `json:"program_id"`
	WeekNumber int32       `json:"week_number"`
	SortOrder  int32       `json:"sort_order"`
	ModifiedAt time.Time   `json:"modified_at"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
}

func (q *Queries) InsertProgramWeek(ctx context.Context, arg InsertProgramWeekParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProgramWeek,
		arg.ProgramID,
		arg.WeekNumber,
		arg.SortOrder,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listDayExercises = `-- name: ListDayExercises :many
SELECT
  pde.id,
  pde.exercise_id,
  e.name,
  e.name_ru,
  pde.sort_order,
  pde.sets,
  pde.reps,
  pde.weight_kg,
  pde.instruction,
  pde.created_at
FROM mentorix.program_day_exercises pde
JOIN mentorix.exercises e ON e.id = pde.exercise_id
WHERE pde.program_day_id = $1
ORDER BY pde.sort_order ASC, pde.created_at ASC
`

type ListDayExercisesRow struct {
	ID          pgtype.UUID    `json:"id"`
	ExerciseID  pgtype.UUID    `json:"exercise_id"`
	Name        string         `json:"name"`
	NameRu      string         `json:"name_ru"`
	SortOrder   int32          `json:"sort_order"`
	Sets        *int32         `json:"sets"`
	Reps        *int32         `json:"reps"`
	WeightKg    pgtype.Numeric `json:"weight_kg"`
	Instruction string         `json:"instruction"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) ListDayExercises(ctx context.Context, programDayID pgtype.UUID) ([]ListDayExercisesRow, error) {
	rows, err := q.db.Query(ctx, listDayExercises, programDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDayExercisesRow{}
	for rows.Next() {
		var i ListDayExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.Name,
			&i.NameRu,
			&i.SortOrder,
			&i.Sets,
			&i.Reps,
			&i.WeightKg,
			&i.Instruction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseItemsByWeek = `-- name: ListExerciseItemsByWeek :many
SELECT pde.id, pde.program_day_id
FROM mentorix.program_day_exercises pde
JOIN mentorix.program_days pd ON pd.id = pde.program_day_id
WHERE pd.week_id = $1
`

type ListExerciseItemsByWeekRow struct {
	ID           pgtype.UUID `json:"id"`
	ProgramDayID pgtype.UUID `json:"program_day_id"`
}

func (q *Queries) ListExerciseItemsByWeek(ctx context.Context, weekID pgtype.UUID) ([]ListExerciseItemsByWeekRow, error) {
	rows, err := q.db.Query(ctx, listExerciseItemsByWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExerciseItemsByWeekRow{}
	for rows.Next() {
		var i ListExerciseItemsByWeekRow
		if err := rows.Scan(&i.ID, &i.ProgramDayID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramDayIDsForWeek = `-- name: ListProgramDayIDsForWeek :many
SELECT id
FROM mentorix.program_days
WHERE week_id = $1
ORDER BY sort_order ASC, day_number ASC
`

func (q *Queries) ListProgramDayIDsForWeek(ctx context.Context, weekID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listProgramDayIDsForWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramDaysForWeek = `-- name: ListProgramDaysForWeek :many
SELECT id, day_number, sort_order, created_at
FROM mentorix.program_days
WHERE week_id = $1
ORDER BY sort_order ASC, day_number ASC
`

type ListProgramDaysForWeekRow struct {
	ID        pgtype.UUID `json:"id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) ListProgramDaysForWeek(ctx context.Context, weekID pgtype.UUID) ([]ListProgramDaysForWeekRow, error) {
	rows, err := q.db.Query(ctx, listProgramDaysForWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramDaysForWeekRow{}
	for rows.Next() {
		var i ListProgramDaysForWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.DayNumber,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramWeekIDs = `-- name: ListProgramWeekIDs :many
SELECT id
FROM mentorix.program_weeks
WHERE program_id = $1
ORDER BY sort_order ASC, week_number ASC
`

func (q *Queries) ListProgramWeekIDs(ctx context.Context, programID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listProgramWeekIDs, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramWeeks = `-- name: ListProgramWeeks :many
SELECT id, week_number, sort_order, created_at
FROM mentorix.program_weeks
WHERE program_id = $1
ORDER BY sort_order ASC, week_number ASC
`

type ListProgramWeeksRow struct {
	ID         pgtype.UUID `json:"id"`
	WeekNumber int32       `json:"week_number"`
	SortOrder  int32       `json:"sort_order"`
	CreatedAt  time.Time   `json:"created_at"`
}

func (q *Queries) ListProgramWeeks(ctx context.Context, programID pgtype.UUID) ([]ListProgramWeeksRow, error) {
	rows, err := q.db.Query(ctx, listProgramWeeks, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramWeeksRow{}
	for rows.Next() {
		var i ListProgramWeeksRow
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT
  p.id, p.created_by, p.modified_by, p.status, p.name, p.name_ru, p.description, p.description_ru,
  p.category, p.difficulty, p.preview_image_url, p.created_at, p.modified_at, p.deleted_at,
  COALESCE(u.display_name, '') AS created_by_name
FROM mentorix.programs p
JOIN mentorix.users u ON u.id = p.created_by
WHERE p.deleted_at IS NULL
  AND ($1::uuid IS NULL OR p.created_by = $1)
  AND (
    $2::text IS NULL
    OR p.name ILIKE $2 ESCAPE '\'
    OR p.name_ru ILIKE $2 ESCAPE '\'
  )
  AND ($3::text[] IS NULL OR p.status = ANY($3))
  AND ($4::text IS NULL OR p.category = $4)
  AND ($5::text IS NULL OR p.difficulty = $5)
ORDER BY
  CASE WHEN $6 = 'name' AND $7 = 'asc' THEN p.name END ASC NULLS LAST,
  CASE WHEN $6 = 'name' AND $7 = 'desc' THEN p.name END DESC NULLS LAST,
  CASE WHEN $6 = 'name_ru' AND $7 = 'asc' THEN p.name_ru END ASC NULLS LAST,
  CASE WHEN $6 = 'name_ru' AND $7 = 'desc' THEN p.name_ru END DESC NULLS LAST,
  CASE WHEN $6 = 'created_at' AND $7 = 'asc' THEN p.created_at END ASC NULLS LAST,
  CASE WHEN $6 = 'created_at' AND $7 = 'desc' THEN p.created_at END DESC NULLS LAST,
  CASE WHEN $6 = 'modified_at' AND $7 = 'asc' THEN p.modified_at END ASC NULLS LAST,
  CASE WHEN $6 = 'modified_at' AND $7 = 'desc' THEN p.modified_at END DESC NULLS LAST,
  CASE WHEN $6 = 'status' AND $7 = 'asc' THEN p.status END ASC NULLS LAST,
  CASE WHEN $6 = 'status' AND $7 = 'desc' THEN p.status END DESC NULLS LAST,
  CASE WHEN $6 = 'category' AND $7 = 'asc' THEN p.category END ASC NULLS LAST,
  CASE WHEN $6 = 'category' AND $7 = 'desc' THEN p.category END DESC NULLS LAST,
  CASE WHEN $6 = 'difficulty' AND $7 = 'asc' THEN p.difficulty END ASC NULLS LAST,
  CASE WHEN $6 = 'difficulty' AND $7 = 'desc' THEN p.difficulty END DESC NULLS LAST,
  p.id ASC
LIMIT $9 OFFSET $8
`

type ListProgramsParams struct {
	FilterCreatedBy  pgtype.UUID `json:"filter_created_by"`
	QPattern         *string     `json:"q_pattern"`
	FilterStatuses   []string    `json:"filter_statuses"`
	FilterCategory   *string     `json:"filter_category"`
	FilterDifficulty *string     `json:"filter_difficulty"`
	SortBy           interface{} `json:"sort_by"`
	SortOrder        interface{} `json:"sort_order"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

type ListProgramsRow struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	Status          string             `json:"status"`
	Name            string             `json:"name"`
	NameRu          string             `json:"name_ru"`
	Description     string             `json:"description"`
	DescriptionRu   string             `json:"description_ru"`
	Category        *string            `json:"category"`
	Difficulty      *string            `json:"difficulty"`
	PreviewImageUrl string             `json:"preview_image_url"`
	CreatedAt       time.Time          `json:"created_at"`
	ModifiedAt      time.Time          `json:"modified_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedByName   string             `json:"created_by_name"`
}

func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]ListProgramsRow, error) {
	rows, err := q.db.Query(ctx, listPrograms,
		arg.FilterCreatedBy,
		arg.QPattern,
		arg.FilterStatuses,
		arg.FilterCategory,
		arg.FilterDifficulty,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsRow{}
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.Status,
			&i.Name,
			&i.NameRu,
			&i.Description,
			&i.DescriptionRu,
			&i.Category,
			&i.Difficulty,
			&i.PreviewImageUrl,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDayExerciseSort = `-- name: NextDayExerciseSort :one
SELECT COALESCE(MAX(sort_order), 0) + 1::int AS next_sort
FROM mentorix.program_day_exercises
WHERE program_day_id = $1
`

func (q *Queries) NextDayExerciseSort(ctx context.Context, programDayID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextDayExerciseSort, programDayID)
	var next_sort int32
	err := row.Scan(&next_sort)
	return next_sort, err
}

const nextProgramDayNumbersForWeek = `-- name: NextProgramDayNumbersForWeek :one
SELECT
  COALESCE(MAX(day_number), 0) + 1::int AS next_day_number,
  COALESCE(MAX(sort_order), 0) + 1::int AS next_sort_order
FROM mentorix.program_days
WHERE week_id = $1
`

type NextProgramDayNumbersForWeekRow struct {
	NextDayNumber int32 `json:"next_day_number"`
	NextSortOrder int32 `json:"next_sort_order"`
}

func (q *Queries) NextProgramDayNumbersForWeek(ctx context.Context, weekID pgtype.UUID) (NextProgramDayNumbersForWeekRow, error) {
	row := q.db.QueryRow(ctx, nextProgramDayNumbersForWeek, weekID)
	var i NextProgramDayNumbersForWeekRow
	err := row.Scan(&i.NextDayNumber, &i.NextSortOrder)
	return i, err
}

const nextProgramWeekNumbers = `-- name: NextProgramWeekNumbers :one
SELECT
  COALESCE(MAX(week_number), 0) + 1::int AS next_week_number,
  COALESCE(MAX(sort_order), 0) + 1::int AS next_sort_order
FROM mentorix.program_weeks
WHERE program_id = $1
`

type NextProgramWeekNumbersRow struct {
	NextWeekNumber int32 `json:"next_week_number"`
	NextSortOrder  int32 `json:"next_sort_order"`
}

func (q *Queries) NextProgramWeekNumbers(ctx context.Context, programID pgtype.UUID) (NextProgramWeekNumbersRow, error) {
	row := q.db.QueryRow(ctx, nextProgramWeekNumbers, programID)
	var i NextProgramWeekNumbersRow
	err := row.Scan(&i.NextWeekNumber, &i.NextSortOrder)
	return i, err
}

const setProgramStatus = `-- name: SetProgramStatus :execrows
UPDATE mentorix.programs SET
  status = $2,
  modified_by = $3,
  modified_at = $4
WHERE id = $1 AND deleted_at IS NULL
`

type SetProgramStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
	ModifiedAt time.Time   `json:"modified_at"`
}

func (q *Queries) SetProgramStatus(ctx context.Context, arg SetProgramStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProgramStatus,
		arg.ID,
		arg.Status,
		arg.ModifiedBy,
		arg.ModifiedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProgram = `-- name: SoftDeleteProgram :execrows
UPDATE mentorix.programs SET
  deleted_at = $2,
  modified_by = $3,
  modified_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteProgramParams struct {
	ID         pgtype.UUID        `json:"id"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ModifiedBy pgtype.UUID        `json:"modified_by"`
}

func (q *Queries) SoftDeleteProgram(ctx context.Context, arg SoftDeleteProgramParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProgram, arg.ID, arg.DeletedAt, arg.ModifiedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDayExercise = `-- name: UpdateDayExercise :execrows
UPDATE mentorix.program_day_exercises SET
  exercise_id = $3,
  sets = $4,
  reps = $5,
  weight_kg = $6,
  instruction = $7,
  modified_at = $8,
  modified_by = $9
WHERE id = $1 AND program_day_id = $2
`

type UpdateDayExerciseParams struct {
	ID           pgtype.UUID    `json:"id"`
	ProgramDayID pgtype.UUID    `json:"program_day_id"`
	ExerciseID   pgtype.UUID    `json:"exercise_id"`
	Sets         *int32         `json:"sets"`
	Reps         *int32         `json:"reps"`
	WeightKg     pgtype.Numeric `json:"weight_kg"`
	Instruction  string         `json:"instruction"`
	ModifiedAt   time.Time      `json:"modified_at"`
	ModifiedBy   pgtype.UUID    `json:"modified_by"`
}

func (q *Queries) UpdateDayExercise(ctx context.Context, arg UpdateDayExerciseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDayExercise,
		arg.ID,
		arg.ProgramDayID,
		arg.ExerciseID,
		arg.Sets,
		arg.Reps,
		arg.WeightKg,
		arg.Instruction,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDayExercisePlacement = `-- name: UpdateDayExercisePlacement :exec
UPDATE mentorix.program_day_exercises SET
  program_day_id = $2,
  sort_order = $3,
  modified_at = $4,
  modified_by = $5
WHERE id = $1
`

type UpdateDayExercisePlacementParams struct {
	ID           pgtype.UUID `json:"id"`
	ProgramDayID pgtype.UUID `json:"program_day_id"`
	SortOrder    int32       `json:"sort_order"`
	ModifiedAt   time.Time   `json:"modified_at"`
	ModifiedBy   pgtype.UUID `json:"modified_by"`
}

func (q *Queries) UpdateDayExercisePlacement(ctx context.Context, arg UpdateDayExercisePlacementParams) error {
	_, err := q.db.Exec(ctx, updateDayExercisePlacement,
		arg.ID,
		arg.ProgramDayID,
		arg.SortOrder,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	return err
}

const updateProgram = `-- name: UpdateProgram :execrows
UPDATE mentorix.programs SET
  modified_by = $1,
  modified_at = $2,
  name = COALESCE($3, name),
  name_ru = COALESCE($4, name_ru),
  description = COALESCE($5, description),
  description_ru = COALESCE($6, description_ru),
  category = COALESCE($7, category),
  difficulty = COALESCE($8, difficulty),
  preview_image_url = COALESCE($9, preview_image_url)
WHERE id = $10 AND deleted_at IS NULL
`

type UpdateProgramParams struct {
	ModifiedBy      pgtype.UUID `json:"modified_by"`
	ModifiedAt      time.Time   `json:"modified_at"`
	Name            *string     `json:"name"`
	NameRu          *string     `json:"name_ru"`
	Description     *string     `json:"description"`
	DescriptionRu   *string     `json:"description_ru"`
	Category        *string     `json:"category"`
	Difficulty      *string     `json:"difficulty"`
	PreviewImageUrl *string     `json:"preview_image_url"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProgram,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.NameRu,
		arg.Description,
		arg.DescriptionRu,
		arg.Category,
		arg.Difficulty,
		arg.PreviewImageUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProgramDayOrder = `-- name: UpdateProgramDayOrder :exec
UPDATE mentorix.program_days SET
  sort_order = $3,
  day_number = $4
WHERE id = $1 AND week_id = $2
`

type UpdateProgramDayOrderParams struct {
	ID        pgtype.UUID `json:"id"`
	WeekID    pgtype.UUID `json:"week_id"`
	SortOrder int32       `json:"sort_order"`
	DayNumber int32       `json:"day_number"`
}

func (q *Queries) UpdateProgramDayOrder(ctx context.Context, arg UpdateProgramDayOrderParams) error {
	_, err := q.db.Exec(ctx, updateProgramDayOrder,
		arg.ID,
		arg.WeekID,
		arg.SortOrder,
		arg.DayNumber,
	)
	return err
}

const updateProgramWeekOrder = `-- name: UpdateProgramWeekOrder :exec
UPDATE mentorix.program_weeks SET
  sort_order = $3,
  week_number = $4
WHERE id = $1 AND program_id = $2
`

type UpdateProgramWeekOrderParams struct {
	ID         pgtype.UUID `json:"id"`
	ProgramID  pgtype.UUID `json:"program_id"`
	SortOrder  int32       `json:"sort_order"`
	WeekNumber int32       `json:"week_number"`
}

func (q *Queries) UpdateProgramWeekOrder(ctx context.Context, arg UpdateProgramWeekOrderParams) error {
	_, err := q.db.Exec(ctx, updateProgramWeekOrder,
		arg.ID,
		arg.ProgramID,
		arg.SortOrder,
		arg.WeekNumber,
	)
	return err
}

const weekBelongsToProgram = `-- name: WeekBelongsToProgram :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.program_weeks
  WHERE id = $1 AND program_id = $2
) AS ok
`

type WeekBelongsToProgramParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) WeekBelongsToProgram(ctx context.Context, arg WeekBelongsToProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, weekBelongsToProgram, arg.ID, arg.ProgramID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}
