// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: program_assignment.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveProgramAssignmentsByProgramID = `-- name: CountActiveProgramAssignmentsByProgramID :one
SELECT COUNT(*)::int AS total
FROM mentorix.program_assignments
WHERE program_id = $1
  AND status = 'active'
`

func (q *Queries) CountActiveProgramAssignmentsByProgramID(ctx context.Context, programID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveProgramAssignmentsByProgramID, programID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countActiveProgramAssignmentsByVersionID = `-- name: CountActiveProgramAssignmentsByVersionID :one
SELECT COUNT(*)::int AS total
FROM mentorix.program_assignments
WHERE program_version_id = $1
  AND status = 'active'
`

func (q *Queries) CountActiveProgramAssignmentsByVersionID(ctx context.Context, programVersionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveProgramAssignmentsByVersionID, programVersionID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const deleteProgramAssignmentByTrainerClient = `-- name: DeleteProgramAssignmentByTrainerClient :execrows
DELETE FROM mentorix.program_assignments
WHERE trainer_id = $1
  AND client_user_id = $2
`

type DeleteProgramAssignmentByTrainerClientParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

func (q *Queries) DeleteProgramAssignmentByTrainerClient(ctx context.Context, arg DeleteProgramAssignmentByTrainerClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramAssignmentByTrainerClient, arg.TrainerID, arg.ClientUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgramAssignmentsByProgramID = `-- name: DeleteProgramAssignmentsByProgramID :execrows
DELETE FROM mentorix.program_assignments
WHERE program_id = $1
`

func (q *Queries) DeleteProgramAssignmentsByProgramID(ctx context.Context, programID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramAssignmentsByProgramID, programID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveProgramAssignmentByTrainerClient = `-- name: GetActiveProgramAssignmentByTrainerClient :one
SELECT id, program_id, program_version_id, trainer_id, client_user_id, status, assigned_at, created_at, modified_at, created_by, modified_by, completion_cycle_id
FROM mentorix.program_assignments
WHERE trainer_id = $1
  AND client_user_id = $2
  AND status = 'active'
`

type GetActiveProgramAssignmentByTrainerClientParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

func (q *Queries) GetActiveProgramAssignmentByTrainerClient(ctx context.Context, arg GetActiveProgramAssignmentByTrainerClientParams) (MentorixProgramAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveProgramAssignmentByTrainerClient, arg.TrainerID, arg.ClientUserID)
	var i MentorixProgramAssignment
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ProgramVersionID,
		&i.TrainerID,
		&i.ClientUserID,
		&i.Status,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.CompletionCycleID,
	)
	return i, err
}

const getProgramAssignmentByID = `-- name: GetProgramAssignmentByID :one
SELECT id, program_id, program_version_id, trainer_id, client_user_id, status, assigned_at, created_at, modified_at, created_by, modified_by, completion_cycle_id
FROM mentorix.program_assignments
WHERE id = $1
`

func (q *Queries) GetProgramAssignmentByID(ctx context.Context, id pgtype.UUID) (MentorixProgramAssignment, error) {
	row := q.db.QueryRow(ctx, getProgramAssignmentByID, id)
	var i MentorixProgramAssignment
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ProgramVersionID,
		&i.TrainerID,
		&i.ClientUserID,
		&i.Status,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.CompletionCycleID,
	)
	return i, err
}

const getProgramAssignmentByTrainerClient = `-- name: GetProgramAssignmentByTrainerClient :one
SELECT id, program_id, program_version_id, trainer_id, client_user_id, status, assigned_at, created_at, modified_at, created_by, modified_by, completion_cycle_id
FROM mentorix.program_assignments
WHERE trainer_id = $1
  AND client_user_id = $2
`

type GetProgramAssignmentByTrainerClientParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

func (q *Queries) GetProgramAssignmentByTrainerClient(ctx context.Context, arg GetProgramAssignmentByTrainerClientParams) (MentorixProgramAssignment, error) {
	row := q.db.QueryRow(ctx, getProgramAssignmentByTrainerClient, arg.TrainerID, arg.ClientUserID)
	var i MentorixProgramAssignment
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ProgramVersionID,
		&i.TrainerID,
		&i.ClientUserID,
		&i.Status,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.CompletionCycleID,
	)
	return i, err
}

const getTrainerIDByUserID = `-- name: GetTrainerIDByUserID :one
SELECT id
FROM mentorix.trainers
WHERE user_id = $1
`

func (q *Queries) GetTrainerIDByUserID(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTrainerIDByUserID, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProgramAssignment = `-- name: InsertProgramAssignment :one
INSERT INTO mentorix.program_assignments (
  program_id,
  program_version_id,
  trainer_id,
  client_user_id,
  status,
  assigned_at,
  created_by,
  modified_at,
  modified_by,
  completion_cycle_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, program_id, program_version_id, trainer_id, client_user_id, status, assigned_at, created_at, modified_at, created_by, modified_by, completion_cycle_id
`

type InsertProgramAssignmentParams struct {
	ProgramID         pgtype.UUID `json:"program_id"`
	ProgramVersionID  pgtype.UUID `json:"program_version_id"`
	TrainerID         pgtype.UUID `json:"trainer_id"`
	ClientUserID      pgtype.UUID `json:"client_user_id"`
	Status            string      `json:"status"`
	AssignedAt        time.Time   `json:"assigned_at"`
	CreatedBy         pgtype.UUID `json:"created_by"`
	ModifiedAt        time.Time   `json:"modified_at"`
	ModifiedBy        pgtype.UUID `json:"modified_by"`
	CompletionCycleID pgtype.UUID `json:"completion_cycle_id"`
}

func (q *Queries) InsertProgramAssignment(ctx context.Context, arg InsertProgramAssignmentParams) (MentorixProgramAssignment, error) {
	row := q.db.QueryRow(ctx, insertProgramAssignment,
		arg.ProgramID,
		arg.ProgramVersionID,
		arg.TrainerID,
		arg.ClientUserID,
		arg.Status,
		arg.AssignedAt,
		arg.CreatedBy,
		arg.ModifiedAt,
		arg.ModifiedBy,
		arg.CompletionCycleID,
	)
	var i MentorixProgramAssignment
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ProgramVersionID,
		&i.TrainerID,
		&i.ClientUserID,
		&i.Status,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.CompletionCycleID,
	)
	return i, err
}

const listActiveProgramAssignmentsByProgramID = `-- name: ListActiveProgramAssignmentsByProgramID :many
SELECT id, program_id, program_version_id, trainer_id, client_user_id, status, assigned_at, created_at, modified_at, created_by, modified_by, completion_cycle_id
FROM mentorix.program_assignments
WHERE program_id = $1
  AND status = 'active'
ORDER BY assigned_at DESC
`

func (q *Queries) ListActiveProgramAssignmentsByProgramID(ctx context.Context, programID pgtype.UUID) ([]MentorixProgramAssignment, error) {
	rows, err := q.db.Query(ctx, listActiveProgramAssignmentsByProgramID, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorixProgramAssignment{}
	for rows.Next() {
		var i MentorixProgramAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.ProgramVersionID,
			&i.TrainerID,
			&i.ClientUserID,
			&i.Status,
			&i.AssignedAt,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.CompletionCycleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramAssignmentsByProgramID = `-- name: ListProgramAssignmentsByProgramID :many
SELECT id, program_id, program_version_id, trainer_id, client_user_id, status, assigned_at, created_at, modified_at, created_by, modified_by, completion_cycle_id
FROM mentorix.program_assignments
WHERE program_id = $1
ORDER BY assigned_at DESC
`

func (q *Queries) ListProgramAssignmentsByProgramID(ctx context.Context, programID pgtype.UUID) ([]MentorixProgramAssignment, error) {
	rows, err := q.db.Query(ctx, listProgramAssignmentsByProgramID, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorixProgramAssignment{}
	for rows.Next() {
		var i MentorixProgramAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.ProgramVersionID,
			&i.TrainerID,
			&i.ClientUserID,
			&i.Status,
			&i.AssignedAt,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.CompletionCycleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trainerClientLinkActive = `-- name: TrainerClientLinkActive :one
SELECT status
FROM mentorix.trainer_clients
WHERE trainer_id = $1
  AND client_user_id = $2
`

type TrainerClientLinkActiveParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

func (q *Queries) TrainerClientLinkActive(ctx context.Context, arg TrainerClientLinkActiveParams) (string, error) {
	row := q.db.QueryRow(ctx, trainerClientLinkActive, arg.TrainerID, arg.ClientUserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const updateProgramAssignment = `-- name: UpdateProgramAssignment :one
UPDATE mentorix.program_assignments
SET program_id = $3,
    program_version_id = $4,
    assigned_at = $5,
    modified_at = $6,
    modified_by = $7,
    completion_cycle_id = $8
WHERE trainer_id = $1
  AND client_user_id = $2
RETURNING id, program_id, program_version_id, trainer_id, client_user_id, status, assigned_at, created_at, modified_at, created_by, modified_by, completion_cycle_id
`

type UpdateProgramAssignmentParams struct {
	TrainerID         pgtype.UUID `json:"trainer_id"`
	ClientUserID      pgtype.UUID `json:"client_user_id"`
	ProgramID         pgtype.UUID `json:"program_id"`
	ProgramVersionID  pgtype.UUID `json:"program_version_id"`
	AssignedAt        time.Time   `json:"assigned_at"`
	ModifiedAt        time.Time   `json:"modified_at"`
	ModifiedBy        pgtype.UUID `json:"modified_by"`
	CompletionCycleID pgtype.UUID `json:"completion_cycle_id"`
}

func (q *Queries) UpdateProgramAssignment(ctx context.Context, arg UpdateProgramAssignmentParams) (MentorixProgramAssignment, error) {
	row := q.db.QueryRow(ctx, updateProgramAssignment,
		arg.TrainerID,
		arg.ClientUserID,
		arg.ProgramID,
		arg.ProgramVersionID,
		arg.AssignedAt,
		arg.ModifiedAt,
		arg.ModifiedBy,
		arg.CompletionCycleID,
	)
	var i MentorixProgramAssignment
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ProgramVersionID,
		&i.TrainerID,
		&i.ClientUserID,
		&i.Status,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.CompletionCycleID,
	)
	return i, err
}

const updateProgramAssignmentVersion = `-- name: UpdateProgramAssignmentVersion :execrows
UPDATE mentorix.program_assignments
SET program_version_id = $2,
    modified_at = $3,
    modified_by = $4
WHERE id = $1
  AND status = 'active'
`

type UpdateProgramAssignmentVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	ProgramVersionID pgtype.UUID `json:"program_version_id"`
	ModifiedAt       time.Time   `json:"modified_at"`
	ModifiedBy       pgtype.UUID `json:"modified_by"`
}

func (q *Queries) UpdateProgramAssignmentVersion(ctx context.Context, arg UpdateProgramAssignmentVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProgramAssignmentVersion,
		arg.ID,
		arg.ProgramVersionID,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
