// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: program_block_client.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProgramBlockClients = `-- name: ListProgramBlockClients :many
SELECT block_key, client_user_id
FROM mentorix.program_block_clients
WHERE program_id = $1
ORDER BY block_key, client_user_id
`

type ListProgramBlockClientsRow struct {
	BlockKey     pgtype.UUID `json:"block_key"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

func (q *Queries) ListProgramBlockClients(ctx context.Context, programID pgtype.UUID) ([]ListProgramBlockClientsRow, error) {
	rows, err := q.db.Query(ctx, listProgramBlockClients, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramBlockClientsRow{}
	for rows.Next() {
		var i ListProgramBlockClientsRow
		if err := rows.Scan(&i.BlockKey, &i.ClientUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
