// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: program_block_client.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const copyProgramBlockClients = `-- name: CopyProgramBlockClients :exec
INSERT INTO mentorix.program_block_clients (program_id, block_key, client_user_id, created_by)
SELECT src.program_id, $1, src.client_user_id, src.created_by
FROM mentorix.program_block_clients src
WHERE src.program_id = $2
  AND src.block_key = $3
ON CONFLICT (program_id, block_key, client_user_id) DO NOTHING
`

type CopyProgramBlockClientsParams struct {
	TargetBlockKey pgtype.UUID `json:"target_block_key"`
	ProgramID      pgtype.UUID `json:"program_id"`
	SourceBlockKey pgtype.UUID `json:"source_block_key"`
}

func (q *Queries) CopyProgramBlockClients(ctx context.Context, arg CopyProgramBlockClientsParams) error {
	_, err := q.db.Exec(ctx, copyProgramBlockClients, arg.TargetBlockKey, arg.ProgramID, arg.SourceBlockKey)
	return err
}

const deleteProgramBlockClients = `-- name: DeleteProgramBlockClients :exec
DELETE FROM mentorix.program_block_clients
WHERE program_id = $1 AND block_key = $2
`

type DeleteProgramBlockClientsParams struct {
	ProgramID pgtype.UUID `json:"program_id"`
	BlockKey  pgtype.UUID `json:"block_key"`
}

func (q *Queries) DeleteProgramBlockClients(ctx context.Context, arg DeleteProgramBlockClientsParams) error {
	_, err := q.db.Exec(ctx, deleteProgramBlockClients, arg.ProgramID, arg.BlockKey)
	return err
}

const deleteProgramBlockClientsForClient = `-- name: DeleteProgramBlockClientsForClient :exec
DELETE FROM mentorix.program_block_clients
WHERE program_id = $1 AND client_user_id = $2
`

type DeleteProgramBlockClientsForClientParams struct {
	ProgramID    pgtype.UUID `json:"program_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

func (q *Queries) DeleteProgramBlockClientsForClient(ctx context.Context, arg DeleteProgramBlockClientsForClientParams) error {
	_, err := q.db.Exec(ctx, deleteProgramBlockClientsForClient, arg.ProgramID, arg.ClientUserID)
	return err
}

const insertProgramBlockClient = `-- name: InsertProgramBlockClient :exec
INSERT INTO mentorix.program_block_clients (program_id, block_key, client_user_id, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (program_id, block_key, client_user_id) DO NOTHING
`

type InsertProgramBlockClientParams struct {
	ProgramID    pgtype.UUID `json:"program_id"`
	BlockKey     pgtype.UUID `json:"block_key"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertProgramBlockClient(ctx context.Context, arg InsertProgramBlockClientParams) error {
	_, err := q.db.Exec(ctx, insertProgramBlockClient,
		arg.ProgramID,
		arg.BlockKey,
		arg.ClientUserID,
		arg.CreatedBy,
	)
	return err
}

const listAssignedClientUserIDs = `-- name: ListAssignedClientUserIDs :many
SELECT DISTINCT client_user_id
FROM mentorix.program_assignments
WHERE program_id = $1
`

func (q *Queries) ListAssignedClientUserIDs(ctx context.Context, programID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAssignedClientUserIDs, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var client_user_id pgtype.UUID
		if err := rows.Scan(&client_user_id); err != nil {
			return nil, err
		}
		items = append(items, client_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignedProgramVersionIDs = `-- name: ListAssignedProgramVersionIDs :many
SELECT DISTINCT program_version_id
FROM mentorix.program_assignments
WHERE program_id = $1
`

func (q *Queries) ListAssignedProgramVersionIDs(ctx context.Context, programID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAssignedProgramVersionIDs, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var program_version_id pgtype.UUID
		if err := rows.Scan(&program_version_id); err != nil {
			return nil, err
		}
		items = append(items, program_version_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramBlockClients = `-- name: ListProgramBlockClients :many
SELECT block_key, client_user_id
FROM mentorix.program_block_clients
WHERE program_id = $1
ORDER BY block_key, client_user_id
`

type ListProgramBlockClientsRow struct {
	BlockKey     pgtype.UUID `json:"block_key"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

func (q *Queries) ListProgramBlockClients(ctx context.Context, programID pgtype.UUID) ([]ListProgramBlockClientsRow, error) {
	rows, err := q.db.Query(ctx, listProgramBlockClients, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramBlockClientsRow{}
	for rows.Next() {
		var i ListProgramBlockClientsRow
		if err := rows.Scan(&i.BlockKey, &i.ClientUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProgramForUpdate = `-- name: LockProgramForUpdate :exec
SELECT id
FROM mentorix.programs
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockProgramForUpdate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockProgramForUpdate, id)
	return err
}

const purgeOrphanProgramBlockClients = `-- name: PurgeOrphanProgramBlockClients :execrows
DELETE FROM mentorix.program_block_clients pbc
WHERE NOT EXISTS (
    SELECT 1
    FROM mentorix.program_week_day_blocks b
    JOIN mentorix.program_week_days d ON d.id = b.program_week_day_id
    WHERE d.program_id = pbc.program_id AND b.block_key = pbc.block_key
  )
  AND NOT EXISTS (
    SELECT 1
    FROM mentorix.program_version_week_day_blocks vb
    JOIN mentorix.program_version_week_days vd
      ON vd.id = vb.program_version_week_day_id
    JOIN mentorix.program_versions v ON v.id = vd.program_version_id
    WHERE v.program_id = pbc.program_id AND vb.block_key = pbc.block_key
  )
`

func (q *Queries) PurgeOrphanProgramBlockClients(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOrphanProgramBlockClients)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOrphanProgramBlockClientsForProgram = `-- name: PurgeOrphanProgramBlockClientsForProgram :execrows

DELETE FROM mentorix.program_block_clients pbc
WHERE pbc.program_id = $1
  AND NOT EXISTS (
    SELECT 1
    FROM mentorix.program_week_day_blocks b
    JOIN mentorix.program_week_days d ON d.id = b.program_week_day_id
    WHERE d.program_id = pbc.program_id AND b.block_key = pbc.block_key
  )
  AND NOT EXISTS (
    SELECT 1
    FROM mentorix.program_version_week_day_blocks vb
    JOIN mentorix.program_version_week_days vd
      ON vd.id = vb.program_version_week_day_id
    JOIN mentorix.program_versions v ON v.id = vd.program_version_id
    WHERE v.program_id = pbc.program_id AND vb.block_key = pbc.block_key
  )
`

// A rule is orphaned only when its block_key exists in neither the working
// copy (program_week_day_blocks, joined through program_week_days for the
// program_id) nor any surviving version of the same program. The version
// half matters: a block_key removed from the working copy can still live
// inside a frozen version a client is currently assigned to, and deleting
// its rule there would wrongly un-restrict the block for that client.
func (q *Queries) PurgeOrphanProgramBlockClientsForProgram(ctx context.Context, programID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOrphanProgramBlockClientsForProgram, programID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
