// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: program_version.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProgramAssignmentsByVersionID = `-- name: CountProgramAssignmentsByVersionID :one
SELECT COUNT(*)::int AS total
FROM mentorix.program_assignments
WHERE program_version_id = $1
`

func (q *Queries) CountProgramAssignmentsByVersionID(ctx context.Context, programVersionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProgramAssignmentsByVersionID, programVersionID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countProgramVersionsByProgramID = `-- name: CountProgramVersionsByProgramID :one
SELECT COUNT(*)::int AS total
FROM mentorix.program_versions
WHERE program_id = $1
`

func (q *Queries) CountProgramVersionsByProgramID(ctx context.Context, programID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProgramVersionsByProgramID, programID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const deleteProgramVersion = `-- name: DeleteProgramVersion :execrows
DELETE FROM mentorix.program_versions
WHERE id = $1
`

func (q *Queries) DeleteProgramVersion(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestProgramVersionByProgramID = `-- name: GetLatestProgramVersionByProgramID :one
SELECT id, program_id, version_number, published_at, published_by, name, name_ru, description, description_ru, category, difficulty, preview_image_url, created_at, content_fingerprint
FROM mentorix.program_versions
WHERE program_id = $1
ORDER BY version_number DESC
LIMIT 1
`

func (q *Queries) GetLatestProgramVersionByProgramID(ctx context.Context, programID pgtype.UUID) (MentorixProgramVersion, error) {
	row := q.db.QueryRow(ctx, getLatestProgramVersionByProgramID, programID)
	var i MentorixProgramVersion
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.VersionNumber,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.Name,
		&i.NameRu,
		&i.Description,
		&i.DescriptionRu,
		&i.Category,
		&i.Difficulty,
		&i.PreviewImageUrl,
		&i.CreatedAt,
		&i.ContentFingerprint,
	)
	return i, err
}

const getLatestProgramVersionFingerprint = `-- name: GetLatestProgramVersionFingerprint :one
SELECT content_fingerprint
FROM mentorix.program_versions
WHERE program_id = $1
ORDER BY version_number DESC
LIMIT 1
`

func (q *Queries) GetLatestProgramVersionFingerprint(ctx context.Context, programID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLatestProgramVersionFingerprint, programID)
	var content_fingerprint string
	err := row.Scan(&content_fingerprint)
	return content_fingerprint, err
}

const getMaxProgramVersionNumber = `-- name: GetMaxProgramVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::int AS max_version_number
FROM mentorix.program_versions
WHERE program_id = $1
`

func (q *Queries) GetMaxProgramVersionNumber(ctx context.Context, programID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxProgramVersionNumber, programID)
	var max_version_number int32
	err := row.Scan(&max_version_number)
	return max_version_number, err
}

const getProgramVersionByID = `-- name: GetProgramVersionByID :one
SELECT id, program_id, version_number, published_at, published_by, name, name_ru, description, description_ru, category, difficulty, preview_image_url, created_at, content_fingerprint
FROM mentorix.program_versions
WHERE id = $1
`

func (q *Queries) GetProgramVersionByID(ctx context.Context, id pgtype.UUID) (MentorixProgramVersion, error) {
	row := q.db.QueryRow(ctx, getProgramVersionByID, id)
	var i MentorixProgramVersion
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.VersionNumber,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.Name,
		&i.NameRu,
		&i.Description,
		&i.DescriptionRu,
		&i.Category,
		&i.Difficulty,
		&i.PreviewImageUrl,
		&i.CreatedAt,
		&i.ContentFingerprint,
	)
	return i, err
}

const insertProgramVersion = `-- name: InsertProgramVersion :one
INSERT INTO mentorix.program_versions (
  program_id,
  version_number,
  published_at,
  published_by,
  name,
  name_ru,
  description,
  description_ru,
  category,
  difficulty,
  preview_image_url,
  content_fingerprint
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, program_id, version_number, published_at, published_by, name, name_ru, description, description_ru, category, difficulty, preview_image_url, created_at, content_fingerprint
`

type InsertProgramVersionParams struct {
	ProgramID          pgtype.UUID `json:"program_id"`
	VersionNumber      int32       `json:"version_number"`
	PublishedAt        time.Time   `json:"published_at"`
	PublishedBy        pgtype.UUID `json:"published_by"`
	Name               string      `json:"name"`
	NameRu             string      `json:"name_ru"`
	Description        string      `json:"description"`
	DescriptionRu      string      `json:"description_ru"`
	Category           *string     `json:"category"`
	Difficulty         *string     `json:"difficulty"`
	PreviewImageUrl    string      `json:"preview_image_url"`
	ContentFingerprint string      `json:"content_fingerprint"`
}

func (q *Queries) InsertProgramVersion(ctx context.Context, arg InsertProgramVersionParams) (MentorixProgramVersion, error) {
	row := q.db.QueryRow(ctx, insertProgramVersion,
		arg.ProgramID,
		arg.VersionNumber,
		arg.PublishedAt,
		arg.PublishedBy,
		arg.Name,
		arg.NameRu,
		arg.Description,
		arg.DescriptionRu,
		arg.Category,
		arg.Difficulty,
		arg.PreviewImageUrl,
		arg.ContentFingerprint,
	)
	var i MentorixProgramVersion
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.VersionNumber,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.Name,
		&i.NameRu,
		&i.Description,
		&i.DescriptionRu,
		&i.Category,
		&i.Difficulty,
		&i.PreviewImageUrl,
		&i.CreatedAt,
		&i.ContentFingerprint,
	)
	return i, err
}

const insertProgramVersionDay = `-- name: InsertProgramVersionDay :one
INSERT INTO mentorix.program_version_days (
  program_version_id,
  program_version_week_id,
  day_number,
  sort_order
) VALUES ($1, $2, $3, $4)
RETURNING id, program_version_id, program_version_week_id, day_number, sort_order, created_at
`

type InsertProgramVersionDayParams struct {
	ProgramVersionID     pgtype.UUID `json:"program_version_id"`
	ProgramVersionWeekID pgtype.UUID `json:"program_version_week_id"`
	DayNumber            int32       `json:"day_number"`
	SortOrder            int32       `json:"sort_order"`
}

func (q *Queries) InsertProgramVersionDay(ctx context.Context, arg InsertProgramVersionDayParams) (MentorixProgramVersionDay, error) {
	row := q.db.QueryRow(ctx, insertProgramVersionDay,
		arg.ProgramVersionID,
		arg.ProgramVersionWeekID,
		arg.DayNumber,
		arg.SortOrder,
	)
	var i MentorixProgramVersionDay
	err := row.Scan(
		&i.ID,
		&i.ProgramVersionID,
		&i.ProgramVersionWeekID,
		&i.DayNumber,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const insertProgramVersionDayExercise = `-- name: InsertProgramVersionDayExercise :one
INSERT INTO mentorix.program_version_day_exercises (
  program_version_day_id,
  exercise_id,
  sort_order,
  sets,
  reps,
  weight_kg,
  instruction
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, program_version_day_id, exercise_id, sort_order, sets, reps, weight_kg, instruction, created_at
`

type InsertProgramVersionDayExerciseParams struct {
	ProgramVersionDayID pgtype.UUID    `json:"program_version_day_id"`
	ExerciseID          pgtype.UUID    `json:"exercise_id"`
	SortOrder           int32          `json:"sort_order"`
	Sets                *int32         `json:"sets"`
	Reps                *int32         `json:"reps"`
	WeightKg            pgtype.Numeric `json:"weight_kg"`
	Instruction         string         `json:"instruction"`
}

func (q *Queries) InsertProgramVersionDayExercise(ctx context.Context, arg InsertProgramVersionDayExerciseParams) (MentorixProgramVersionDayExercise, error) {
	row := q.db.QueryRow(ctx, insertProgramVersionDayExercise,
		arg.ProgramVersionDayID,
		arg.ExerciseID,
		arg.SortOrder,
		arg.Sets,
		arg.Reps,
		arg.WeightKg,
		arg.Instruction,
	)
	var i MentorixProgramVersionDayExercise
	err := row.Scan(
		&i.ID,
		&i.ProgramVersionDayID,
		&i.ExerciseID,
		&i.SortOrder,
		&i.Sets,
		&i.Reps,
		&i.WeightKg,
		&i.Instruction,
		&i.CreatedAt,
	)
	return i, err
}

const insertProgramVersionWeek = `-- name: InsertProgramVersionWeek :one
INSERT INTO mentorix.program_version_weeks (
  program_version_id,
  week_number,
  sort_order
) VALUES ($1, $2, $3)
RETURNING id, program_version_id, week_number, sort_order, created_at
`

type InsertProgramVersionWeekParams struct {
	ProgramVersionID pgtype.UUID `json:"program_version_id"`
	WeekNumber       int32       `json:"week_number"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) InsertProgramVersionWeek(ctx context.Context, arg InsertProgramVersionWeekParams) (MentorixProgramVersionWeek, error) {
	row := q.db.QueryRow(ctx, insertProgramVersionWeek, arg.ProgramVersionID, arg.WeekNumber, arg.SortOrder)
	var i MentorixProgramVersionWeek
	err := row.Scan(
		&i.ID,
		&i.ProgramVersionID,
		&i.WeekNumber,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listProgramVersionDayExercisesByVersionID = `-- name: ListProgramVersionDayExercisesByVersionID :many
SELECT pde.id, pde.program_version_day_id, pde.exercise_id, pde.sort_order, pde.sets, pde.reps, pde.weight_kg, pde.instruction, pde.created_at
FROM mentorix.program_version_day_exercises pde
JOIN mentorix.program_version_days pd ON pd.id = pde.program_version_day_id
WHERE pd.program_version_id = $1
ORDER BY pd.sort_order ASC, pd.day_number ASC, pde.sort_order ASC
`

func (q *Queries) ListProgramVersionDayExercisesByVersionID(ctx context.Context, programVersionID pgtype.UUID) ([]MentorixProgramVersionDayExercise, error) {
	rows, err := q.db.Query(ctx, listProgramVersionDayExercisesByVersionID, programVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorixProgramVersionDayExercise{}
	for rows.Next() {
		var i MentorixProgramVersionDayExercise
		if err := rows.Scan(
			&i.ID,
			&i.ProgramVersionDayID,
			&i.ExerciseID,
			&i.SortOrder,
			&i.Sets,
			&i.Reps,
			&i.WeightKg,
			&i.Instruction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramVersionDaysByVersionID = `-- name: ListProgramVersionDaysByVersionID :many
SELECT id, program_version_id, program_version_week_id, day_number, sort_order, created_at
FROM mentorix.program_version_days
WHERE program_version_id = $1
ORDER BY sort_order ASC, day_number ASC
`

func (q *Queries) ListProgramVersionDaysByVersionID(ctx context.Context, programVersionID pgtype.UUID) ([]MentorixProgramVersionDay, error) {
	rows, err := q.db.Query(ctx, listProgramVersionDaysByVersionID, programVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorixProgramVersionDay{}
	for rows.Next() {
		var i MentorixProgramVersionDay
		if err := rows.Scan(
			&i.ID,
			&i.ProgramVersionID,
			&i.ProgramVersionWeekID,
			&i.DayNumber,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramVersionWeeksByVersionID = `-- name: ListProgramVersionWeeksByVersionID :many
SELECT id, program_version_id, week_number, sort_order, created_at
FROM mentorix.program_version_weeks
WHERE program_version_id = $1
ORDER BY sort_order ASC, week_number ASC
`

func (q *Queries) ListProgramVersionWeeksByVersionID(ctx context.Context, programVersionID pgtype.UUID) ([]MentorixProgramVersionWeek, error) {
	rows, err := q.db.Query(ctx, listProgramVersionWeeksByVersionID, programVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorixProgramVersionWeek{}
	for rows.Next() {
		var i MentorixProgramVersionWeek
		if err := rows.Scan(
			&i.ID,
			&i.ProgramVersionID,
			&i.WeekNumber,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramVersionsByProgramID = `-- name: ListProgramVersionsByProgramID :many
SELECT
  pv.id, pv.program_id, pv.version_number, pv.published_at, pv.published_by, pv.name, pv.name_ru, pv.description, pv.description_ru, pv.category, pv.difficulty, pv.preview_image_url, pv.created_at, pv.content_fingerprint,
  COUNT(pa.id) FILTER (WHERE pa.status = 'active')::int AS assignment_count
FROM mentorix.program_versions pv
LEFT JOIN mentorix.program_assignments pa ON pa.program_version_id = pv.id
WHERE pv.program_id = $1
GROUP BY pv.id
ORDER BY pv.version_number DESC
`

type ListProgramVersionsByProgramIDRow struct {
	ID                 pgtype.UUID `json:"id"`
	ProgramID          pgtype.UUID `json:"program_id"`
	VersionNumber      int32       `json:"version_number"`
	PublishedAt        time.Time   `json:"published_at"`
	PublishedBy        pgtype.UUID `json:"published_by"`
	Name               string      `json:"name"`
	NameRu             string      `json:"name_ru"`
	Description        string      `json:"description"`
	DescriptionRu      string      `json:"description_ru"`
	Category           *string     `json:"category"`
	Difficulty         *string     `json:"difficulty"`
	PreviewImageUrl    string      `json:"preview_image_url"`
	CreatedAt          time.Time   `json:"created_at"`
	ContentFingerprint string      `json:"content_fingerprint"`
	AssignmentCount    int32       `json:"assignment_count"`
}

func (q *Queries) ListProgramVersionsByProgramID(ctx context.Context, programID pgtype.UUID) ([]ListProgramVersionsByProgramIDRow, error) {
	rows, err := q.db.Query(ctx, listProgramVersionsByProgramID, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramVersionsByProgramIDRow{}
	for rows.Next() {
		var i ListProgramVersionsByProgramIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.VersionNumber,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.Name,
			&i.NameRu,
			&i.Description,
			&i.DescriptionRu,
			&i.Category,
			&i.Difficulty,
			&i.PreviewImageUrl,
			&i.CreatedAt,
			&i.ContentFingerprint,
			&i.AssignmentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
