// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: program.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockBelongsToDay = `-- name: BlockBelongsToDay :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.program_week_day_blocks
  WHERE id = $1 AND program_week_day_id = $2
) AS ok
`

type BlockBelongsToDayParams struct {
	ID               pgtype.UUID `json:"id"`
	ProgramWeekDayID pgtype.UUID `json:"program_week_day_id"`
}

func (q *Queries) BlockBelongsToDay(ctx context.Context, arg BlockBelongsToDayParams) (bool, error) {
	row := q.db.QueryRow(ctx, blockBelongsToDay, arg.ID, arg.ProgramWeekDayID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const blockBelongsToProgram = `-- name: BlockBelongsToProgram :one
SELECT EXISTS(
  SELECT 1
  FROM mentorix.program_week_day_blocks pdb
  JOIN mentorix.program_week_days pd ON pd.id = pdb.program_week_day_id
  WHERE pdb.id = $1 AND pd.program_id = $2
) AS ok
`

type BlockBelongsToProgramParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) BlockBelongsToProgram(ctx context.Context, arg BlockBelongsToProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, blockBelongsToProgram, arg.ID, arg.ProgramID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const countBlockExercises = `-- name: CountBlockExercises :one
SELECT COUNT(*)::int AS count
FROM mentorix.program_week_day_block_exercises
WHERE program_week_day_block_id = $1
`

func (q *Queries) CountBlockExercises(ctx context.Context, programWeekDayBlockID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBlockExercises, programWeekDayBlockID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countProgramDaysForWeek = `-- name: CountProgramDaysForWeek :one
SELECT COUNT(*)::int AS count
FROM mentorix.program_week_days
WHERE week_id = $1
`

func (q *Queries) CountProgramDaysForWeek(ctx context.Context, weekID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProgramDaysForWeek, weekID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countProgramWeeks = `-- name: CountProgramWeeks :one
SELECT COUNT(*)::int AS count
FROM mentorix.program_weeks
WHERE program_id = $1
`

func (q *Queries) CountProgramWeeks(ctx context.Context, programID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProgramWeeks, programID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countPrograms = `-- name: CountPrograms :one
SELECT COUNT(*)::int AS total
FROM mentorix.programs
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR created_by = $1)
  AND (
    $2::text IS NULL
    OR name ILIKE $2 ESCAPE '\'
    OR name_ru ILIKE $2 ESCAPE '\'
  )
  AND ($3::text[] IS NULL OR status = ANY($3))
  AND ($4::text IS NULL OR category = $4)
  AND ($5::text IS NULL OR difficulty = $5)
`

type CountProgramsParams struct {
	FilterCreatedBy  pgtype.UUID `json:"filter_created_by"`
	QPattern         *string     `json:"q_pattern"`
	FilterStatuses   []string    `json:"filter_statuses"`
	FilterCategory   *string     `json:"filter_category"`
	FilterDifficulty *string     `json:"filter_difficulty"`
}

func (q *Queries) CountPrograms(ctx context.Context, arg CountProgramsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPrograms,
		arg.FilterCreatedBy,
		arg.QPattern,
		arg.FilterStatuses,
		arg.FilterCategory,
		arg.FilterDifficulty,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const dayBelongsToProgram = `-- name: DayBelongsToProgram :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.program_week_days
  WHERE id = $1 AND program_id = $2
) AS ok
`

type DayBelongsToProgramParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) DayBelongsToProgram(ctx context.Context, arg DayBelongsToProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, dayBelongsToProgram, arg.ID, arg.ProgramID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const dayBelongsToWeek = `-- name: DayBelongsToWeek :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.program_week_days
  WHERE id = $1 AND week_id = $2 AND program_id = $3
) AS ok
`

type DayBelongsToWeekParams struct {
	ID        pgtype.UUID `json:"id"`
	WeekID    pgtype.UUID `json:"week_id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) DayBelongsToWeek(ctx context.Context, arg DayBelongsToWeekParams) (bool, error) {
	row := q.db.QueryRow(ctx, dayBelongsToWeek, arg.ID, arg.WeekID, arg.ProgramID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const deleteBlockExercise = `-- name: DeleteBlockExercise :execrows
DELETE FROM mentorix.program_week_day_block_exercises
WHERE id = $1 AND program_week_day_block_id = $2
`

type DeleteBlockExerciseParams struct {
	ID                    pgtype.UUID `json:"id"`
	ProgramWeekDayBlockID pgtype.UUID `json:"program_week_day_block_id"`
}

func (q *Queries) DeleteBlockExercise(ctx context.Context, arg DeleteBlockExerciseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockExercise, arg.ID, arg.ProgramWeekDayBlockID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDayBlock = `-- name: DeleteDayBlock :execrows
DELETE FROM mentorix.program_week_day_blocks
WHERE id = $1 AND program_week_day_id = $2
`

type DeleteDayBlockParams struct {
	ID               pgtype.UUID `json:"id"`
	ProgramWeekDayID pgtype.UUID `json:"program_week_day_id"`
}

func (q *Queries) DeleteDayBlock(ctx context.Context, arg DeleteDayBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDayBlock, arg.ID, arg.ProgramWeekDayID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgramDay = `-- name: DeleteProgramDay :execrows
DELETE FROM mentorix.program_week_days
WHERE id = $1 AND program_id = $2 AND week_id = $3
`

type DeleteProgramDayParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
	WeekID    pgtype.UUID `json:"week_id"`
}

func (q *Queries) DeleteProgramDay(ctx context.Context, arg DeleteProgramDayParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramDay, arg.ID, arg.ProgramID, arg.WeekID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgramWeek = `-- name: DeleteProgramWeek :execrows
DELETE FROM mentorix.program_weeks
WHERE id = $1 AND program_id = $2
`

type DeleteProgramWeekParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) DeleteProgramWeek(ctx context.Context, arg DeleteProgramWeekParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramWeek, arg.ID, arg.ProgramID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exerciseExists = `-- name: ExerciseExists :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.exercises WHERE id = $1 AND deleted_at IS NULL
) AS ok
`

func (q *Queries) ExerciseExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, exerciseExists, id)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const getBlockExerciseMeta = `-- name: GetBlockExerciseMeta :one
SELECT pde.id, pde.program_week_day_block_id, pdb.program_week_day_id, pdb.block_type
FROM mentorix.program_week_day_block_exercises pde
JOIN mentorix.program_week_day_blocks pdb ON pdb.id = pde.program_week_day_block_id
WHERE pde.id = $1
`

type GetBlockExerciseMetaRow struct {
	ID                    pgtype.UUID `json:"id"`
	ProgramWeekDayBlockID pgtype.UUID `json:"program_week_day_block_id"`
	ProgramWeekDayID      pgtype.UUID `json:"program_week_day_id"`
	BlockType             string      `json:"block_type"`
}

func (q *Queries) GetBlockExerciseMeta(ctx context.Context, id pgtype.UUID) (GetBlockExerciseMetaRow, error) {
	row := q.db.QueryRow(ctx, getBlockExerciseMeta, id)
	var i GetBlockExerciseMetaRow
	err := row.Scan(
		&i.ID,
		&i.ProgramWeekDayBlockID,
		&i.ProgramWeekDayID,
		&i.BlockType,
	)
	return i, err
}

const getDayBlockByID = `-- name: GetDayBlockByID :one
SELECT id, program_week_day_id, block_type, instruction, sort_order, created_at
FROM mentorix.program_week_day_blocks
WHERE id = $1
`

func (q *Queries) GetDayBlockByID(ctx context.Context, id pgtype.UUID) (MentorixProgramWeekDayBlock, error) {
	row := q.db.QueryRow(ctx, getDayBlockByID, id)
	var i MentorixProgramWeekDayBlock
	err := row.Scan(
		&i.ID,
		&i.ProgramWeekDayID,
		&i.BlockType,
		&i.Instruction,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT
  p.id, p.created_by, p.modified_by, p.status, p.name, p.name_ru, p.description, p.description_ru,
  p.category, p.difficulty, p.preview_image_url, p.created_at, p.modified_at, p.deleted_at,
  COALESCE(u.display_name, '') AS created_by_name
FROM mentorix.programs p
JOIN mentorix.users u ON u.id = p.created_by
WHERE p.id = $1
`

type GetProgramByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	Status          string             `json:"status"`
	Name            string             `json:"name"`
	NameRu          string             `json:"name_ru"`
	Description     string             `json:"description"`
	DescriptionRu   string             `json:"description_ru"`
	Category        *string            `json:"category"`
	Difficulty      *string            `json:"difficulty"`
	PreviewImageUrl string             `json:"preview_image_url"`
	CreatedAt       time.Time          `json:"created_at"`
	ModifiedAt      time.Time          `json:"modified_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedByName   string             `json:"created_by_name"`
}

func (q *Queries) GetProgramByID(ctx context.Context, id pgtype.UUID) (GetProgramByIDRow, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i GetProgramByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.Status,
		&i.Name,
		&i.NameRu,
		&i.Description,
		&i.DescriptionRu,
		&i.Category,
		&i.Difficulty,
		&i.PreviewImageUrl,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.CreatedByName,
	)
	return i, err
}

const insertBlockExercise = `-- name: InsertBlockExercise :exec
INSERT INTO mentorix.program_week_day_block_exercises (
  program_week_day_block_id, exercise_id, sort_order, sets, reps, instruction,
  modified_at, modified_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertBlockExerciseParams struct {
	ProgramWeekDayBlockID pgtype.UUID `json:"program_week_day_block_id"`
	ExerciseID            pgtype.UUID `json:"exercise_id"`
	SortOrder             int32       `json:"sort_order"`
	Sets                  *int32      `json:"sets"`
	Reps                  *int32      `json:"reps"`
	Instruction           string      `json:"instruction"`
	ModifiedAt            time.Time   `json:"modified_at"`
	ModifiedBy            pgtype.UUID `json:"modified_by"`
}

func (q *Queries) InsertBlockExercise(ctx context.Context, arg InsertBlockExerciseParams) error {
	_, err := q.db.Exec(ctx, insertBlockExercise,
		arg.ProgramWeekDayBlockID,
		arg.ExerciseID,
		arg.SortOrder,
		arg.Sets,
		arg.Reps,
		arg.Instruction,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	return err
}

const insertDayBlock = `-- name: InsertDayBlock :one
INSERT INTO mentorix.program_week_day_blocks (
  program_week_day_id, block_type, instruction, sort_order
) VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertDayBlockParams struct {
	ProgramWeekDayID pgtype.UUID `json:"program_week_day_id"`
	BlockType        string      `json:"block_type"`
	Instruction      string      `json:"instruction"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) InsertDayBlock(ctx context.Context, arg InsertDayBlockParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDayBlock,
		arg.ProgramWeekDayID,
		arg.BlockType,
		arg.Instruction,
		arg.SortOrder,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProgramDay = `-- name: InsertProgramDay :one
INSERT INTO mentorix.program_week_days (program_id, week_id, day_number, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertProgramDayParams struct {
	ProgramID pgtype.UUID `json:"program_id"`
	WeekID    pgtype.UUID `json:"week_id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProgramDay(ctx context.Context, arg InsertProgramDayParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProgramDay,
		arg.ProgramID,
		arg.WeekID,
		arg.DayNumber,
		arg.SortOrder,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProgramDayAuto = `-- name: InsertProgramDayAuto :exec
INSERT INTO mentorix.program_week_days (program_id, week_id, day_number, sort_order)
VALUES ($1, $2, $3, $4)
`

type InsertProgramDayAutoParams struct {
	ProgramID pgtype.UUID `json:"program_id"`
	WeekID    pgtype.UUID `json:"week_id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProgramDayAuto(ctx context.Context, arg InsertProgramDayAutoParams) error {
	_, err := q.db.Exec(ctx, insertProgramDayAuto,
		arg.ProgramID,
		arg.WeekID,
		arg.DayNumber,
		arg.SortOrder,
	)
	return err
}

const insertProgramDraft = `-- name: InsertProgramDraft :one
INSERT INTO mentorix.programs (created_by, modified_by, status, modified_at)
VALUES ($1, $1, $2, $3)
RETURNING id
`

type InsertProgramDraftParams struct {
	CreatedBy  pgtype.UUID `json:"created_by"`
	Status     string      `json:"status"`
	ModifiedAt time.Time   `json:"modified_at"`
}

func (q *Queries) InsertProgramDraft(ctx context.Context, arg InsertProgramDraftParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProgramDraft, arg.CreatedBy, arg.Status, arg.ModifiedAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProgramWeek = `-- name: InsertProgramWeek :one
INSERT INTO mentorix.program_weeks (program_id, week_number, sort_order, modified_at, modified_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertProgramWeekParams struct {
	ProgramID  pgtype.UUID `json:"program_id"`
	WeekNumber int32       `json:"week_number"`
	SortOrder  int32       `json:"sort_order"`
	ModifiedAt time.Time   `json:"modified_at"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
}

func (q *Queries) InsertProgramWeek(ctx context.Context, arg InsertProgramWeekParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProgramWeek,
		arg.ProgramID,
		arg.WeekNumber,
		arg.SortOrder,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listBlockExercises = `-- name: ListBlockExercises :many
SELECT
  pde.id,
  pde.exercise_id,
  e.name,
  e.name_ru,
  pde.sort_order,
  pde.sets,
  pde.reps,
  pde.instruction,
  pde.created_at
FROM mentorix.program_week_day_block_exercises pde
JOIN mentorix.exercises e ON e.id = pde.exercise_id
WHERE pde.program_week_day_block_id = $1
ORDER BY pde.sort_order ASC, pde.created_at ASC
`

type ListBlockExercisesRow struct {
	ID          pgtype.UUID `json:"id"`
	ExerciseID  pgtype.UUID `json:"exercise_id"`
	Name        string      `json:"name"`
	NameRu      string      `json:"name_ru"`
	SortOrder   int32       `json:"sort_order"`
	Sets        *int32      `json:"sets"`
	Reps        *int32      `json:"reps"`
	Instruction string      `json:"instruction"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListBlockExercises(ctx context.Context, programWeekDayBlockID pgtype.UUID) ([]ListBlockExercisesRow, error) {
	rows, err := q.db.Query(ctx, listBlockExercises, programWeekDayBlockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockExercisesRow{}
	for rows.Next() {
		var i ListBlockExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.Name,
			&i.NameRu,
			&i.SortOrder,
			&i.Sets,
			&i.Reps,
			&i.Instruction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByWeek = `-- name: ListBlocksByWeek :many
SELECT pdb.id, pdb.program_week_day_id, pdb.block_type, pdb.instruction, pdb.sort_order, pdb.created_at
FROM mentorix.program_week_day_blocks pdb
JOIN mentorix.program_week_days pd ON pd.id = pdb.program_week_day_id
WHERE pd.week_id = $1
ORDER BY pd.sort_order ASC, pd.day_number ASC, pdb.sort_order ASC, pdb.created_at ASC
`

func (q *Queries) ListBlocksByWeek(ctx context.Context, weekID pgtype.UUID) ([]MentorixProgramWeekDayBlock, error) {
	rows, err := q.db.Query(ctx, listBlocksByWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorixProgramWeekDayBlock{}
	for rows.Next() {
		var i MentorixProgramWeekDayBlock
		if err := rows.Scan(
			&i.ID,
			&i.ProgramWeekDayID,
			&i.BlockType,
			&i.Instruction,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayBlockIDsForDay = `-- name: ListDayBlockIDsForDay :many
SELECT id
FROM mentorix.program_week_day_blocks
WHERE program_week_day_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListDayBlockIDsForDay(ctx context.Context, programWeekDayID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listDayBlockIDsForDay, programWeekDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayBlocks = `-- name: ListDayBlocks :many
SELECT id, block_type, instruction, sort_order, created_at
FROM mentorix.program_week_day_blocks
WHERE program_week_day_id = $1
ORDER BY sort_order ASC, created_at ASC
`

type ListDayBlocksRow struct {
	ID          pgtype.UUID `json:"id"`
	BlockType   string      `json:"block_type"`
	Instruction string      `json:"instruction"`
	SortOrder   int32       `json:"sort_order"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListDayBlocks(ctx context.Context, programWeekDayID pgtype.UUID) ([]ListDayBlocksRow, error) {
	rows, err := q.db.Query(ctx, listDayBlocks, programWeekDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDayBlocksRow{}
	for rows.Next() {
		var i ListDayBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.BlockType,
			&i.Instruction,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseItemsByWeek = `-- name: ListExerciseItemsByWeek :many
SELECT pde.id, pdb.program_week_day_id
FROM mentorix.program_week_day_block_exercises pde
JOIN mentorix.program_week_day_blocks pdb ON pdb.id = pde.program_week_day_block_id
JOIN mentorix.program_week_days pd ON pd.id = pdb.program_week_day_id
WHERE pd.week_id = $1
`

type ListExerciseItemsByWeekRow struct {
	ID               pgtype.UUID `json:"id"`
	ProgramWeekDayID pgtype.UUID `json:"program_week_day_id"`
}

func (q *Queries) ListExerciseItemsByWeek(ctx context.Context, weekID pgtype.UUID) ([]ListExerciseItemsByWeekRow, error) {
	rows, err := q.db.Query(ctx, listExerciseItemsByWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExerciseItemsByWeekRow{}
	for rows.Next() {
		var i ListExerciseItemsByWeekRow
		if err := rows.Scan(&i.ID, &i.ProgramWeekDayID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramDayIDsForWeek = `-- name: ListProgramDayIDsForWeek :many
SELECT id
FROM mentorix.program_week_days
WHERE week_id = $1
ORDER BY sort_order ASC, day_number ASC
`

func (q *Queries) ListProgramDayIDsForWeek(ctx context.Context, weekID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listProgramDayIDsForWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramDaysForWeek = `-- name: ListProgramDaysForWeek :many
SELECT id, day_number, sort_order, created_at
FROM mentorix.program_week_days
WHERE week_id = $1
ORDER BY sort_order ASC, day_number ASC
`

type ListProgramDaysForWeekRow struct {
	ID        pgtype.UUID `json:"id"`
	DayNumber int32       `json:"day_number"`
	SortOrder int32       `json:"sort_order"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) ListProgramDaysForWeek(ctx context.Context, weekID pgtype.UUID) ([]ListProgramDaysForWeekRow, error) {
	rows, err := q.db.Query(ctx, listProgramDaysForWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramDaysForWeekRow{}
	for rows.Next() {
		var i ListProgramDaysForWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.DayNumber,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramWeekIDs = `-- name: ListProgramWeekIDs :many
SELECT id
FROM mentorix.program_weeks
WHERE program_id = $1
ORDER BY sort_order ASC, week_number ASC
`

func (q *Queries) ListProgramWeekIDs(ctx context.Context, programID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listProgramWeekIDs, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramWeeks = `-- name: ListProgramWeeks :many
SELECT id, week_number, sort_order, created_at
FROM mentorix.program_weeks
WHERE program_id = $1
ORDER BY sort_order ASC, week_number ASC
`

type ListProgramWeeksRow struct {
	ID         pgtype.UUID `json:"id"`
	WeekNumber int32       `json:"week_number"`
	SortOrder  int32       `json:"sort_order"`
	CreatedAt  time.Time   `json:"created_at"`
}

func (q *Queries) ListProgramWeeks(ctx context.Context, programID pgtype.UUID) ([]ListProgramWeeksRow, error) {
	rows, err := q.db.Query(ctx, listProgramWeeks, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramWeeksRow{}
	for rows.Next() {
		var i ListProgramWeeksRow
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT
  p.id, p.created_by, p.modified_by, p.status, p.name, p.name_ru, p.description, p.description_ru,
  p.category, p.difficulty, p.preview_image_url, p.created_at, p.modified_at, p.deleted_at,
  COALESCE(u.display_name, '') AS created_by_name
FROM mentorix.programs p
JOIN mentorix.users u ON u.id = p.created_by
WHERE p.deleted_at IS NULL
  AND ($1::uuid IS NULL OR p.created_by = $1)
  AND (
    $2::text IS NULL
    OR p.name ILIKE $2 ESCAPE '\'
    OR p.name_ru ILIKE $2 ESCAPE '\'
  )
  AND ($3::text[] IS NULL OR p.status = ANY($3))
  AND ($4::text IS NULL OR p.category = $4)
  AND ($5::text IS NULL OR p.difficulty = $5)
ORDER BY
  CASE WHEN $6 = 'name' AND $7 = 'asc' THEN p.name END ASC NULLS LAST,
  CASE WHEN $6 = 'name' AND $7 = 'desc' THEN p.name END DESC NULLS LAST,
  CASE WHEN $6 = 'name_ru' AND $7 = 'asc' THEN p.name_ru END ASC NULLS LAST,
  CASE WHEN $6 = 'name_ru' AND $7 = 'desc' THEN p.name_ru END DESC NULLS LAST,
  CASE WHEN $6 = 'created_at' AND $7 = 'asc' THEN p.created_at END ASC NULLS LAST,
  CASE WHEN $6 = 'created_at' AND $7 = 'desc' THEN p.created_at END DESC NULLS LAST,
  CASE WHEN $6 = 'modified_at' AND $7 = 'asc' THEN p.modified_at END ASC NULLS LAST,
  CASE WHEN $6 = 'modified_at' AND $7 = 'desc' THEN p.modified_at END DESC NULLS LAST,
  CASE WHEN $6 = 'status' AND $7 = 'asc' THEN p.status END ASC NULLS LAST,
  CASE WHEN $6 = 'status' AND $7 = 'desc' THEN p.status END DESC NULLS LAST,
  CASE WHEN $6 = 'category' AND $7 = 'asc' THEN p.category END ASC NULLS LAST,
  CASE WHEN $6 = 'category' AND $7 = 'desc' THEN p.category END DESC NULLS LAST,
  CASE WHEN $6 = 'difficulty' AND $7 = 'asc' THEN p.difficulty END ASC NULLS LAST,
  CASE WHEN $6 = 'difficulty' AND $7 = 'desc' THEN p.difficulty END DESC NULLS LAST,
  p.id ASC
LIMIT $9 OFFSET $8
`

type ListProgramsParams struct {
	FilterCreatedBy  pgtype.UUID `json:"filter_created_by"`
	QPattern         *string     `json:"q_pattern"`
	FilterStatuses   []string    `json:"filter_statuses"`
	FilterCategory   *string     `json:"filter_category"`
	FilterDifficulty *string     `json:"filter_difficulty"`
	SortBy           interface{} `json:"sort_by"`
	SortOrder        interface{} `json:"sort_order"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

type ListProgramsRow struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	Status          string             `json:"status"`
	Name            string             `json:"name"`
	NameRu          string             `json:"name_ru"`
	Description     string             `json:"description"`
	DescriptionRu   string             `json:"description_ru"`
	Category        *string            `json:"category"`
	Difficulty      *string            `json:"difficulty"`
	PreviewImageUrl string             `json:"preview_image_url"`
	CreatedAt       time.Time          `json:"created_at"`
	ModifiedAt      time.Time          `json:"modified_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedByName   string             `json:"created_by_name"`
}

func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]ListProgramsRow, error) {
	rows, err := q.db.Query(ctx, listPrograms,
		arg.FilterCreatedBy,
		arg.QPattern,
		arg.FilterStatuses,
		arg.FilterCategory,
		arg.FilterDifficulty,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsRow{}
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.Status,
			&i.Name,
			&i.NameRu,
			&i.Description,
			&i.DescriptionRu,
			&i.Category,
			&i.Difficulty,
			&i.PreviewImageUrl,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBlockExerciseSort = `-- name: NextBlockExerciseSort :one
SELECT COALESCE(MAX(sort_order), 0) + 1::int AS next_sort
FROM mentorix.program_week_day_block_exercises
WHERE program_week_day_block_id = $1
`

func (q *Queries) NextBlockExerciseSort(ctx context.Context, programWeekDayBlockID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextBlockExerciseSort, programWeekDayBlockID)
	var next_sort int32
	err := row.Scan(&next_sort)
	return next_sort, err
}

const nextDayBlockSort = `-- name: NextDayBlockSort :one
SELECT COALESCE(MAX(sort_order), 0) + 1::int AS next_sort
FROM mentorix.program_week_day_blocks
WHERE program_week_day_id = $1
`

func (q *Queries) NextDayBlockSort(ctx context.Context, programWeekDayID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextDayBlockSort, programWeekDayID)
	var next_sort int32
	err := row.Scan(&next_sort)
	return next_sort, err
}

const nextProgramDayNumbersForWeek = `-- name: NextProgramDayNumbersForWeek :one
SELECT
  COALESCE(MAX(day_number), 0) + 1::int AS next_day_number,
  COALESCE(MAX(sort_order), 0) + 1::int AS next_sort_order
FROM mentorix.program_week_days
WHERE week_id = $1
`

type NextProgramDayNumbersForWeekRow struct {
	NextDayNumber int32 `json:"next_day_number"`
	NextSortOrder int32 `json:"next_sort_order"`
}

func (q *Queries) NextProgramDayNumbersForWeek(ctx context.Context, weekID pgtype.UUID) (NextProgramDayNumbersForWeekRow, error) {
	row := q.db.QueryRow(ctx, nextProgramDayNumbersForWeek, weekID)
	var i NextProgramDayNumbersForWeekRow
	err := row.Scan(&i.NextDayNumber, &i.NextSortOrder)
	return i, err
}

const nextProgramWeekNumbers = `-- name: NextProgramWeekNumbers :one
SELECT
  COALESCE(MAX(week_number), 0) + 1::int AS next_week_number,
  COALESCE(MAX(sort_order), 0) + 1::int AS next_sort_order
FROM mentorix.program_weeks
WHERE program_id = $1
`

type NextProgramWeekNumbersRow struct {
	NextWeekNumber int32 `json:"next_week_number"`
	NextSortOrder  int32 `json:"next_sort_order"`
}

func (q *Queries) NextProgramWeekNumbers(ctx context.Context, programID pgtype.UUID) (NextProgramWeekNumbersRow, error) {
	row := q.db.QueryRow(ctx, nextProgramWeekNumbers, programID)
	var i NextProgramWeekNumbersRow
	err := row.Scan(&i.NextWeekNumber, &i.NextSortOrder)
	return i, err
}

const setProgramStatus = `-- name: SetProgramStatus :execrows
UPDATE mentorix.programs SET
  status = $2,
  modified_by = $3,
  modified_at = $4
WHERE id = $1 AND deleted_at IS NULL
`

type SetProgramStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	ModifiedBy pgtype.UUID `json:"modified_by"`
	ModifiedAt time.Time   `json:"modified_at"`
}

func (q *Queries) SetProgramStatus(ctx context.Context, arg SetProgramStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProgramStatus,
		arg.ID,
		arg.Status,
		arg.ModifiedBy,
		arg.ModifiedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProgram = `-- name: SoftDeleteProgram :execrows
UPDATE mentorix.programs SET
  deleted_at = $2,
  modified_by = $3,
  modified_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteProgramParams struct {
	ID         pgtype.UUID        `json:"id"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ModifiedBy pgtype.UUID        `json:"modified_by"`
}

func (q *Queries) SoftDeleteProgram(ctx context.Context, arg SoftDeleteProgramParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProgram, arg.ID, arg.DeletedAt, arg.ModifiedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBlockExercise = `-- name: UpdateBlockExercise :execrows
UPDATE mentorix.program_week_day_block_exercises SET
  exercise_id = $3,
  sets = $4,
  reps = $5,
  instruction = $6,
  modified_at = $7,
  modified_by = $8
WHERE id = $1 AND program_week_day_block_id = $2
`

type UpdateBlockExerciseParams struct {
	ID                    pgtype.UUID `json:"id"`
	ProgramWeekDayBlockID pgtype.UUID `json:"program_week_day_block_id"`
	ExerciseID            pgtype.UUID `json:"exercise_id"`
	Sets                  *int32      `json:"sets"`
	Reps                  *int32      `json:"reps"`
	Instruction           string      `json:"instruction"`
	ModifiedAt            time.Time   `json:"modified_at"`
	ModifiedBy            pgtype.UUID `json:"modified_by"`
}

func (q *Queries) UpdateBlockExercise(ctx context.Context, arg UpdateBlockExerciseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBlockExercise,
		arg.ID,
		arg.ProgramWeekDayBlockID,
		arg.ExerciseID,
		arg.Sets,
		arg.Reps,
		arg.Instruction,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBlockExercisePlacement = `-- name: UpdateBlockExercisePlacement :exec
UPDATE mentorix.program_week_day_block_exercises SET
  program_week_day_block_id = $2,
  sort_order = $3,
  modified_at = $4,
  modified_by = $5
WHERE id = $1
`

type UpdateBlockExercisePlacementParams struct {
	ID                    pgtype.UUID `json:"id"`
	ProgramWeekDayBlockID pgtype.UUID `json:"program_week_day_block_id"`
	SortOrder             int32       `json:"sort_order"`
	ModifiedAt            time.Time   `json:"modified_at"`
	ModifiedBy            pgtype.UUID `json:"modified_by"`
}

func (q *Queries) UpdateBlockExercisePlacement(ctx context.Context, arg UpdateBlockExercisePlacementParams) error {
	_, err := q.db.Exec(ctx, updateBlockExercisePlacement,
		arg.ID,
		arg.ProgramWeekDayBlockID,
		arg.SortOrder,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	return err
}

const updateDayBlock = `-- name: UpdateDayBlock :execrows
UPDATE mentorix.program_week_day_blocks SET
  block_type = COALESCE($1, block_type),
  instruction = COALESCE($2, instruction)
WHERE id = $3 AND program_week_day_id = $4
`

type UpdateDayBlockParams struct {
	BlockType        *string     `json:"block_type"`
	Instruction      *string     `json:"instruction"`
	ID               pgtype.UUID `json:"id"`
	ProgramWeekDayID pgtype.UUID `json:"program_week_day_id"`
}

func (q *Queries) UpdateDayBlock(ctx context.Context, arg UpdateDayBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDayBlock,
		arg.BlockType,
		arg.Instruction,
		arg.ID,
		arg.ProgramWeekDayID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDayBlockOrder = `-- name: UpdateDayBlockOrder :exec
UPDATE mentorix.program_week_day_blocks SET
  sort_order = $3
WHERE id = $1 AND program_week_day_id = $2
`

type UpdateDayBlockOrderParams struct {
	ID               pgtype.UUID `json:"id"`
	ProgramWeekDayID pgtype.UUID `json:"program_week_day_id"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) UpdateDayBlockOrder(ctx context.Context, arg UpdateDayBlockOrderParams) error {
	_, err := q.db.Exec(ctx, updateDayBlockOrder, arg.ID, arg.ProgramWeekDayID, arg.SortOrder)
	return err
}

const updateDayBlockPlacement = `-- name: UpdateDayBlockPlacement :exec
UPDATE mentorix.program_week_day_blocks SET
  program_week_day_id = $2,
  sort_order = $3
WHERE id = $1
`

type UpdateDayBlockPlacementParams struct {
	ID               pgtype.UUID `json:"id"`
	ProgramWeekDayID pgtype.UUID `json:"program_week_day_id"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) UpdateDayBlockPlacement(ctx context.Context, arg UpdateDayBlockPlacementParams) error {
	_, err := q.db.Exec(ctx, updateDayBlockPlacement, arg.ID, arg.ProgramWeekDayID, arg.SortOrder)
	return err
}

const updateProgram = `-- name: UpdateProgram :execrows
UPDATE mentorix.programs SET
  modified_by = $1,
  modified_at = $2,
  name = COALESCE($3, name),
  name_ru = COALESCE($4, name_ru),
  description = COALESCE($5, description),
  description_ru = COALESCE($6, description_ru),
  category = COALESCE($7, category),
  difficulty = COALESCE($8, difficulty),
  preview_image_url = COALESCE($9, preview_image_url)
WHERE id = $10 AND deleted_at IS NULL
`

type UpdateProgramParams struct {
	ModifiedBy      pgtype.UUID `json:"modified_by"`
	ModifiedAt      time.Time   `json:"modified_at"`
	Name            *string     `json:"name"`
	NameRu          *string     `json:"name_ru"`
	Description     *string     `json:"description"`
	DescriptionRu   *string     `json:"description_ru"`
	Category        *string     `json:"category"`
	Difficulty      *string     `json:"difficulty"`
	PreviewImageUrl *string     `json:"preview_image_url"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProgram,
		arg.ModifiedBy,
		arg.ModifiedAt,
		arg.Name,
		arg.NameRu,
		arg.Description,
		arg.DescriptionRu,
		arg.Category,
		arg.Difficulty,
		arg.PreviewImageUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProgramDayOrder = `-- name: UpdateProgramDayOrder :exec
UPDATE mentorix.program_week_days SET
  sort_order = $3,
  day_number = $4
WHERE id = $1 AND week_id = $2
`

type UpdateProgramDayOrderParams struct {
	ID        pgtype.UUID `json:"id"`
	WeekID    pgtype.UUID `json:"week_id"`
	SortOrder int32       `json:"sort_order"`
	DayNumber int32       `json:"day_number"`
}

func (q *Queries) UpdateProgramDayOrder(ctx context.Context, arg UpdateProgramDayOrderParams) error {
	_, err := q.db.Exec(ctx, updateProgramDayOrder,
		arg.ID,
		arg.WeekID,
		arg.SortOrder,
		arg.DayNumber,
	)
	return err
}

const updateProgramWeekOrder = `-- name: UpdateProgramWeekOrder :exec
UPDATE mentorix.program_weeks SET
  sort_order = $3,
  week_number = $4
WHERE id = $1 AND program_id = $2
`

type UpdateProgramWeekOrderParams struct {
	ID         pgtype.UUID `json:"id"`
	ProgramID  pgtype.UUID `json:"program_id"`
	SortOrder  int32       `json:"sort_order"`
	WeekNumber int32       `json:"week_number"`
}

func (q *Queries) UpdateProgramWeekOrder(ctx context.Context, arg UpdateProgramWeekOrderParams) error {
	_, err := q.db.Exec(ctx, updateProgramWeekOrder,
		arg.ID,
		arg.ProgramID,
		arg.SortOrder,
		arg.WeekNumber,
	)
	return err
}

const weekBelongsToProgram = `-- name: WeekBelongsToProgram :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.program_weeks
  WHERE id = $1 AND program_id = $2
) AS ok
`

type WeekBelongsToProgramParams struct {
	ID        pgtype.UUID `json:"id"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) WeekBelongsToProgram(ctx context.Context, arg WeekBelongsToProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, weekBelongsToProgram, arg.ID, arg.ProgramID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}
