// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userHasAnyRole = `-- name: UserHasAnyRole :one
SELECT EXISTS(
  SELECT 1 FROM mentorix.user_roles
  WHERE user_id = $1 AND role = ANY($2::text[])
) AS ok
`

type UserHasAnyRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Roles  []string    `json:"roles"`
}

func (q *Queries) UserHasAnyRole(ctx context.Context, arg UserHasAnyRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasAnyRole, arg.UserID, arg.Roles)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}
