// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subscription.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTrainerUsage = `-- name: GetTrainerUsage :one
SELECT
  (
    SELECT COUNT(*) FROM mentorix.exercises e
    WHERE e.owner_trainer_id = t.id AND e.deleted_at IS NULL
  )::int AS exercises,
  (
    SELECT COUNT(*) FROM mentorix.programs p
    WHERE p.created_by = t.user_id
      AND p.status IN ('draft', 'published')
      AND p.deleted_at IS NULL
  )::int AS active_programs,
  (
    SELECT COUNT(*) FROM mentorix.trainer_clients tc
    WHERE tc.trainer_id = t.id AND tc.status = 'active'
  )::int AS active_clients
FROM mentorix.trainers t
WHERE t.id = $1
`

type GetTrainerUsageRow struct {
	Exercises      int32 `json:"exercises"`
	ActivePrograms int32 `json:"active_programs"`
	ActiveClients  int32 `json:"active_clients"`
}

func (q *Queries) GetTrainerUsage(ctx context.Context, id pgtype.UUID) (GetTrainerUsageRow, error) {
	row := q.db.QueryRow(ctx, getTrainerUsage, id)
	var i GetTrainerUsageRow
	err := row.Scan(&i.Exercises, &i.ActivePrograms, &i.ActiveClients)
	return i, err
}

const listActiveTrainerPlanEntitlements = `-- name: ListActiveTrainerPlanEntitlements :many
SELECT id, trainer_id, plan_code, source, status, valid_from, valid_until, created_at, modified_at
FROM mentorix.trainer_plan_entitlements
WHERE trainer_id = $1
  AND status = 'active'
  AND (valid_until IS NULL OR valid_until > now())
`

func (q *Queries) ListActiveTrainerPlanEntitlements(ctx context.Context, trainerID pgtype.UUID) ([]MentorixTrainerPlanEntitlement, error) {
	rows, err := q.db.Query(ctx, listActiveTrainerPlanEntitlements, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorixTrainerPlanEntitlement{}
	for rows.Next() {
		var i MentorixTrainerPlanEntitlement
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.PlanCode,
			&i.Source,
			&i.Status,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTrainerRow = `-- name: LockTrainerRow :one
SELECT id
FROM mentorix.trainers
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockTrainerRow(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockTrainerRow, id)
	err := row.Scan(&id)
	return id, err
}

const revokeAdminPlanGrant = `-- name: RevokeAdminPlanGrant :execrows
UPDATE mentorix.trainer_plan_entitlements
SET status = 'revoked', modified_at = now()
WHERE trainer_id = $1 AND source = 'admin' AND status = 'active'
`

func (q *Queries) RevokeAdminPlanGrant(ctx context.Context, trainerID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAdminPlanGrant, trainerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAdminPlanGrant = `-- name: UpsertAdminPlanGrant :one
INSERT INTO mentorix.trainer_plan_entitlements (trainer_id, plan_code, source, status, valid_until)
VALUES ($1, $2, 'admin', 'active', NULL)
ON CONFLICT (trainer_id) WHERE status = 'active' AND source = 'admin'
DO UPDATE SET plan_code = EXCLUDED.plan_code, modified_at = now()
RETURNING id, trainer_id, plan_code, source, status, valid_from, valid_until, created_at, modified_at
`

type UpsertAdminPlanGrantParams struct {
	TrainerID pgtype.UUID `json:"trainer_id"`
	PlanCode  string      `json:"plan_code"`
}

func (q *Queries) UpsertAdminPlanGrant(ctx context.Context, arg UpsertAdminPlanGrantParams) (MentorixTrainerPlanEntitlement, error) {
	row := q.db.QueryRow(ctx, upsertAdminPlanGrant, arg.TrainerID, arg.PlanCode)
	var i MentorixTrainerPlanEntitlement
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.PlanCode,
		&i.Source,
		&i.Status,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
