// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: telegram_client.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClientUserIDByTelegram = `-- name: GetClientUserIDByTelegram :one
SELECT user_id
FROM mentorix.auth_identities
WHERE provider = $1
  AND subject = $2
`

type GetClientUserIDByTelegramParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetClientUserIDByTelegram(ctx context.Context, arg GetClientUserIDByTelegramParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getClientUserIDByTelegram, arg.Provider, arg.Subject)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getProgramVersionDisplayByID = `-- name: GetProgramVersionDisplayByID :one
SELECT name, name_ru
FROM mentorix.program_versions
WHERE id = $1
`

type GetProgramVersionDisplayByIDRow struct {
	Name   string `json:"name"`
	NameRu string `json:"name_ru"`
}

func (q *Queries) GetProgramVersionDisplayByID(ctx context.Context, id pgtype.UUID) (GetProgramVersionDisplayByIDRow, error) {
	row := q.db.QueryRow(ctx, getProgramVersionDisplayByID, id)
	var i GetProgramVersionDisplayByIDRow
	err := row.Scan(&i.Name, &i.NameRu)
	return i, err
}

const getTelegramSubjectByUserID = `-- name: GetTelegramSubjectByUserID :one
SELECT subject
FROM mentorix.auth_identities
WHERE user_id = $1
  AND provider = $2
`

type GetTelegramSubjectByUserIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) GetTelegramSubjectByUserID(ctx context.Context, arg GetTelegramSubjectByUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getTelegramSubjectByUserID, arg.UserID, arg.Provider)
	var subject string
	err := row.Scan(&subject)
	return subject, err
}

const getTrainerDisplayNameByTrainerID = `-- name: GetTrainerDisplayNameByTrainerID :one
SELECT u.display_name
FROM mentorix.trainers t
INNER JOIN mentorix.users u ON u.id = t.user_id
WHERE t.id = $1
`

func (q *Queries) GetTrainerDisplayNameByTrainerID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTrainerDisplayNameByTrainerID, id)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const listClientTrainersByTelegramUser = `-- name: ListClientTrainersByTelegramUser :many
SELECT
  tc.trainer_id,
  tu.display_name AS trainer_display_name,
  pa.id AS assignment_id,
  pv.name AS program_name,
  pv.name_ru AS program_name_ru
FROM mentorix.auth_identities ai
INNER JOIN mentorix.trainer_clients tc
  ON tc.client_user_id = ai.user_id
  AND tc.status = 'active'
INNER JOIN mentorix.trainers t ON t.id = tc.trainer_id
INNER JOIN mentorix.users tu ON tu.id = t.user_id
LEFT JOIN mentorix.program_assignments pa
  ON pa.trainer_id = tc.trainer_id
  AND pa.client_user_id = tc.client_user_id
  AND pa.status = 'active'
LEFT JOIN mentorix.program_versions pv ON pv.id = pa.program_version_id
WHERE ai.provider = $1
  AND ai.subject = $2
ORDER BY tc.created_at DESC
`

type ListClientTrainersByTelegramUserParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

type ListClientTrainersByTelegramUserRow struct {
	TrainerID          pgtype.UUID `json:"trainer_id"`
	TrainerDisplayName string      `json:"trainer_display_name"`
	AssignmentID       pgtype.UUID `json:"assignment_id"`
	ProgramName        *string     `json:"program_name"`
	ProgramNameRu      *string     `json:"program_name_ru"`
}

func (q *Queries) ListClientTrainersByTelegramUser(ctx context.Context, arg ListClientTrainersByTelegramUserParams) ([]ListClientTrainersByTelegramUserRow, error) {
	rows, err := q.db.Query(ctx, listClientTrainersByTelegramUser, arg.Provider, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientTrainersByTelegramUserRow{}
	for rows.Next() {
		var i ListClientTrainersByTelegramUserRow
		if err := rows.Scan(
			&i.TrainerID,
			&i.TrainerDisplayName,
			&i.AssignmentID,
			&i.ProgramName,
			&i.ProgramNameRu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
