// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trainer_invite.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeTrainerInvite = `-- name: ConsumeTrainerInvite :execrows
UPDATE mentorix.trainer_invites
SET consumed_at = $2,
    consumed_by = $3
WHERE id = $1
  AND consumed_at IS NULL
`

type ConsumeTrainerInviteParams struct {
	ID         pgtype.UUID        `json:"id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy pgtype.UUID        `json:"consumed_by"`
}

func (q *Queries) ConsumeTrainerInvite(ctx context.Context, arg ConsumeTrainerInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeTrainerInvite, arg.ID, arg.ConsumedAt, arg.ConsumedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAllTrainerClients = `-- name: CountAllTrainerClients :one
SELECT COUNT(DISTINCT tc.client_user_id)::int AS total
FROM mentorix.trainer_clients tc
INNER JOIN mentorix.users u ON u.id = tc.client_user_id
WHERE (
  $1::text IS NULL
  OR u.display_name ILIKE $1 ESCAPE '\'
)
`

func (q *Queries) CountAllTrainerClients(ctx context.Context, qPattern *string) (int32, error) {
	row := q.db.QueryRow(ctx, countAllTrainerClients, qPattern)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countTrainerClients = `-- name: CountTrainerClients :one
SELECT COUNT(*)::int AS total
FROM mentorix.trainer_clients tc
INNER JOIN mentorix.users u ON u.id = tc.client_user_id
WHERE tc.trainer_id = $1
  AND (
    $2::text IS NULL
    OR u.display_name ILIKE $2 ESCAPE '\'
  )
`

type CountTrainerClientsParams struct {
	TrainerID pgtype.UUID `json:"trainer_id"`
	QPattern  *string     `json:"q_pattern"`
}

func (q *Queries) CountTrainerClients(ctx context.Context, arg CountTrainerClientsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countTrainerClients, arg.TrainerID, arg.QPattern)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getAuthIdentityUserID = `-- name: GetAuthIdentityUserID :one
SELECT user_id
FROM mentorix.auth_identities
WHERE provider = $1
  AND subject = $2
`

type GetAuthIdentityUserIDParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetAuthIdentityUserID(ctx context.Context, arg GetAuthIdentityUserIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityUserID, arg.Provider, arg.Subject)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getTrainerClient = `-- name: GetTrainerClient :one
SELECT trainer_id, client_user_id, status, blocked_at, created_at
FROM mentorix.trainer_clients
WHERE trainer_id = $1
  AND client_user_id = $2
`

type GetTrainerClientParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

type GetTrainerClientRow struct {
	TrainerID    pgtype.UUID        `json:"trainer_id"`
	ClientUserID pgtype.UUID        `json:"client_user_id"`
	Status       string             `json:"status"`
	BlockedAt    pgtype.Timestamptz `json:"blocked_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

func (q *Queries) GetTrainerClient(ctx context.Context, arg GetTrainerClientParams) (GetTrainerClientRow, error) {
	row := q.db.QueryRow(ctx, getTrainerClient, arg.TrainerID, arg.ClientUserID)
	var i GetTrainerClientRow
	err := row.Scan(
		&i.TrainerID,
		&i.ClientUserID,
		&i.Status,
		&i.BlockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTrainerInviteByTokenForUpdate = `-- name: GetTrainerInviteByTokenForUpdate :one
SELECT id, token, expires_at, consumed_at, consumed_by, created_at, trainer_id
FROM mentorix.trainer_invites
WHERE token = $1
FOR UPDATE
`

func (q *Queries) GetTrainerInviteByTokenForUpdate(ctx context.Context, token string) (MentorixTrainerInvite, error) {
	row := q.db.QueryRow(ctx, getTrainerInviteByTokenForUpdate, token)
	var i MentorixTrainerInvite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.CreatedAt,
		&i.TrainerID,
	)
	return i, err
}

const getTrainerUserDisplayName = `-- name: GetTrainerUserDisplayName :one
SELECT u.display_name
FROM mentorix.trainers t
INNER JOIN mentorix.users u ON u.id = t.user_id
WHERE t.id = $1
`

func (q *Queries) GetTrainerUserDisplayName(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTrainerUserDisplayName, id)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const insertTrainerClient = `-- name: InsertTrainerClient :exec
INSERT INTO mentorix.trainer_clients (trainer_id, client_user_id, status)
VALUES ($1, $2, 'active')
ON CONFLICT (trainer_id, client_user_id) DO NOTHING
`

type InsertTrainerClientParams struct {
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

func (q *Queries) InsertTrainerClient(ctx context.Context, arg InsertTrainerClientParams) error {
	_, err := q.db.Exec(ctx, insertTrainerClient, arg.TrainerID, arg.ClientUserID)
	return err
}

const insertTrainerInvite = `-- name: InsertTrainerInvite :one
INSERT INTO mentorix.trainer_invites (trainer_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token, expires_at, consumed_at, consumed_by, created_at, trainer_id
`

type InsertTrainerInviteParams struct {
	TrainerID pgtype.UUID `json:"trainer_id"`
	Token     string      `json:"token"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) InsertTrainerInvite(ctx context.Context, arg InsertTrainerInviteParams) (MentorixTrainerInvite, error) {
	row := q.db.QueryRow(ctx, insertTrainerInvite, arg.TrainerID, arg.Token, arg.ExpiresAt)
	var i MentorixTrainerInvite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.CreatedAt,
		&i.TrainerID,
	)
	return i, err
}

const listAllTrainerClients = `-- name: ListAllTrainerClients :many
WITH ranked_link AS (
  SELECT DISTINCT ON (tc.client_user_id)
    tc.client_user_id,
    tc.trainer_id,
    tc.status,
    tc.created_at
  FROM mentorix.trainer_clients tc
  ORDER BY
    tc.client_user_id,
    CASE
      WHEN $6::uuid IS NOT NULL
        AND tc.trainer_id = $6::uuid
      THEN 0
      ELSE 1
    END,
    tc.created_at DESC
)
SELECT
  rl.client_user_id,
  t.user_id AS trainer_user_id,
  rl.status,
  rl.created_at,
  u.display_name,
  u.avatar_file_path,
  pa.id AS assignment_id,
  pa.program_id,
  pa.program_version_id,
  pa.status AS assignment_status,
  pa.assigned_at,
  pv.name AS program_name,
  pv.name_ru AS program_name_ru
FROM ranked_link rl
INNER JOIN mentorix.trainers t ON t.id = rl.trainer_id
INNER JOIN mentorix.users u ON u.id = rl.client_user_id
LEFT JOIN mentorix.program_assignments pa
  ON pa.trainer_id = rl.trainer_id
  AND pa.client_user_id = rl.client_user_id
  AND pa.status = 'active'
LEFT JOIN mentorix.program_versions pv ON pv.id = pa.program_version_id
WHERE (
  $1::text IS NULL
  OR u.display_name ILIKE $1 ESCAPE '\'
)
ORDER BY
  CASE WHEN $2 = 'display_name' AND $3 = 'asc' THEN u.display_name END ASC NULLS LAST,
  CASE WHEN $2 = 'display_name' AND $3 = 'desc' THEN u.display_name END DESC NULLS LAST,
  CASE WHEN $2 = 'linked_at' AND $3 = 'asc' THEN rl.created_at END ASC NULLS LAST,
  CASE WHEN $2 = 'linked_at' AND $3 = 'desc' THEN rl.created_at END DESC NULLS LAST,
  rl.client_user_id ASC
LIMIT $5 OFFSET $4
`

type ListAllTrainerClientsParams struct {
	QPattern        *string     `json:"q_pattern"`
	SortBy          interface{} `json:"sort_by"`
	SortOrder       interface{} `json:"sort_order"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
	PreferTrainerID pgtype.UUID `json:"prefer_trainer_id"`
}

type ListAllTrainerClientsRow struct {
	ClientUserID     pgtype.UUID        `json:"client_user_id"`
	TrainerUserID    pgtype.UUID        `json:"trainer_user_id"`
	Status           string             `json:"status"`
	CreatedAt        time.Time          `json:"created_at"`
	DisplayName      string             `json:"display_name"`
	AvatarFilePath   string             `json:"avatar_file_path"`
	AssignmentID     pgtype.UUID        `json:"assignment_id"`
	ProgramID        pgtype.UUID        `json:"program_id"`
	ProgramVersionID pgtype.UUID        `json:"program_version_id"`
	AssignmentStatus *string            `json:"assignment_status"`
	AssignedAt       pgtype.Timestamptz `json:"assigned_at"`
	ProgramName      *string            `json:"program_name"`
	ProgramNameRu    *string            `json:"program_name_ru"`
}

func (q *Queries) ListAllTrainerClients(ctx context.Context, arg ListAllTrainerClientsParams) ([]ListAllTrainerClientsRow, error) {
	rows, err := q.db.Query(ctx, listAllTrainerClients,
		arg.QPattern,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
		arg.PreferTrainerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTrainerClientsRow{}
	for rows.Next() {
		var i ListAllTrainerClientsRow
		if err := rows.Scan(
			&i.ClientUserID,
			&i.TrainerUserID,
			&i.Status,
			&i.CreatedAt,
			&i.DisplayName,
			&i.AvatarFilePath,
			&i.AssignmentID,
			&i.ProgramID,
			&i.ProgramVersionID,
			&i.AssignmentStatus,
			&i.AssignedAt,
			&i.ProgramName,
			&i.ProgramNameRu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainerClients = `-- name: ListTrainerClients :many
SELECT
  tc.client_user_id,
  t.user_id AS trainer_user_id,
  tc.status,
  tc.created_at,
  u.display_name,
  u.avatar_file_path,
  pa.id AS assignment_id,
  pa.program_id,
  pa.program_version_id,
  pa.status AS assignment_status,
  pa.assigned_at,
  pv.name AS program_name,
  pv.name_ru AS program_name_ru
FROM mentorix.trainer_clients tc
INNER JOIN mentorix.trainers t ON t.id = tc.trainer_id
INNER JOIN mentorix.users u ON u.id = tc.client_user_id
LEFT JOIN mentorix.program_assignments pa
  ON pa.trainer_id = tc.trainer_id
  AND pa.client_user_id = tc.client_user_id
  AND pa.status = 'active'
LEFT JOIN mentorix.program_versions pv ON pv.id = pa.program_version_id
WHERE tc.trainer_id = $1
  AND (
    $2::text IS NULL
    OR u.display_name ILIKE $2 ESCAPE '\'
  )
ORDER BY
  CASE WHEN $3 = 'display_name' AND $4 = 'asc' THEN u.display_name END ASC NULLS LAST,
  CASE WHEN $3 = 'display_name' AND $4 = 'desc' THEN u.display_name END DESC NULLS LAST,
  CASE WHEN $3 = 'linked_at' AND $4 = 'asc' THEN tc.created_at END ASC NULLS LAST,
  CASE WHEN $3 = 'linked_at' AND $4 = 'desc' THEN tc.created_at END DESC NULLS LAST,
  tc.client_user_id ASC
LIMIT $6 OFFSET $5
`

type ListTrainerClientsParams struct {
	TrainerID pgtype.UUID `json:"trainer_id"`
	QPattern  *string     `json:"q_pattern"`
	SortBy    interface{} `json:"sort_by"`
	SortOrder interface{} `json:"sort_order"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

type ListTrainerClientsRow struct {
	ClientUserID     pgtype.UUID        `json:"client_user_id"`
	TrainerUserID    pgtype.UUID        `json:"trainer_user_id"`
	Status           string             `json:"status"`
	CreatedAt        time.Time          `json:"created_at"`
	DisplayName      string             `json:"display_name"`
	AvatarFilePath   string             `json:"avatar_file_path"`
	AssignmentID     pgtype.UUID        `json:"assignment_id"`
	ProgramID        pgtype.UUID        `json:"program_id"`
	ProgramVersionID pgtype.UUID        `json:"program_version_id"`
	AssignmentStatus *string            `json:"assignment_status"`
	AssignedAt       pgtype.Timestamptz `json:"assigned_at"`
	ProgramName      *string            `json:"program_name"`
	ProgramNameRu    *string            `json:"program_name_ru"`
}

func (q *Queries) ListTrainerClients(ctx context.Context, arg ListTrainerClientsParams) ([]ListTrainerClientsRow, error) {
	rows, err := q.db.Query(ctx, listTrainerClients,
		arg.TrainerID,
		arg.QPattern,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrainerClientsRow{}
	for rows.Next() {
		var i ListTrainerClientsRow
		if err := rows.Scan(
			&i.ClientUserID,
			&i.TrainerUserID,
			&i.Status,
			&i.CreatedAt,
			&i.DisplayName,
			&i.AvatarFilePath,
			&i.AssignmentID,
			&i.ProgramID,
			&i.ProgramVersionID,
			&i.AssignmentStatus,
			&i.AssignedAt,
			&i.ProgramName,
			&i.ProgramNameRu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
