// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workout_comment.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompletionComment = `-- name: CreateCompletionComment :one
INSERT INTO mentorix.client_workout_completion_comments (
  client_workout_completion_id,
  trainer_id,
  comment_text
) VALUES ($1, $2, $3)
RETURNING id, client_workout_completion_id, trainer_id, comment_text, created_at
`

type CreateCompletionCommentParams struct {
	ClientWorkoutCompletionID pgtype.UUID `json:"client_workout_completion_id"`
	TrainerID                 pgtype.UUID `json:"trainer_id"`
	CommentText               string      `json:"comment_text"`
}

func (q *Queries) CreateCompletionComment(ctx context.Context, arg CreateCompletionCommentParams) (MentorixClientWorkoutCompletionComment, error) {
	row := q.db.QueryRow(ctx, createCompletionComment, arg.ClientWorkoutCompletionID, arg.TrainerID, arg.CommentText)
	var i MentorixClientWorkoutCompletionComment
	err := row.Scan(
		&i.ID,
		&i.ClientWorkoutCompletionID,
		&i.TrainerID,
		&i.CommentText,
		&i.CreatedAt,
	)
	return i, err
}

const getCompletionForComment = `-- name: GetCompletionForComment :one

SELECT
  id,
  client_user_id,
  week_number,
  day_number,
  program_name,
  program_name_ru,
  result_text
FROM mentorix.client_workout_completions
WHERE id = $1
  AND trainer_id = $2
  AND client_user_id = $3
`

type GetCompletionForCommentParams struct {
	ID           pgtype.UUID `json:"id"`
	TrainerID    pgtype.UUID `json:"trainer_id"`
	ClientUserID pgtype.UUID `json:"client_user_id"`
}

type GetCompletionForCommentRow struct {
	ID            pgtype.UUID `json:"id"`
	ClientUserID  pgtype.UUID `json:"client_user_id"`
	WeekNumber    int32       `json:"week_number"`
	DayNumber     int32       `json:"day_number"`
	ProgramName   string      `json:"program_name"`
	ProgramNameRu string      `json:"program_name_ru"`
	ResultText    string      `json:"result_text"`
}

// Trainer replies on client workout completions.
// Scopes the completion to the trainer/client pair and returns the snapshot
// fields needed for the Telegram notification text.
func (q *Queries) GetCompletionForComment(ctx context.Context, arg GetCompletionForCommentParams) (GetCompletionForCommentRow, error) {
	row := q.db.QueryRow(ctx, getCompletionForComment, arg.ID, arg.TrainerID, arg.ClientUserID)
	var i GetCompletionForCommentRow
	err := row.Scan(
		&i.ID,
		&i.ClientUserID,
		&i.WeekNumber,
		&i.DayNumber,
		&i.ProgramName,
		&i.ProgramNameRu,
		&i.ResultText,
	)
	return i, err
}

const listCommentsForCompletions = `-- name: ListCommentsForCompletions :many
SELECT
  id,
  client_workout_completion_id,
  comment_text,
  created_at
FROM mentorix.client_workout_completion_comments
WHERE client_workout_completion_id = ANY ($1::uuid[])
ORDER BY created_at ASC, id ASC
`

type ListCommentsForCompletionsRow struct {
	ID                        pgtype.UUID `json:"id"`
	ClientWorkoutCompletionID pgtype.UUID `json:"client_workout_completion_id"`
	CommentText               string      `json:"comment_text"`
	CreatedAt                 time.Time   `json:"created_at"`
}

func (q *Queries) ListCommentsForCompletions(ctx context.Context, completionIds []pgtype.UUID) ([]ListCommentsForCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listCommentsForCompletions, completionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsForCompletionsRow{}
	for rows.Next() {
		var i ListCommentsForCompletionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientWorkoutCompletionID,
			&i.CommentText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
