-- Generated by scripts/schema-sync.sh — do not edit by hand.
-- Source: db/migrations/*.up.sql
-- Regenerate: ./scripts/schema-sync.sh


-- >>> 000001_init.up.sql
-- Core schema for Mentorix (MVP foundation).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS mentorix;

CREATE TABLE IF NOT EXISTS mentorix.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  primary_email text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- One logical user can have multiple sign-in methods (email/password, telegram, oauth, ...).
CREATE TABLE IF NOT EXISTS mentorix.auth_identities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  provider text NOT NULL,
  subject text NOT NULL,
  password_hash text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT auth_identities_provider_subject_uniq UNIQUE (provider, subject)
);

-- Roles are per-user and can be multiple at the same time.
CREATE TABLE IF NOT EXISTS mentorix.user_roles (
  user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  role text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role),
  CONSTRAINT user_roles_role_check CHECK (role IN ('admin', 'trainer', 'client'))
);

-- A trainer is a user with the "trainer" role. Table exists for trainer-specific fields later.
CREATE TABLE IF NOT EXISTS mentorix.trainers (
  user_id uuid PRIMARY KEY REFERENCES mentorix.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Client relationship: one client can belong to multiple trainers.
CREATE TABLE IF NOT EXISTS mentorix.trainer_clients (
  trainer_user_id uuid NOT NULL REFERENCES mentorix.trainers(user_id) ON DELETE CASCADE,
  client_user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'active',
  blocked_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (trainer_user_id, client_user_id),
  CONSTRAINT trainer_clients_status_check CHECK (status IN ('active', 'blocked'))
);

-- One-time invite token (24h TTL at the application layer).
CREATE TABLE IF NOT EXISTS mentorix.invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trainer_user_id uuid NOT NULL REFERENCES mentorix.trainers(user_id) ON DELETE CASCADE,
  token text NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz NULL,
  consumed_by_user_id uuid NULL REFERENCES mentorix.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT invites_token_uniq UNIQUE (token),
  CONSTRAINT invites_consumed_consistency CHECK (
    (consumed_at IS NULL AND consumed_by_user_id IS NULL) OR
    (consumed_at IS NOT NULL AND consumed_by_user_id IS NOT NULL)
  )
);

-- One-time codes used to link Telegram users to a mobile/app login later.
CREATE TABLE IF NOT EXISTS mentorix.link_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  code text NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT link_codes_code_uniq UNIQUE (code)
);


-- >>> 000002_refresh_sessions.up.sql
CREATE TABLE mentorix.refresh_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  token_hash bytea NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT refresh_sessions_token_hash_uniq UNIQUE (token_hash)
);

CREATE INDEX refresh_sessions_user_id_idx ON mentorix.refresh_sessions (user_id);

-- >>> 000003_exercises.up.sql
CREATE TABLE mentorix.exercises (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT '',
  name_ru text NOT NULL DEFAULT '',
  added_by uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  modified_by uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  modified_at timestamptz NOT NULL DEFAULT now(),
  equipment text NULL,
  type text NOT NULL,
  muscle_group text NOT NULL,
  description text NOT NULL DEFAULT '',
  description_ru text NOT NULL DEFAULT '',
  difficulty text NOT NULL,
  video_url text NOT NULL DEFAULT '',
  preview_image_url text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exercises_muscle_group_check CHECK (
    muscle_group IN ('compound', 'chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'full_body')
  ),
  CONSTRAINT exercises_type_check CHECK (
    type IN ('strength', 'cardio', 'mixed_modal', 'intervals', 'stretching', 'metcon', 'skill_work', 'accessory')
  ),
  CONSTRAINT exercises_equipment_check CHECK (
    equipment IS NULL OR equipment IN (
      'barbell', 'dumbbells', 'kettlebell', 'pull_up_bar', 'squat_rack', 'rowing_machine',
      'assault_bike', 'jump_rope', 'plyo_box', 'medicine_ball', 'wall_ball', 'resistance_bands',
      'battle_ropes', 'gymnastic_rings', 'sandbag', 'sled', 'weight_plates'
    )
  ),
  CONSTRAINT exercises_difficulty_check CHECK (
    difficulty IN ('beginner', 'intermediate', 'advanced', 'expert')
  )
);

CREATE INDEX exercises_name_idx ON mentorix.exercises (name);

-- >>> 000004_exercise_enum_snake_case.up.sql
UPDATE mentorix.exercises SET muscle_group = 'full_body' WHERE muscle_group = 'full-body';
UPDATE mentorix.exercises SET type = 'mixed_modal' WHERE type = 'mixed-modal';
UPDATE mentorix.exercises SET type = 'skill_work' WHERE type = 'skill-work';
UPDATE mentorix.exercises SET equipment = REPLACE(equipment, '-', '_') WHERE equipment IS NOT NULL;

ALTER TABLE mentorix.exercises DROP CONSTRAINT exercises_muscle_group_check;
ALTER TABLE mentorix.exercises DROP CONSTRAINT exercises_type_check;
ALTER TABLE mentorix.exercises DROP CONSTRAINT exercises_equipment_check;

ALTER TABLE mentorix.exercises ADD CONSTRAINT exercises_muscle_group_check CHECK (
  muscle_group IN ('compound', 'chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'full_body')
);

ALTER TABLE mentorix.exercises ADD CONSTRAINT exercises_type_check CHECK (
  type IN ('strength', 'cardio', 'mixed_modal', 'intervals', 'stretching', 'metcon', 'skill_work', 'accessory')
);

ALTER TABLE mentorix.exercises ADD CONSTRAINT exercises_equipment_check CHECK (
  equipment IS NULL OR equipment IN (
    'barbell', 'dumbbells', 'kettlebell', 'pull_up_bar', 'squat_rack', 'rowing_machine',
    'assault_bike', 'jump_rope', 'plyo_box', 'medicine_ball', 'wall_ball', 'resistance_bands',
    'battle_ropes', 'gymnastic_rings', 'sandbag', 'sled', 'weight_plates'
  )
);

-- >>> 000005_programs.up.sql
CREATE TABLE mentorix.programs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  modified_by uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'draft',
  name text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  category text NULL,
  difficulty text NULL,
  preview_image_url text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  modified_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL,
  CONSTRAINT programs_status_check CHECK (status IN ('draft', 'published', 'archived')),
  CONSTRAINT programs_category_check CHECK (
    category IS NULL OR category IN (
      'weight_loss', 'muscle_gain', 'rehabilitation', 'endurance', 'functional'
    )
  ),
  CONSTRAINT programs_difficulty_check CHECK (
    difficulty IS NULL OR difficulty IN ('beginner', 'intermediate', 'advanced', 'expert')
  )
);

CREATE TABLE mentorix.program_days (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL REFERENCES mentorix.programs(id) ON DELETE CASCADE,
  day_number int NOT NULL,
  sort_order int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT program_days_program_day_number_uniq UNIQUE (program_id, day_number)
);

CREATE TABLE mentorix.program_day_exercises (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  program_day_id uuid NOT NULL REFERENCES mentorix.program_days(id) ON DELETE CASCADE,
  exercise_id uuid NOT NULL REFERENCES mentorix.exercises(id) ON DELETE RESTRICT,
  sort_order int NOT NULL,
  sets int NULL,
  reps int NULL,
  weight_kg numeric(6, 2) NULL,
  instruction text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX programs_created_by_idx ON mentorix.programs (created_by);
CREATE INDEX programs_status_idx ON mentorix.programs (status);
CREATE INDEX programs_deleted_at_idx ON mentorix.programs (deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX program_days_program_id_idx ON mentorix.program_days (program_id);
CREATE INDEX program_day_exercises_day_id_idx ON mentorix.program_day_exercises (program_day_id);

-- >>> 000006_text_name_defaults.up.sql
UPDATE mentorix.programs SET name = '' WHERE name IS NULL;

ALTER TABLE mentorix.programs
  ALTER COLUMN name SET DEFAULT '',
  ALTER COLUMN name SET NOT NULL;

ALTER TABLE mentorix.exercises
  ALTER COLUMN name SET DEFAULT '';

-- >>> 000007_schema_naming_unification.up.sql
-- Unify table/column naming across mentorix schema.

-- 1. Rename tables
ALTER TABLE mentorix.refresh_sessions RENAME TO auth_refresh_sessions;
ALTER TABLE mentorix.invites RENAME TO trainer_invites;
ALTER TABLE mentorix.link_codes RENAME TO user_link_codes;

ALTER INDEX mentorix.refresh_sessions_user_id_idx RENAME TO auth_refresh_sessions_user_id_idx;
ALTER TABLE mentorix.auth_refresh_sessions
  RENAME CONSTRAINT refresh_sessions_token_hash_uniq TO auth_refresh_sessions_token_hash_uniq;

ALTER TABLE mentorix.trainer_invites
  RENAME CONSTRAINT invites_token_uniq TO trainer_invites_token_uniq;
ALTER TABLE mentorix.trainer_invites
  RENAME CONSTRAINT invites_consumed_consistency TO trainer_invites_consumed_consistency;

ALTER TABLE mentorix.user_link_codes
  RENAME CONSTRAINT link_codes_code_uniq TO user_link_codes_code_uniq;

-- 2. trainers: add surrogate id column
ALTER TABLE mentorix.trainers ADD COLUMN id uuid DEFAULT gen_random_uuid();
UPDATE mentorix.trainers SET id = gen_random_uuid() WHERE id IS NULL;
ALTER TABLE mentorix.trainers ALTER COLUMN id SET NOT NULL;
ALTER TABLE mentorix.trainers ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- 3. Drop FKs that reference trainers(user_id) before PK change
ALTER TABLE mentorix.trainer_clients DROP CONSTRAINT trainer_clients_trainer_user_id_fkey;
ALTER TABLE mentorix.trainer_invites DROP CONSTRAINT invites_trainer_user_id_fkey;

-- 4. Switch trainers PK to id
ALTER TABLE mentorix.trainers DROP CONSTRAINT trainers_pkey;
ALTER TABLE mentorix.trainers ADD PRIMARY KEY (id);
ALTER TABLE mentorix.trainers ADD CONSTRAINT trainers_user_id_uniq UNIQUE (user_id);

-- 5. trainer_clients: trainer_user_id -> trainer_id -> trainers(id)
ALTER TABLE mentorix.trainer_clients ADD COLUMN trainer_id uuid;
UPDATE mentorix.trainer_clients tc
SET trainer_id = t.id
FROM mentorix.trainers t
WHERE tc.trainer_user_id = t.user_id;
ALTER TABLE mentorix.trainer_clients ALTER COLUMN trainer_id SET NOT NULL;

ALTER TABLE mentorix.trainer_clients DROP CONSTRAINT trainer_clients_pkey;
ALTER TABLE mentorix.trainer_clients DROP COLUMN trainer_user_id;
ALTER TABLE mentorix.trainer_clients ADD PRIMARY KEY (trainer_id, client_user_id);
ALTER TABLE mentorix.trainer_clients ADD CONSTRAINT trainer_clients_trainer_id_fkey
  FOREIGN KEY (trainer_id) REFERENCES mentorix.trainers(id) ON DELETE CASCADE;

-- 6. trainer_invites: trainer_user_id -> trainer_id -> trainers(id)
ALTER TABLE mentorix.trainer_invites ADD COLUMN trainer_id uuid;
UPDATE mentorix.trainer_invites ti
SET trainer_id = t.id
FROM mentorix.trainers t
WHERE ti.trainer_user_id = t.user_id;
ALTER TABLE mentorix.trainer_invites ALTER COLUMN trainer_id SET NOT NULL;

ALTER TABLE mentorix.trainer_invites DROP COLUMN trainer_user_id;
ALTER TABLE mentorix.trainer_invites ADD CONSTRAINT trainer_invites_trainer_id_fkey
  FOREIGN KEY (trainer_id) REFERENCES mentorix.trainers(id) ON DELETE CASCADE;

-- 7. exercises column renames
ALTER TABLE mentorix.exercises RENAME COLUMN added_by TO created_by;
ALTER TABLE mentorix.exercises RENAME COLUMN type TO exercise_type;
ALTER TABLE mentorix.exercises RENAME CONSTRAINT exercises_type_check TO exercises_exercise_type_check;

-- 8. trainer_invites: consumed_by_user_id -> consumed_by
ALTER TABLE mentorix.trainer_invites RENAME COLUMN consumed_by_user_id TO consumed_by;

-- 9. audit columns on program children
ALTER TABLE mentorix.program_days
  ADD COLUMN modified_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN modified_by uuid NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT;

ALTER TABLE mentorix.program_day_exercises
  ADD COLUMN modified_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN modified_by uuid NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT;

-- 10. indexes
CREATE INDEX auth_identities_user_id_idx ON mentorix.auth_identities (user_id);
CREATE INDEX trainer_clients_trainer_id_idx ON mentorix.trainer_clients (trainer_id);
CREATE INDEX trainer_clients_client_user_id_idx ON mentorix.trainer_clients (client_user_id);
CREATE INDEX trainer_invites_trainer_id_idx ON mentorix.trainer_invites (trainer_id);
ALTER INDEX mentorix.program_day_exercises_day_id_idx
  RENAME TO program_day_exercises_program_day_id_idx;

-- >>> 000008_exercises_soft_delete.up.sql
ALTER TABLE mentorix.exercises
  ADD COLUMN deleted_at timestamptz NULL;

CREATE INDEX exercises_deleted_at_idx ON mentorix.exercises (deleted_at)
  WHERE deleted_at IS NULL;

-- >>> 000009_programs_name_ru_description_ru.up.sql
ALTER TABLE mentorix.programs
  ADD COLUMN name_ru text NOT NULL DEFAULT '',
  ADD COLUMN description_ru text NOT NULL DEFAULT '';

-- >>> 000010_users_display_name.up.sql
ALTER TABLE mentorix.users
  ADD COLUMN display_name text NOT NULL DEFAULT '';

-- >>> 000011_program_weeks.up.sql
CREATE TABLE mentorix.program_weeks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL REFERENCES mentorix.programs(id) ON DELETE CASCADE,
  week_number int NOT NULL,
  sort_order int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  modified_at timestamptz NOT NULL DEFAULT now(),
  modified_by uuid NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  CONSTRAINT program_weeks_program_week_number_uniq UNIQUE (program_id, week_number)
);

CREATE INDEX program_weeks_program_id_idx ON mentorix.program_weeks (program_id);

ALTER TABLE mentorix.program_days ADD COLUMN week_id uuid NULL;

INSERT INTO mentorix.program_weeks (program_id, week_number, sort_order)
SELECT DISTINCT program_id, 1, 1
FROM mentorix.program_days;

INSERT INTO mentorix.program_weeks (program_id, week_number, sort_order)
SELECT p.id, 1, 1
FROM mentorix.programs p
WHERE p.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM mentorix.program_weeks pw WHERE pw.program_id = p.id
  );

UPDATE mentorix.program_days pd
SET week_id = pw.id
FROM mentorix.program_weeks pw
WHERE pw.program_id = pd.program_id
  AND pw.week_number = 1
  AND pd.week_id IS NULL;

ALTER TABLE mentorix.program_days
  ALTER COLUMN week_id SET NOT NULL;

ALTER TABLE mentorix.program_days
  ADD CONSTRAINT program_days_week_id_fkey
  FOREIGN KEY (week_id) REFERENCES mentorix.program_weeks(id) ON DELETE CASCADE;

ALTER TABLE mentorix.program_days
  DROP CONSTRAINT program_days_program_day_number_uniq;

ALTER TABLE mentorix.program_days
  ADD CONSTRAINT program_days_week_day_number_uniq UNIQUE (week_id, day_number);

CREATE INDEX program_days_week_id_idx ON mentorix.program_days (week_id);
