-- Generated by scripts/schema-sync.sh — do not edit by hand.
-- Source: db/migrations/*.up.sql
-- Regenerate: ./scripts/schema-sync.sh


-- >>> 000001_init.up.sql
-- Core schema for Mentorix (MVP foundation).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS mentorix;

CREATE TABLE IF NOT EXISTS mentorix.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  primary_email text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- One logical user can have multiple sign-in methods (email/password, telegram, oauth, ...).
CREATE TABLE IF NOT EXISTS mentorix.auth_identities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  provider text NOT NULL,
  subject text NOT NULL,
  password_hash text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT auth_identities_provider_subject_uniq UNIQUE (provider, subject)
);

-- Roles are per-user and can be multiple at the same time.
CREATE TABLE IF NOT EXISTS mentorix.user_roles (
  user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  role text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role),
  CONSTRAINT user_roles_role_check CHECK (role IN ('admin', 'trainer', 'client'))
);

-- A trainer is a user with the "trainer" role. Table exists for trainer-specific fields later.
CREATE TABLE IF NOT EXISTS mentorix.trainers (
  user_id uuid PRIMARY KEY REFERENCES mentorix.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Client relationship: one client can belong to multiple trainers.
CREATE TABLE IF NOT EXISTS mentorix.trainer_clients (
  trainer_user_id uuid NOT NULL REFERENCES mentorix.trainers(user_id) ON DELETE CASCADE,
  client_user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'active',
  blocked_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (trainer_user_id, client_user_id),
  CONSTRAINT trainer_clients_status_check CHECK (status IN ('active', 'blocked'))
);

-- One-time invite token (24h TTL at the application layer).
CREATE TABLE IF NOT EXISTS mentorix.invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trainer_user_id uuid NOT NULL REFERENCES mentorix.trainers(user_id) ON DELETE CASCADE,
  token text NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz NULL,
  consumed_by_user_id uuid NULL REFERENCES mentorix.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT invites_token_uniq UNIQUE (token),
  CONSTRAINT invites_consumed_consistency CHECK (
    (consumed_at IS NULL AND consumed_by_user_id IS NULL) OR
    (consumed_at IS NOT NULL AND consumed_by_user_id IS NOT NULL)
  )
);

-- One-time codes used to link Telegram users to a mobile/app login later.
CREATE TABLE IF NOT EXISTS mentorix.link_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  code text NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT link_codes_code_uniq UNIQUE (code)
);


-- >>> 000002_refresh_sessions.up.sql
CREATE TABLE mentorix.refresh_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE CASCADE,
  token_hash bytea NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT refresh_sessions_token_hash_uniq UNIQUE (token_hash)
);

CREATE INDEX refresh_sessions_user_id_idx ON mentorix.refresh_sessions (user_id);

-- >>> 000003_exercises.up.sql
CREATE TABLE mentorix.exercises (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT '',
  name_ru text NOT NULL DEFAULT '',
  added_by uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  modified_by uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  modified_at timestamptz NOT NULL DEFAULT now(),
  equipment text NULL,
  type text NOT NULL,
  muscle_group text NOT NULL,
  description text NOT NULL DEFAULT '',
  description_ru text NOT NULL DEFAULT '',
  difficulty text NOT NULL,
  video_url text NOT NULL DEFAULT '',
  preview_image_url text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exercises_muscle_group_check CHECK (
    muscle_group IN ('compound', 'chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'full_body')
  ),
  CONSTRAINT exercises_type_check CHECK (
    type IN ('strength', 'cardio', 'mixed_modal', 'intervals', 'stretching', 'metcon', 'skill_work', 'accessory')
  ),
  CONSTRAINT exercises_equipment_check CHECK (
    equipment IS NULL OR equipment IN (
      'barbell', 'dumbbells', 'kettlebell', 'pull_up_bar', 'squat_rack', 'rowing_machine',
      'assault_bike', 'jump_rope', 'plyo_box', 'medicine_ball', 'wall_ball', 'resistance_bands',
      'battle_ropes', 'gymnastic_rings', 'sandbag', 'sled', 'weight_plates'
    )
  ),
  CONSTRAINT exercises_difficulty_check CHECK (
    difficulty IN ('beginner', 'intermediate', 'advanced', 'expert')
  )
);

CREATE INDEX exercises_name_idx ON mentorix.exercises (name);

-- >>> 000004_exercise_enum_snake_case.up.sql
UPDATE mentorix.exercises SET muscle_group = 'full_body' WHERE muscle_group = 'full-body';
UPDATE mentorix.exercises SET type = 'mixed_modal' WHERE type = 'mixed-modal';
UPDATE mentorix.exercises SET type = 'skill_work' WHERE type = 'skill-work';
UPDATE mentorix.exercises SET equipment = REPLACE(equipment, '-', '_') WHERE equipment IS NOT NULL;

ALTER TABLE mentorix.exercises DROP CONSTRAINT exercises_muscle_group_check;
ALTER TABLE mentorix.exercises DROP CONSTRAINT exercises_type_check;
ALTER TABLE mentorix.exercises DROP CONSTRAINT exercises_equipment_check;

ALTER TABLE mentorix.exercises ADD CONSTRAINT exercises_muscle_group_check CHECK (
  muscle_group IN ('compound', 'chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'full_body')
);

ALTER TABLE mentorix.exercises ADD CONSTRAINT exercises_type_check CHECK (
  type IN ('strength', 'cardio', 'mixed_modal', 'intervals', 'stretching', 'metcon', 'skill_work', 'accessory')
);

ALTER TABLE mentorix.exercises ADD CONSTRAINT exercises_equipment_check CHECK (
  equipment IS NULL OR equipment IN (
    'barbell', 'dumbbells', 'kettlebell', 'pull_up_bar', 'squat_rack', 'rowing_machine',
    'assault_bike', 'jump_rope', 'plyo_box', 'medicine_ball', 'wall_ball', 'resistance_bands',
    'battle_ropes', 'gymnastic_rings', 'sandbag', 'sled', 'weight_plates'
  )
);

-- >>> 000005_programs.up.sql
CREATE TABLE mentorix.programs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  modified_by uuid NOT NULL REFERENCES mentorix.users(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'draft',
  name text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  category text NULL,
  difficulty text NULL,
  preview_image_url text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  modified_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL,
  CONSTRAINT programs_status_check CHECK (status IN ('draft', 'published', 'archived')),
  CONSTRAINT programs_category_check CHECK (
    category IS NULL OR category IN (
      'weight_loss', 'muscle_gain', 'rehabilitation', 'endurance', 'functional'
    )
  ),
  CONSTRAINT programs_difficulty_check CHECK (
    difficulty IS NULL OR difficulty IN ('beginner', 'intermediate', 'advanced', 'expert')
  )
);

CREATE TABLE mentorix.program_days (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL REFERENCES mentorix.programs(id) ON DELETE CASCADE,
  day_number int NOT NULL,
  sort_order int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT program_days_program_day_number_uniq UNIQUE (program_id, day_number)
);

CREATE TABLE mentorix.program_day_exercises (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  program_day_id uuid NOT NULL REFERENCES mentorix.program_days(id) ON DELETE CASCADE,
  exercise_id uuid NOT NULL REFERENCES mentorix.exercises(id) ON DELETE RESTRICT,
  sort_order int NOT NULL,
  sets int NULL,
  reps int NULL,
  weight_kg numeric(6, 2) NULL,
  instruction text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX programs_created_by_idx ON mentorix.programs (created_by);
CREATE INDEX programs_status_idx ON mentorix.programs (status);
CREATE INDEX programs_deleted_at_idx ON mentorix.programs (deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX program_days_program_id_idx ON mentorix.program_days (program_id);
CREATE INDEX program_day_exercises_day_id_idx ON mentorix.program_day_exercises (program_day_id);

-- >>> 000006_text_name_defaults.up.sql
UPDATE mentorix.programs SET name = '' WHERE name IS NULL;

ALTER TABLE mentorix.programs
  ALTER COLUMN name SET DEFAULT '',
  ALTER COLUMN name SET NOT NULL;

ALTER TABLE mentorix.exercises
  ALTER COLUMN name SET DEFAULT '';
