#!/usr/bin/env bash
# Builds db/schema.sql from golang-migrate .up.sql files (for sqlc).
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

out="db/schema.sql"
migrations_dir="db/migrations"

{
  echo "-- Generated by scripts/schema-sync.sh — do not edit by hand."
  echo "-- Source: ${migrations_dir}/*.up.sql"
  echo "-- Regenerate: ./scripts/schema-sync.sh"
  echo ""
} > "$out"

for f in "$migrations_dir"/*.up.sql; do
  [[ -f "$f" ]] || continue
  echo "" >> "$out"
  echo "-- >>> $(basename "$f")" >> "$out"
  cat "$f" >> "$out"
done

echo "Wrote $out"
